# -*- coding: utf-8 -*-
"""
Polars Native Operators

真正的 Polars native 实现，避免 pandas fallback，提升性能。
"""

# Technical indicators final (10 operators)
from .technical_final import (
    ElderRay,
    FisherTransform,
    PSAR,
    QQE,
    RSX,
    SupertrendDirection,
    TSI,
    TSI_signal,
    VortexMinus,
    VortexPlus,
)

# Miscellaneous operators (9 operators)
from .misc_final import (
    AshareOnePriceLimitStreak,
    CashFlowLifecycleStage,
    IndustryFiscalResid,
    IndustryRollingPCALoading,
    QuarterFromCumulative,
    RevisionDelta,
    SessionEventRecoveryScore,
    TurnoverChipAgeCostSurface,
    TurnoverChipOverhangSurface,
)

# Intraday/intra operators final (49 operators)
from .intraday_final import (
    # intraday_* (25 operators)
    IntradayActivityDurationCurvaturePolarsNative,
    IntradayBarrierApproachAccelerationPolarsNative,
    IntradayBvcImbalancePolarsNative,
    IntradayImpactAsymmetryPolarsNative,
    IntradayImpactBetaPolarsNative,
    IntradayImpactDecayRatePolarsNative,
    IntradayJumpTestStatPolarsNative,
    IntradayMedrvPolarsNative,
    IntradayMinrvPolarsNative,
    IntradayQuantileCurvePcaResidualPolarsNative,
    IntradayQuantileCurvePcaScorePolarsNative,
    IntradayRealizedPowerVariationPolarsNative,
    IntradayRealizedSemivarianceBalancePolarsNative,
    IntradayReturnWassersteinShiftPolarsNative,
    IntradayRvSignatureCurvaturePolarsNative,
    IntradayRvSignatureSlopePolarsNative,
    IntradaySessionShapeNoveltyPolarsNative,
    IntradaySubsampledRvDispersionPolarsNative,
    IntradayVolatilityConcentrationPolarsNative,
    IntradayVolatilityEntropyPolarsNative,
    IntradayVolatilitySignatureSlopePolarsNative,
    IntradayVolatilityTimeCentroidPolarsNative,
    IntradayVolumeClockPathEfficiencyPolarsNative,
    IntradayVolumeClockRoughnessPolarsNative,
    IntradayWassersteinPairDistancePolarsNative,
    # intra_* (24 operators)
    IntraEventPrePostContrastPolarsNative,
    IntraEventWindowReducePolarsNative,
    IntraImpulseEventDetectorPolarsNative,
    IntraLimitDurationPolarsNative,
    IntraLimitFirstHitTimePolarsNative,
    IntraLimitPreHitPressureProfilePolarsNative,
    IntraLimitReopenCountPolarsNative,
    IntraLiquidityResilienceCurveFitPolarsNative,
    IntraMultiresolutionResampleReducePolarsNative,
    IntraNeighborEventClassPolarsNative,
    IntraPostImpulseResponsePolarsNative,
    IntraProbeOutcomeScorePolarsNative,
    IntraProfileEarthMoverDistancePolarsNative,
    IntraResponseCurveFeaturesPolarsNative,
    IntraSliceMaskPairReducePolarsNative,
    IntraSliceMaskReducePolarsNative,
    IntraStateDwellStatsPolarsNative,
    IntraStateIntervalMomentPolarsNative,
    IntraStatePairSameSlotCorrPolarsNative,
    IntraSupplyAbsorptionScorePolarsNative,
    IntraUteHighPolarsNative,
    IntraUteLowPolarsNative,
    IntraVwapPathCurvaturePctPolarsNative,
    IntraVwapPathSlopePctPolarsNative,
)

# TS advanced batch 5 (64 operators)
from .ts_advanced_batch5 import (
    TSDistanceCorrelationPartialProxyPolarsNative,  # QUARANTINED: research_only
    TSFeatureModeSharePolarsNative,
    TSFeatureSubspaceRotationPolarsNative,  # QUARANTINED: research_only
    TSFIRLowpassCausalPolarsNative,
    TSFirstPassageBiasPolarsNative,
    TSFirstPassageConditionalTimePolarsNative,
    TSFirstPassageHitProbabilityPolarsNative,
    TSFisherInformationShiftPolarsNative,
    TSForbiddenOrdinalPatternRatioPolarsNative,
    TSFractionalDifferencePolarsNative,
    TSFractionalDifferenceDiscardedWeightMassPolarsNative,
    TSGeneralizedHurstExponentPolarsNative,
    TSGeneralizedHurstSpreadQ1Q4PolarsNative,
    TSGPDShapePWMPolarsNative,
    TSHInfinityLevelFilterPolarsNative,
    TSHampelFilterCausalPolarsNative,
    TSHankelEffectiveRankPolarsNative,
    TSHankelSingularGapPolarsNative,
    TSHartiganDipPolarsNative,
    TSHiguchiFractalDimensionPolarsNative,
    TSHillTailIndexPolarsNative,
    TSHSICPolarsNative,
    TSHurstDFAPolarsNative,
    TSHVGAssortativityPolarsNative,
    TSHVGClusteringCoefficientPolarsNative,
    TSHVGDegreeEntropyPolarsNative,
    TSHVGForwardBackwardAsymmetryPolarsNative,
    TSHVGMotifEntropyPolarsNative,
    TSHysteresisAgePolarsNative,
    TSHysteresisStatePolarsNative,
    TSIndustryLiquidityBetaPolarsNative,
    TSIntervalExplorationEfficiencyPolarsNative,
    TSIntervalNestingDepthPolarsNative,
    TSIntervalOccupancyEntropyPolarsNative,
    TSIntervalOccupancyModeDistancePolarsNative,
    TSIntervalOverlapConnectedComponentRatioPolarsNative,
    TSIntervalUnionCoveragePolarsNative,
    TSJointEnergyShiftPolarsNative,
    TSJumpBipowerPolarsNative,  # Renamed from TSJumpBipowerPolarsNative_proxy
    TSKMDiffusionGradientPolarsNative,
    TSDeviationFromMeanPolarsNative,  # Renamed from TsKm_equilibrium_distance
    TSKMQuasipotentialDepthPolarsNative,
    TSKramersMoyalDiffusionPolarsNative,
    TSKramersMoyalDriftPolarsNative,
    TSKramersMoyalLocalStabilityPolarsNative,
    TSKSShiftPolarsNative,
    TSLKurtosisPolarsNative,
    TSLSkewnessPolarsNative,
    TSLagOfPeakCorrPolarsNative,
    TSLaggedMutualInformationPolarsNative,
    TSLempelZivComplexityPolarsNative,
    TSLevelShiftScorePolarsNative,
    TSLeverageEffectPolarsNative,
    TSLineConvergencePolarsNative,
    TSLineParallelismPolarsNative,
    TSLoMackinlayVRPolarsNative,
    TSLoMackinlayZPolarsNative,
    TSLocalLyapunovExponentPolarsNative,  # QUARANTINED: research_only
    TSLowerTailCoexceedanceProbabilityPolarsNative,
    TSMarketLiquidityBetaPolarsNative,
    TSMarkovCommittorPolarsNative,  # QUARANTINED: research_only
    TSMarkovEntropyProductionPolarsNative,  # QUARANTINED: research_only
    TSMarkovMeanFirstPassageTimePolarsNative,  # QUARANTINED: research_only
    TSLag1AutocorrPolarsNative,  # Renamed from TsMarkov_persistence
)

# Candlestick patterns and features (35 operators)
from .candlestick import (
    # Candle features (13)
    CandleBodyPercentile,
    CandleBodyZScore,
    CandleCloseStrength,
    CandleGapATR,
    CandleInsideRatio,
    CandleLowerShadowZScore,
    CandleOverlapRatio,
    CandleRangeATR,
    CandleRangePercentile,
    CandleRangeZScore,
    CandleRejectionLower,
    CandleRejectionUpper,
    CandleUpperShadowZScore,
    # Candlestick patterns (22)
    CDL_DarkCloudCover,
    CDL_Doji,
    CDL_DragonflyDoji,
    CDL_Engulfing,
    CDL_EveningStar,
    CDL_GravestoneDoji,
    CDL_Hammer,
    CDL_HangingMan,
    CDL_Harami,
    CDL_HaramiCross,
    CDL_InsideBar,
    CDL_InvertedHammer,
    CDL_Marubozu,
    CDL_MorningStar,
    CDL_OutsideBar,
    CDL_Piercing,
    CDL_ShootingStar,
    CDL_SpinningTop,
    CDL_ThreeBlackCrows,
    CDL_ThreeWhiteSoldiers,
    CDL_TweezerBottom,
    CDL_TweezerTop,
)

# Chart patterns (27 operators)
from .patterns import (
    Pattern123Bear,
    Pattern123Bull,
    PatternAscendingTriangle,
    PatternBearFlag,
    PatternBearPennant,
    PatternBreakdownRetest,
    PatternBreakoutRetest,
    PatternBroadening,
    PatternBullFlag,
    PatternBullPennant,
    PatternCup,
    PatternCupHandle,
    PatternDescendingTriangle,
    PatternDoubleBottom,
    PatternDoubleTop,
    PatternFallingChannel,
    PatternFallingWedge,
    PatternHeadShoulders,
    PatternInverseHeadShoulders,
    PatternRectangle,
    PatternRisingChannel,
    PatternRisingWedge,
    PatternRoundingBottom,
    PatternRoundingTop,
    PatternSymTriangle,
    PatternTripleBottom,
    PatternTripleTop,
)

__all__ = [
    # Technical indicators final (10)
    "ElderRay",
    "FisherTransform",
    "PSAR",
    "QQE",
    "RSX",
    "SupertrendDirection",
    "TSI",
    "TSI_signal",
    "VortexMinus",
    "VortexPlus",
    # Miscellaneous operators (9)
    "AshareOnePriceLimitStreak",
    "CashFlowLifecycleStage",
    "IndustryFiscalResid",
    "IndustryRollingPCALoading",
    "QuarterFromCumulative",
    "RevisionDelta",
    "SessionEventRecoveryScore",
    "TurnoverChipAgeCostSurface",
    "TurnoverChipOverhangSurface",
    # Intraday operators (25)
    "IntradayActivityDurationCurvaturePolarsNative",
    "IntradayBarrierApproachAccelerationPolarsNative",
    "IntradayBvcImbalancePolarsNative",
    "IntradayImpactAsymmetryPolarsNative",
    "IntradayImpactBetaPolarsNative",
    "IntradayImpactDecayRatePolarsNative",
    "IntradayJumpTestStatPolarsNative",
    "IntradayMedrvPolarsNative",
    "IntradayMinrvPolarsNative",
    "IntradayQuantileCurvePcaResidualPolarsNative",
    "IntradayQuantileCurvePcaScorePolarsNative",
    "IntradayRealizedPowerVariationPolarsNative",
    "IntradayRealizedSemivarianceBalancePolarsNative",
    "IntradayReturnWassersteinShiftPolarsNative",
    "IntradayRvSignatureCurvaturePolarsNative",
    "IntradayRvSignatureSlopePolarsNative",
    "IntradaySessionShapeNoveltyPolarsNative",
    "IntradaySubsampledRvDispersionPolarsNative",
    "IntradayVolatilityConcentrationPolarsNative",
    "IntradayVolatilityEntropyPolarsNative",
    "IntradayVolatilitySignatureSlopePolarsNative",
    "IntradayVolatilityTimeCentroidPolarsNative",
    "IntradayVolumeClockPathEfficiencyPolarsNative",
    "IntradayVolumeClockRoughnessPolarsNative",
    "IntradayWassersteinPairDistancePolarsNative",
    # Intra operators (24)
    "IntraEventPrePostContrastPolarsNative",
    "IntraEventWindowReducePolarsNative",
    "IntraImpulseEventDetectorPolarsNative",
    "IntraLimitDurationPolarsNative",
    "IntraLimitFirstHitTimePolarsNative",
    "IntraLimitPreHitPressureProfilePolarsNative",
    "IntraLimitReopenCountPolarsNative",
    "IntraLiquidityResilienceCurveFitPolarsNative",
    "IntraMultiresolutionResampleReducePolarsNative",
    "IntraNeighborEventClassPolarsNative",
    "IntraPostImpulseResponsePolarsNative",
    "IntraProbeOutcomeScorePolarsNative",
    "IntraProfileEarthMoverDistancePolarsNative",
    "IntraResponseCurveFeaturesPolarsNative",
    "IntraSliceMaskPairReducePolarsNative",
    "IntraSliceMaskReducePolarsNative",
    "IntraStateDwellStatsPolarsNative",
    "IntraStateIntervalMomentPolarsNative",
    "IntraStatePairSameSlotCorrPolarsNative",
    "IntraSupplyAbsorptionScorePolarsNative",
    "IntraUteHighPolarsNative",
    "IntraUteLowPolarsNative",
    "IntraVwapPathCurvaturePctPolarsNative",
    "IntraVwapPathSlopePctPolarsNative",
    # TS advanced batch 5 (64)
    "TSDistanceCorrelationPartialProxyPolarsNative",
    "TSFeatureModeSharePolarsNative",
    "TSFeatureSubspaceRotationPolarsNative",
    "TSFIRLowpassCausalPolarsNative",
    "TSFirstPassageBiasPolarsNative",
    "TSFirstPassageConditionalTimePolarsNative",
    "TSFirstPassageHitProbabilityPolarsNative",
    "TSFisherInformationShiftPolarsNative",
    "TSForbiddenOrdinalPatternRatioPolarsNative",
    "TSFractionalDifferencePolarsNative",
    "TSFractionalDifferenceDiscardedWeightMassPolarsNative",
    "TSGeneralizedHurstExponentPolarsNative",
    "TSGeneralizedHurstSpreadQ1Q4PolarsNative",
    "TSGPDShapePWMPolarsNative",
    "TSHInfinityLevelFilterPolarsNative",
    "TSHampelFilterCausalPolarsNative",
    "TSHankelEffectiveRankPolarsNative",
    "TSHankelSingularGapPolarsNative",
    "TSHartiganDipPolarsNative",
    "TSHiguchiFractalDimensionPolarsNative",
    "TSHillTailIndexPolarsNative",
    "TSHSICPolarsNative",
    "TSHurstDFAPolarsNative",
    "TSHVGAssortativityPolarsNative",
    "TSHVGClusteringCoefficientPolarsNative",
    "TSHVGDegreeEntropyPolarsNative",
    "TSHVGForwardBackwardAsymmetryPolarsNative",
    "TSHVGMotifEntropyPolarsNative",
    "TSHysteresisAgePolarsNative",
    "TSHysteresisStatePolarsNative",
    "TSIndustryLiquidityBetaPolarsNative",
    "TSIntervalExplorationEfficiencyPolarsNative",
    "TSIntervalNestingDepthPolarsNative",
    "TSIntervalOccupancyEntropyPolarsNative",
    "TSIntervalOccupancyModeDistancePolarsNative",
    "TSIntervalOverlapConnectedComponentRatioPolarsNative",
    "TSIntervalUnionCoveragePolarsNative",
    "TSJointEnergyShiftPolarsNative",
    "TSJumpBipowerPolarsNative",  # Renamed from TSJumpBipowerPolarsNative_proxy
    "TSKMDiffusionGradientPolarsNative",
    "TSDeviationFromMeanPolarsNative",  # Renamed from TsKm_equilibrium_distance
    "TSKMQuasipotentialDepthPolarsNative",
    "TSKramersMoyalDiffusionPolarsNative",
    "TSKramersMoyalDriftPolarsNative",
    "TSKramersMoyalLocalStabilityPolarsNative",
    "TSKSShiftPolarsNative",
    "TSLKurtosisPolarsNative",
    "TSLSkewnessPolarsNative",
    "TSLagOfPeakCorrPolarsNative",
    "TSLaggedMutualInformationPolarsNative",
    "TSLempelZivComplexityPolarsNative",
    "TSLevelShiftScorePolarsNative",
    "TSLeverageEffectPolarsNative",
    "TSLineConvergencePolarsNative",
    "TSLineParallelismPolarsNative",
    "TSLoMackinlayVRPolarsNative",
    "TSLoMackinlayZPolarsNative",
    "TSLocalLyapunovExponentPolarsNative",  # QUARANTINED: research_only
    "TSLowerTailCoexceedanceProbabilityPolarsNative",
    "TSMarketLiquidityBetaPolarsNative",
    "TSMarkovCommittorPolarsNative",  # QUARANTINED: research_only
    "TSMarkovEntropyProductionPolarsNative",  # QUARANTINED: research_only
    "TSMarkovMeanFirstPassageTimePolarsNative",  # QUARANTINED: research_only
    "TSLag1AutocorrPolarsNative",  # Renamed from TsMarkov_persistence
    # Candle features (13)
    "CandleBodyPercentile",
    "CandleBodyZScore",
    "CandleCloseStrength",
    "CandleGapATR",
    "CandleInsideRatio",
    "CandleLowerShadowZScore",
    "CandleOverlapRatio",
    "CandleRangeATR",
    "CandleRangePercentile",
    "CandleRangeZScore",
    "CandleRejectionLower",
    "CandleRejectionUpper",
    "CandleUpperShadowZScore",
    # Candlestick patterns (22)
    "CDL_DarkCloudCover",
    "CDL_Doji",
    "CDL_DragonflyDoji",
    "CDL_Engulfing",
    "CDL_EveningStar",
    "CDL_GravestoneDoji",
    "CDL_Hammer",
    "CDL_HangingMan",
    "CDL_Harami",
    "CDL_HaramiCross",
    "CDL_InsideBar",
    "CDL_InvertedHammer",
    "CDL_Marubozu",
    "CDL_MorningStar",
    "CDL_OutsideBar",
    "CDL_Piercing",
    "CDL_ShootingStar",
    "CDL_SpinningTop",
    "CDL_ThreeBlackCrows",
    "CDL_ThreeWhiteSoldiers",
    "CDL_TweezerBottom",
    "CDL_TweezerTop",
    # Chart patterns (27)
    "Pattern123Bear",
    "Pattern123Bull",
    "PatternAscendingTriangle",
    "PatternBearFlag",
    "PatternBearPennant",
    "PatternBreakdownRetest",
    "PatternBreakoutRetest",
    "PatternBroadening",
    "PatternBullFlag",
    "PatternBullPennant",
    "PatternCup",
    "PatternCupHandle",
    "PatternDescendingTriangle",
    "PatternDoubleBottom",
    "PatternDoubleTop",
    "PatternFallingChannel",
    "PatternFallingWedge",
    "PatternHeadShoulders",
    "PatternInverseHeadShoulders",
    "PatternRectangle",
    "PatternRisingChannel",
    "PatternRisingWedge",
    "PatternRoundingBottom",
    "PatternRoundingTop",
    "PatternSymTriangle",
    "PatternTripleBottom",
    "PatternTripleTop",
]
