# -*- coding: utf-8 -*-
"""
Polars Native Operators

真正的 Polars native 实现，避免 pandas fallback，提升性能。
"""

# Candlestick patterns and features (35 operators)
from .candlestick import (
    # Candle features (13)
    CandleBodyPercentile,
    CandleBodyZscore,
    CandleCloseStrength,
    CandleGapATR,
    CandleInsideRatio,
    CandleLowerShadowZscore,
    CandleOverlapRatio,
    CandleRangeATR,
    CandleRangePercentile,
    CandleRangeZscore,
    CandleRejectionLower,
    CandleRejectionUpper,
    CandleUpperShadowZscore,
    # Candlestick patterns (22)
    CdlDarkCloudCover,
    CdlDoji,
    CdlDragonflyDoji,
    CdlEngulfing,
    CdlEveningStar,
    CdlGravestoneDoji,
    CdlHammer,
    CdlHangingMan,
    CdlHarami,
    CdlHaramiCross,
    CdlInsideBar,
    CdlInvertedHammer,
    CdlMarubozu,
    CdlMorningStar,
    CdlOutsideBar,
    CdlPiercing,
    CdlShootingStar,
    CdlSpinningTop,
    CdlThreeBlackCrows,
    CdlThreeWhiteSoldiers,
    CdlTweezerBottom,
    CdlTweezerTop,
)

# Chart patterns (27 operators)
from .patterns import (
    Pattern123Bear,
    Pattern123Bull,
    PatternAscendingTriangle,
    PatternBearFlag,
    PatternBearPennant,
    PatternBreakdownRetest,
    PatternBreakoutRetest,
    PatternBroadening,
    PatternBullFlag,
    PatternBullPennant,
    PatternCup,
    PatternCupHandle,
    PatternDescendingTriangle,
    PatternDoubleBottom,
    PatternDoubleTop,
    PatternFallingChannel,
    PatternFallingWedge,
    PatternHeadShoulders,
    PatternInverseHeadShoulders,
    PatternRectangle,
    PatternRisingChannel,
    PatternRisingWedge,
    PatternRoundingBottom,
    PatternRoundingTop,
    PatternSymTriangle,
    PatternTripleBottom,
    PatternTripleTop,
)

__all__ = [
    # Candle features
    "CandleBodyPercentile",
    "CandleBodyZscore",
    "CandleCloseStrength",
    "CandleGapATR",
    "CandleInsideRatio",
    "CandleLowerShadowZscore",
    "CandleOverlapRatio",
    "CandleRangeATR",
    "CandleRangePercentile",
    "CandleRangeZscore",
    "CandleRejectionLower",
    "CandleRejectionUpper",
    "CandleUpperShadowZscore",
    # Candlestick patterns
    "CdlDarkCloudCover",
    "CdlDoji",
    "CdlDragonflyDoji",
    "CdlEngulfing",
    "CdlEveningStar",
    "CdlGravestoneDoji",
    "CdlHammer",
    "CdlHangingMan",
    "CdlHarami",
    "CdlHaramiCross",
    "CdlInsideBar",
    "CdlInvertedHammer",
    "CdlMarubozu",
    "CdlMorningStar",
    "CdlOutsideBar",
    "CdlPiercing",
    "CdlShootingStar",
    "CdlSpinningTop",
    "CdlThreeBlackCrows",
    "CdlThreeWhiteSoldiers",
    "CdlTweezerBottom",
    "CdlTweezerTop",
    # Chart patterns
    "Pattern123Bear",
    "Pattern123Bull",
    "PatternAscendingTriangle",
    "PatternBearFlag",
    "PatternBearPennant",
    "PatternBreakdownRetest",
    "PatternBreakoutRetest",
    "PatternBroadening",
    "PatternBullFlag",
    "PatternBullPennant",
    "PatternCup",
    "PatternCupHandle",
    "PatternDescendingTriangle",
    "PatternDoubleBottom",
    "PatternDoubleTop",
    "PatternFallingChannel",
    "PatternFallingWedge",
    "PatternHeadShoulders",
    "PatternInverseHeadShoulders",
    "PatternRectangle",
    "PatternRisingChannel",
    "PatternRisingWedge",
    "PatternRoundingBottom",
    "PatternRoundingTop",
    "PatternSymTriangle",
    "PatternTripleBottom",
    "PatternTripleTop",
]
