# -*- coding: utf-8 -*-
"""Round-14 P0 regression tests for the rough-volatility scaling operators.

Canonicals under test:
* ``ts_vol_pvariation_roughness`` — Hurst ``H`` from the log-log slope of the
  mean-normalized structure function ``S_p(delta) = mean |inc|^p`` over the
  finite endpoint pairs.
* ``ts_vol_scaling_break`` — ``H(1,2) - H(8,16)`` on the same mean-normalized
  structure function.

Covers the two P0 correctness fixes in ``cleaned_operators/rough_vol.py``:
* BUG 1 — the H estimator now uses the *mean* structure function (never
  ``sum``), so the scale-count pollution ``log N_delta`` (delta=1 has N-1 valid
  increments, delta=8 has N-8, delta=16 has N-16) can no longer bias the slope.
* BUG 2 — per-scale data-quality gates (``min_pairs`` finite endpoint pairs,
  ``min_pair_fraction`` coverage, and a coverage-imbalance bound) turn a window
  that cannot estimate all required scales on comparable data into NaN instead
  of a missing-pattern-manufactured estimate.

All tests drive the operators through the registry (pandas_numpy backend) on
exact fractional-Brownian synthetic paths generated by Cholesky factorisation of
the fBm covariance, so "systematic bias in the wrong direction" is detectable.
"""
from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from factor_engine.cleaned_operators import OperatorRegistry, load_all

# NaN at positions 3 and 8 of every 11-slot block: [x x x NaN x x x x NaN x x].
_MISSING_PATTERN = np.array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0], dtype=bool)


@pytest.fixture(scope="module", autouse=True)
def _registry_loaded():
    load_all()
    yield


# ---------------------------------------------------------------------------
# exact synthetic process helpers
# ---------------------------------------------------------------------------
def fbm_path(n: int, h: float, rng: np.random.Generator) -> np.ndarray:
    """Fractional Brownian motion sampled at t=1..n (exact Cholesky).

    Builds the covariance of the fBm increments (fractional Gaussian noise)
    ``gamma(k) = 0.5*(|k+1|^{2H} + |k-1|^{2H} - 2*|k|^{2H})``, takes its
    Cholesky factor, and cumsums the generated increments — the exact
    covariance of fBm, not an approximation.  ``rng`` is a
    ``numpy.random.Generator`` so every test is reproducible.
    """
    h = float(h)
    idx = np.arange(0, n, dtype=float)

    def gamma(k: float) -> float:
        return 0.5 * (np.abs(k + 1) ** (2 * h) + np.abs(k - 1) ** (2 * h) - 2 * np.abs(k) ** (2 * h))

    cov = np.array([[gamma(abs(i - j)) for j in idx] for i in idx], dtype=float)
    chol = np.linalg.cholesky(cov + np.eye(n) * 1e-10)
    return np.cumsum(chol @ rng.standard_normal(n))


def brownian(n: int, rng: np.random.Generator) -> np.ndarray:
    """Standard Brownian motion (H=0.5, unit-variance increments)."""
    return np.cumsum(rng.standard_normal(n))


def _panel(series) -> pd.DataFrame:
    return pd.DataFrame({"A": np.asarray(series, dtype=float)})


def _op(canonical: str):
    op = OperatorRegistry.get(canonical, "pandas_numpy")
    assert op is not None, canonical
    return op


def est_h(series, *, window: int, p: float = 2.0, scales=(1, 2, 4), **kwargs) -> float:
    """ts_vol_pvariation_roughness on a 1-column panel; return the last value."""
    out = _op("ts_vol_pvariation_roughness").calculate(
        _panel(series), window=window, p=p, scales=scales, **kwargs
    )
    return float(out.iloc[-1, 0])


# ---------------------------------------------------------------------------
# BUG 1 / happy-path recovery on exact synthetic processes
# ---------------------------------------------------------------------------
def test_brownian_motion_h_estimate_around_half():
    """Brownian (H=0.5) → estimated H ≈ 0.5 within a loose tolerance."""
    rng = np.random.default_rng(5)
    ests = [est_h(brownian(252, rng), window=252) for _ in range(3)]
    mean_est = float(np.mean(ests))
    assert abs(mean_est - 0.5) < 0.15, f"Brownian H estimate {mean_est:.3f} too far from 0.5"


def test_fbm_h_monotone_ordering_and_recovery():
    """fBm H=0.2/0.5/0.8 → monotone ordering + approximate recovery."""
    rng = np.random.default_rng(0)
    ests = {}
    for h_true in (0.2, 0.5, 0.8):
        trials = [est_h(fbm_path(252, h_true, rng), window=252) for _ in range(3)]
        ests[h_true] = float(np.mean(trials))
    assert ests[0.2] < ests[0.5] < ests[0.8], (
        f"estimated H not monotone in true H: {ests}"
    )
    for h_true, h_est in ests.items():
        assert abs(h_est - h_true) < 0.2, (
            f"H={h_true} recovered as {h_est:.3f} — systematic bias in the "
            "wrong direction"
        )


def test_estimator_no_mechanical_drift_with_window_size():
    """N=60/120/252 → similar H for the same process (no N/max_scale drift)."""
    for h_true in (0.2, 0.5, 0.8):
        means: dict[int, float] = {}
        for n in (60, 120, 252):
            rng = np.random.default_rng(42)
            trials = [est_h(fbm_path(n, h_true, rng), window=n) for _ in range(5)]
            means[n] = float(np.mean(trials))
        spread = max(means.values()) - min(means.values())
        assert spread < 0.15, (
            f"H={h_true} drifts with window/max_scale: {means} (spread {spread:.3f})"
        )
        for n, m in means.items():
            assert abs(m - h_true) < 0.2, (
                f"H={h_true} N={n} recovered as {m:.3f} — systematic bias"
            )


def test_insufficient_history_still_nan():
    """Too little finite data → NaN output, never a number."""
    # Window shorter than the finite-observation warmup -> all NaN.
    short = brownian(4, np.random.default_rng(0))
    out = _op("ts_vol_pvariation_roughness").calculate(_panel(short), window=4)
    assert np.isnan(out.to_numpy()).all()
    out2 = _op("ts_vol_scaling_break").calculate(_panel(short), window=4)
    assert np.isnan(out2.to_numpy()).all()

    # Trailing window with 5 finite values scattered over 10 rows: every scale
    # has < min_pairs finite pairs -> the last output is NaN, not a number.
    x = np.full(10, np.nan)
    x[[0, 1, 2, 3, 9]] = [1.0, 2.0, 3.0, 4.0, 5.0]
    out3 = _op("ts_vol_pvariation_roughness").calculate(_panel(x), window=10)
    assert np.isnan(out3.iloc[-1, 0])


def test_all_nan_input_yields_nan():
    """All-NaN input → NaN output (no Inf, no crash)."""
    x = np.full(120, np.nan)
    for canonical in ("ts_vol_pvariation_roughness", "ts_vol_scaling_break"):
        out = _op(canonical).calculate(_panel(x), window=120)
        assert np.isnan(out.to_numpy()).all(), canonical


# ---------------------------------------------------------------------------
# BUG 2 — missing-data gates
# ---------------------------------------------------------------------------
def test_missing_pattern_does_not_jump_scaling():
    """A fixed missing pattern must not manufacture fake scaling.

    Compare the H estimate on a series with a fixed missing pattern to the
    fully-observed series of the same process and report the delta: the
    estimate must not jump purely because of the pattern.
    """
    rng = np.random.default_rng(42)
    for h_true in (0.2, 0.5, 0.8):
        deltas = []
        for _ in range(3):
            path = fbm_path(252, h_true, rng)
            h_full = est_h(path, window=252)
            masked = path.copy()
            masked[np.tile(_MISSING_PATTERN, 252 // 11 + 1)[:252]] = np.nan
            h_masked = est_h(masked, window=252)
            assert np.isfinite(h_masked), (
                f"H={h_true}: coverage gate made the masked series NaN — the "
                "pattern is too destructive for this window, not a 'jump'"
            )
            deltas.append(abs(h_masked - h_full))
        max_delta = float(np.max(deltas))
        print(f"[missing-pattern] H={h_true}: deltas={[round(d, 4) for d in deltas]} "
              f"max_delta={max_delta:.4f}")
        assert max_delta < 0.1, (
            f"H={h_true}: missing pattern moves H by {max_delta:.3f} — "
            "fake scaling from the pattern"
        )


def test_coverage_gate_sparse_pairs_outputs_nan():
    """A window with only 2-3 finite pairs must output NaN, not a number.

    Five finite values placed at every other position pass the ``_MIN_FINITE=5``
    warmup (5 finite values) but give only 0 lag-1, 4 lag-2 and 3 lag-4 finite
    pairs — every scale fails the ``min_pairs`` gate → NaN.
    """
    x = np.full(40, np.nan)
    x[30] = 1.0
    x[32] = 2.0
    x[34] = 3.0
    x[36] = 4.0
    x[38] = 5.0
    out = _op("ts_vol_pvariation_roughness").calculate(_panel(x), window=40)
    assert np.isnan(out.iloc[-1, 0]), "sparse-pair window must emit NaN"
    assert np.isnan(out.to_numpy()).all()


def test_coverage_fraction_gate_outputs_nan():
    """Coverage below min_pair_fraction on a long scale → NaN.

    Finite values packed in the first half of the window give the long scale a
    low finite-pair fraction even though plenty of short-lag pairs exist.
    """
    x = np.full(24, np.nan)
    x[:12] = np.arange(12, dtype=float)
    # delta=8 pairs: (0,8),(1,9),(2,10),(3,11) → 4 of 16 possible = 0.25 < 0.5.
    out = _op("ts_vol_pvariation_roughness").calculate(
        _panel(x), window=24, scales=(1, 2, 4, 8)
    )
    assert np.isnan(out.iloc[-1, 0]), (
        "low-coverage long scale must emit NaN, not a biased estimate"
    )


def test_imbalance_gate_clustered_gap_outputs_nan():
    """Severe per-scale coverage imbalance (max/min > bound) → NaN.

    Two finite clusters far apart make the long scales see almost none of the
    data while the short scales see a normal share: with a loosened
    ``min_pair_fraction`` every scale passes its own gate but the coverage
    imbalance (0.228/0.056 ≈ 4.1) exceeds the bound → NaN.  The same window with
    a permissive imbalance bound yields a finite (deterministic) value.
    """
    x = np.full(80, np.nan)
    x[0:10] = np.arange(10, dtype=float)
    x[70:80] = np.arange(10, 20, dtype=float)
    out = _op("ts_vol_pvariation_roughness").calculate(
        _panel(x), window=80, scales=(1, 2, 4, 8), min_pairs=4, min_pair_fraction=0.05
    )
    assert np.isnan(out.iloc[-1, 0]), "imbalanced per-scale coverage must emit NaN"

    # Control: a fully-observed window of the same length is balanced → finite.
    y = np.arange(80, dtype=float)
    out_ok = _op("ts_vol_pvariation_roughness").calculate(
        _panel(y), window=80, scales=(1, 2, 4, 8), min_pairs=4, min_pair_fraction=0.05
    )
    assert np.isfinite(out_ok.iloc[-1, 0]), "balanced window must stay finite"


def test_scaling_break_happy_path_and_gates():
    """ts_vol_scaling_break runs on real data and gates on sparse data."""
    rng = np.random.default_rng(0)
    df = _panel(brownian(200, rng))
    out = _op("ts_vol_scaling_break").calculate(df, window=120)
    assert np.isfinite(out.iloc[-1, 0]), "scaling_break happy path must be finite"
    assert np.isfinite(out.to_numpy()).mean() > 0.5

    # lag-16 has no finite pairs in the clustered-gap pattern → NaN.
    x = np.full(80, np.nan)
    x[0:10] = np.arange(10, dtype=float)
    x[70:80] = np.arange(10, 20, dtype=float)
    out2 = _op("ts_vol_scaling_break").calculate(_panel(x), window=80)
    assert np.isnan(out2.iloc[-1, 0]), "scaling_break with missing lag-16 must be NaN"


def test_new_parameter_contract():
    """min_pairs / min_pair_fraction are real, validated parameters."""
    rng = np.random.default_rng(0)
    series = brownian(200, rng)
    out = _op("ts_vol_pvariation_roughness").calculate(
        _panel(series), window=120, min_pairs=10, min_pair_fraction=0.8
    )
    assert isinstance(out, pd.DataFrame)

    with pytest.raises(Exception):
        _op("ts_vol_pvariation_roughness").calculate(
            _panel(series), window=120, min_pairs=2.5
        )
    with pytest.raises(Exception):
        _op("ts_vol_pvariation_roughness").calculate(
            _panel(series), window=120, min_pair_fraction=1.5
        )
