"""Custom build backend (PEP 517) for the quant-projects umbrella wheel.

This backend delegates entirely to setuptools.  It NO LONGER performs
post-wheel surgery (unpack -> delete tests -> rezip).  That earlier approach
left ``*.dist-info/RECORD`` stale (supply-chain / integrity risk).  Test and
build-artifact exclusion is now done at the setuptools discovery level in
``pyproject.toml`` (``[tool.setuptools]`` ``exclude`` / ``exclude-package-data``),
so ``RECORD`` is regenerated by setuptools/wheel and always matches the payload.
"""
from setuptools import build_meta as _orig

# Re-export the standard setuptools backend untouched.
build_wheel = _orig.build_wheel
prepare_metadata_for_build_wheel = _orig.prepare_metadata_for_build_wheel
build_sdist = _orig.build_sdist
get_requires_for_build_wheel = _orig.get_requires_for_build_wheel
get_requires_for_build_sdist = _orig.get_requires_for_build_sdist

# Editable install support (PEP 660).
try:
    prepare_metadata_for_build_editable = _orig.prepare_metadata_for_build_editable
    get_requires_for_build_editable = _orig.get_requires_for_build_editable
    build_editable = _orig.build_editable
except AttributeError:  # pragma: no cover - older setuptools fallback
    pass
