# -*- coding: utf-8 -*-
"""算子文档批量语义条目（由 operator_doc_semantics 合并）。"""
from __future__ import annotations

from cleaned_operators.docs.operator_doc_semantics import OpDoc


def _d(meaning: str, compute: str, latex: str) -> OpDoc:
    return OpDoc(meaning, compute, latex)


BATCH_DOCS: dict[str, OpDoc] = {
    # ===== 统计 / 回归 =====
    "Sum": _d("滚动求和。", "窗口内对 X 求和。", r"S_t = \sum_{k=0}^{d-1} X_{t-k}"),
    "sum_agg": _d("列方向求和。", "对 panel 每列（标的）全时间轴求和。", r"\sum_t X_{i,t}"),
    "avg": _d("列方向算术平均。", "对每列全样本求均值。", r"\bar{X}_i = \frac{1}{T}\sum_t X_{i,t}"),
    "mean_agg": _d("列方向算术平均。", "同 avg，对每列求均值。", r"\bar{X}_i = \frac{1}{T}\sum_t X_{i,t}"),
    "count": _d("非空值计数。", "统计有效（非 NaN）观测个数。", r"n = \#\{t: X_{i,t}\ \text{有效}\}"),
    "Median": _d("中位数。", "窗口或截面上的 50% 分位点。", r"\mathrm{median}(X)"),
    "Mode": _d("众数。", "出现频率最高的取值。", r"\mathrm{mode}(X)"),
    "Mad": _d("平均绝对离差 MAD。", "mean(|X - median(X)|)。", r"\mathrm{MAD} = \frac{1}{n}\sum|X_i - \mathrm{med}|"),
    "Kurt": _d("峰度。", "四阶中心矩减 3。", r"\kappa = E\left[\left(\frac{X-\mu}{\sigma}\right)^4\right] - 3"),
    "Skew": _d("偏度。", "三阶标准化矩。", r"\gamma = E\left[\left(\frac{X-\mu}{\sigma}\right)^3\right]"),
    "Var": _d("样本方差。", "ddof=1 的方差。", r"s^2 = \frac{1}{n-1}\sum(X_i-\bar{X})^2"),
    "varp": _d("总体方差。", "ddof=0 的方差。", r"\sigma^2 = \frac{1}{n}\sum(X_i-\bar{X})^2"),
    "std_agg": _d("样本标准差。", "Var 的平方根（样本）。", r"s = \sqrt{\mathrm{Var}(X)}"),
    "stdp": _d("总体标准差。", "varp 的平方根。", r"\sigma = \sqrt{\mathrm{varp}(X)}"),
    "sem": _d("均值标准误。", "std / sqrt(n)。", r"\mathrm{SE} = \frac{s}{\sqrt{n}}"),
    "Percentile": _d("分位数（0–1）。", "返回指定分位点 q∈[0,1]。", r"Q_q(X)"),
    "product": _d("连乘积。", "窗口或序列元素相乘。", r"\prod_i X_i"),
    "sample": _d("随机抽样。", "从序列中随机抽取样本（用于模拟/扰动）。", r"X' \sim \mathrm{Sample}(X)"),
    "shuffle": _d("随机打乱。", "对序列随机重排（破坏时序，慎用）。", r"X' = \pi(X),\ \pi\ \text{随机}"),
    "Beta": _d("回归 Beta 系数。", "OLS：Y ~ X 的斜率 β = Cov(X,Y)/Var(X)。", r"\beta = \frac{\mathrm{Cov}(X,Y)}{\mathrm{Var}(X)}"),
    "beta": _d("回归 Beta 系数。", "同 Beta，小写别名。", r"\beta = \frac{\mathrm{Cov}(X,Y)}{\mathrm{Var}(X)}"),
    "Slope": _d("时间序列斜率。", "对时间索引 t 做线性回归的斜率。", r"X_t \approx a + b t,\quad b=\mathrm{slope}"),
    "slope": _d("回归斜率。", "Y ~ X 的 OLS 斜率。", r"\beta = \frac{\mathrm{Cov}(X,Y)}{\mathrm{Var}(X)}"),
    "Intercept": _d("OLS 截距。", "Y = α + βX 中的 α。", r"\alpha = \bar{Y} - \beta\bar{X}"),
    "intercept": _d("OLS 截距。", "同 Intercept。", r"\alpha = \bar{Y} - \beta\bar{X}"),
    "Corr": _d("Pearson 相关系数。", "Cov(X,Y)/(σ_X σ_Y)。", r"\rho = \frac{\mathrm{Cov}(X,Y)}{\sigma_X\sigma_Y}"),
    "Cov": _d("协方差。", "E[(X-μ_X)(Y-μ_Y)]。", r"\mathrm{Cov}(X,Y) = E[(X-\mu_X)(Y-\mu_Y)]"),
    "Covariance": _d("协方差。", "同 Cov。", r"\mathrm{Cov}(X,Y)"),
    "R2": _d("决定系数 R²。", "回归解释度 1 - SS_res/SS_tot。", r"R^2 = 1 - \frac{\sum(y-\hat{y})^2}{\sum(y-\bar{y})^2}"),
    "r_squared": _d("决定系数 R²。", "同 R2。", r"R^2 = 1 - \frac{SS_{\mathrm{res}}}{SS_{\mathrm{tot}}}"),
    "Residual": _d("回归残差均值。", "窗口内 OLS 残差的平均。", r"\bar{\varepsilon} = \frac{1}{n}\sum(y_i - \hat{y}_i)"),
    "residual": _d("回归残差均值。", "同 Residual。", r"\bar{\varepsilon}"),
    "regress": _d("通用回归接口。", "Y ~ X 回归，按参数返回 slope/intercept/R²/residual。", r"Y = \alpha + \beta X + \varepsilon"),
    "ridge": _d("Ridge 回归（L2）。", "min ||Y-Xβ||² + λ||β||²。", r"\hat\beta = (X'X+\lambda I)^{-1}X'Y"),
    "lasso": _d("Lasso 回归（L1）。", "min ||Y-Xβ||² + λ||β||₁。", r"\hat\beta = \arg\min_\beta \|Y-X\beta\|^2 + \lambda\|\beta\|_1"),
    "ACF": _d("自相关系数 ACF。", "lag-k 自相关 ρ_k = Cov(X_t,X_{t-k})/Var(X)。", r"\rho_k = \frac{\mathrm{Cov}(X_t,X_{t-k})}{\mathrm{Var}(X)}"),
    "pacf": _d("偏自相关系数 PACF。", "控制中间滞后后的条件自相关。", r"\phi_{kk} = \mathrm{corr}(X_t, X_{t-k}\mid X_{t-1},\ldots,X_{t-k+1})"),
    "PACF": _d("偏自相关系数 PACF。", "控制中间滞后后的条件自相关。", r"\phi_{kk} = \mathrm{corr}(X_t, X_{t-k}\mid X_{t-1},\ldots,X_{t-k+1})"),
    "autocorr": _d("自相关系数。", "同 ACF。", r"\rho_k = \mathrm{corr}(X_t, X_{t-k})"),
    "at_imax": _d("最大值索引。", "返回序列最大值所在位置索引。", r"i^* = \arg\max_i X_i"),
    "at_imin": _d("最小值索引。", "返回序列最小值所在位置索引。", r"i^* = \arg\min_i X_i"),
    "first": _d("列首值。", "返回每列第一个观测。", r"X_{i,1}"),
    "last": _d("列末值。", "返回每列最后一个观测。", r"X_{i,T}"),
    "first_not_null": _d("首个非空值。", "返回每列第一个有效观测。", r"X_{i,t_0},\ t_0=\min\{t: X_{i,t}\ \text{有效}\}"),
    "last_not_null": _d("最后非空值。", "返回每列最后一个有效观测。", r"X_{i,t_1},\ t_1=\max\{t: X_{i,t}\ \text{有效}\}"),
    "wavg": _d("加权平均。", "Σ(w_i X_i)/Σw_i。", r"\bar{X}_w = \frac{\sum w_i X_i}{\sum w_i}"),
    "wsum": _d("加权求和。", "Σ(w_i X_i)。", r"S_w = \sum w_i X_i"),
    "weighted_mean": _d("加权平均数。", "同 wavg。", r"\bar{X}_w = \frac{\sum w_i X_i}{\sum w_i}"),
    "quantile_normal": _d("正态分位数函数。", "Φ^{-1}(p)，标准正态逆 CDF。", r"Q(p) = \Phi^{-1}(p)"),
    "quantile_t": _d("t 分布分位数。", "Student-t 逆 CDF。", r"Q_t(p;\,\nu)"),
    "cdf_normal": _d("正态 CDF。", "Φ(x)。", r"\Phi(x) = P(Z \le x)"),
    "cdf_t": _d("t 分布 CDF。", "Student-t 累积分布。", r"F_t/select_t(x;\,\nu)"),
    "cdf_chi2": _d("卡方 CDF。", "χ² 累积分布。", r"F_{\chi^2}(x;\,k)"),
    "cdf_f": _d("F 分布 CDF。", "F 统计量累积分布。", r"F_F(x;\,d_1,d_2)"),
    "pdf_normal": _d("正态 PDF。", "标准正态密度。", r"\phi(x) = \frac{1}{\sqrt{2\pi}}e^{-x^2/2}"),
    "pdf_t": _d("t 分布 PDF。", "Student-t 密度。", r"f_t(x;\,\nu)"),
    "pdf_chi2": _d("卡方 PDF。", "χ² 密度。", r"f_{\chi^2}(x;\,k)"),
    "pdf_f": _d("F 分布 PDF。", "F 密度。", r"f_F(x;\,d_1,d_2)"),
    "rand_normal": _d("正态随机数。", "N(μ, σ²) 抽样。", r"X \sim \mathcal{N}(\mu,\sigma^2)"),
    "rand_uniform": _d("均匀随机数。", "U(a,b) 抽样。", r"X \sim \mathrm{Uniform}(a,b)"),
    "rand_exp": _d("指数随机数。", "Exp(λ) 抽样。", r"X \sim \mathrm{Exp}(\lambda)"),
    "rand_lognormal": _d("对数正态随机数。", "LogNormal 抽样。", r"X \sim \mathrm{LogNormal}(\mu,\sigma)"),
    "rand_poisson": _d("泊松随机数。", "Poisson(λ) 抽样。", r"X \sim \mathrm{Poisson}(\lambda)"),
    "granger_causality": _d("Granger 因果检验。", "检验 X 是否有助于预测 Y（滞后回归 F 检验）。", r"Y_t = \sum\alpha_i Y_{t-i} + \sum\beta_i X_{t-i} + \varepsilon_t"),
    # ===== 元素级 / 数学 =====
    "geometric_mean": _d("几何平均。", "(∏X_i)^{1/n}。", r"\bar{X}_g = \left(\prod_i X_i\right)^{1/n}"),
    "harmonic_mean": _d("调和平均。", "n / Σ(1/X_i)。", r"\bar{X}_h = \frac{n}{\sum_i 1/X_i}"),
    "standardize": _d("Z-Score 标准化。", "(X - μ)/σ。", r"Z = \frac{X - \mu}{\sigma}"),
    "running_mean": _d("滚动均值。", "固定窗口算术平均。", r"\bar{X}_t = \frac{1}{d}\sum_{k=0}^{d-1} X_{t-k}"),
    "running_std": _d("滚动标准差。", "固定窗口样本标准差。", r"\sigma_t = \mathrm{std}(X_{t-d+1:t})"),
    "running_sum": _d("滚动求和。", "固定窗口求和。", r"S_t = \sum_{k=0}^{d-1} X_{t-k}"),
    "lerp": _d("线性插值。", "a + f(b-a)。", r"L = a + f(b-a),\ f\in[0,1]"),
    "interpolate": _d("上采样插值。", "按 factor 倍率插值填充。", r"X' = \mathrm{interp}(X,\ \mathrm{factor})"),
    "decimate": _d("降采样。", "按因子抽取子序列。", r"X'_k = X_{k\cdot f}"),
    "truncate": _d("截断小数位。", "保留 k 位小数（截断而非四舍五入）。", r"\mathrm{trunc}(X,\ k)"),
    "reverse": _d("序列反转。", "时间轴倒序。", r"X'_t = X_{T-t+1}"),
    "identity": _d("恒等映射。", "返回输入不变。", r"Y = X"),
    "constant": _d("常量。", "返回指定常数。", r"Y = c"),
    "signed_log": _d("保号对数。", "sgn(x)·ln|x|。", r"\mathrm{sgn}(x)\ln|x|"),
    "saturate": _d("饱和到 [0,1]。", "clip(x, 0, 1)。", r"\min(\max(x,0),1)"),
    "unitize": _d("归一化到 [-1,1]。", "2·rank - 1 或等价缩放。", r"\tilde{X} = 2R - 1"),
    "norm": _d("L2 范数。", "||X||₂。", r"\|X\|_2 = \sqrt{\sum X_i^2}"),
    "norm_l1": _d("L1 范数。", "Σ|X_i|。", r"\|X\|_1 = \sum |X_i|"),
    "norm_linf": _d("L∞ 范数。", "max|X_i|。", r"\|X\|_\infty = \max |X_i|"),
    "atan2": _d("双参数反正切。", "atan2(y,x)，象限正确。", r"\theta = \mathrm{atan2}(y,x)"),
    "cot": _d("余切。", "1/tan(x)。", r"\cot x = 1/\tan x"),
    "csc": _d("余割。", "1/sin(x)。", r"\csc x = 1/\sin x"),
    "sec": _d("正割。", "1/cos(x)。", r"\sec x = 1/\cos x"),
    "arg": _d("复数辐角（弧度）。", "angle(z)。", r"\arg(z)"),
    "phase": _d("复数相位（角度）。", "arg(z) 转为度数或弧度。", r"\phi = \arg(z)"),
    "conj": _d("复数共轭。", "z*。", r"\bar{z}"),
    "polar": _d("极坐标转复数。", "r·e^{iθ}。", r"z = r e^{i\theta}"),
    "complex": _d("构造复数。", "real + i·imag。", r"z = a + ib"),
    "unwrap": _d("相位展开。", "消除 2π 跳变。", r"\phi'_t = \phi_t + 2\pi k"),
    "convolve": _d("卷积。", "离散卷积 (f*g)。", r"(f*g)[n] = \sum_k f[k]g[n-k]"),
    "correlate": _d("互相关。", "序列相关运算。", r"(f\star g)[n] = \sum_k f[k]g[n+k]"),
    "fft": _d("快速傅里叶变换 FFT。", "时域→频域。", r"X_k = \sum_n x_n e^{-2\pi i kn/N}"),
    "ifft": _d("逆 FFT。", "频域→时域。", r"x_n = \frac{1}{N}\sum_k X_k e^{2\pi i kn/N}"),
    "dft": _d("离散傅里叶变换。", "同 FFT 定义。", r"X_k = \sum_{n=0}^{N-1} x_n e^{-2\pi i kn/N}"),
    "idft": _d("逆离散傅里叶变换。", "DFT 逆变换。", r"x_n = \frac{1}{N}\sum_{k=0}^{N-1} X_k e^{2\pi i kn/N}"),
    "filter_lowpass": _d("低通滤波。", "保留低频、衰减高频。", r"Y = H_{\mathrm{LP}}(f) \cdot X(f)"),
    "filter_highpass": _d("高通滤波。", "保留高频。", r"Y = H_{\mathrm{HP}}(f) \cdot X(f)"),
    "filter_bandpass": _d("带通滤波。", "保留指定频带。", r"Y = H_{\mathrm{BP}}(f) \cdot X(f)"),
    "filter_notch": _d("陷波滤波。", "抑制特定频率。", r"Y = H_{\mathrm{notch}}(f) \cdot X(f)"),
    "wavelet": _d("小波变换。", "时频局部化分解。", r"W(a,b) = \int X(t)\psi^*_{a,b}(t)\,dt"),
    "wavelet_denoise": _d("小波去噪。", "小波阈值去噪后重构。", r"\hat{X} = \mathrm{IDWT}(\mathrm{thresh}(\mathrm{WT}(X)))"),
    "mat_add": _d("矩阵加法。", "逐元素 A + B。", r"C = A + B"),
    "mat_subtract": _d("矩阵减法。", "A - B。", r"C = A - B"),
    "mat_multiply": _d("矩阵乘法。", "A @ B。", r"C = A B"),
    "mat_transpose": _d("矩阵转置。", "A^T。", r"B = A^\top"),
    "mat_inverse": _d("矩阵求逆。", "A^{-1}。", r"B = A^{-1}"),
    "mat_determinant": _d("行列式。", "det(A)。", r"\det(A)"),
    "mat_rank": _d("矩阵秩。", "rank(A)。", r"\mathrm{rank}(A)"),
    "eig": _d("特征值分解。", "A = VΛV^{-1}。", r"A v = \lambda v"),
    "svd": _d("奇异值分解 SVD。", "A = UΣV^T。", r"A = U\Sigma V^\top"),
    "lu_decompose": _d("LU 分解。", "A = LU。", r"A = LU"),
    "qr_decompose": _d("QR 分解。", "A = QR。", r"A = QR"),
    "pca": _d("主成分分析 PCA。", "协方差矩阵特征向量投影。", r"Y = X W,\ W=\mathrm{eig}(\mathrm{Cov}(X))"),
    "blom_transform": _d("Blom 秩正态变换。", "Φ^{-1}((r-3/8)/(n+1/4))。", r"Z_i = \Phi^{-1}\!\left(\frac{r_i - 3/8}{n + 1/4}\right)"),
    "tukey_transform": _d("Tukey 秩变换。", "Φ^{-1}((r-1/3)/(n+1/3))。", r"Z_i = \Phi^{-1}\!\left(\frac{r_i - 1/3}{n + 1/3}\right)"),
    "van_der_waerden_transform": _d("Van der Waerden 变换。", "Φ^{-1}(r/(n+1))。", r"Z_i = \Phi^{-1}\!\left(\frac{r_i}{n+1}\right)"),
    "rank_transform": _d("秩变换。", "将值映射为秩。", r"R_i = \mathrm{rank}(X_i)"),
    "rankavg_transform": _d("平均秩变换。", "处理 ties 的平均秩。", r"R_i = \mathrm{rank}_{\mathrm{avg}}(X_i)"),
    # ===== 时序 =====
    "ema": _d("指数移动平均 EMA。", "α=2/(d+1)，EMA_t = αX_t + (1-α)EMA_{t-1}。", r"\mathrm{EMA}_t = \alpha X_t + (1-\alpha)\mathrm{EMA}_{t-1}"),
    "ewm": _d("指数加权移动。", "EWM 通用接口（span/decay 参数）。", r"\tilde{X}_t = \sum w_k X_{t-k},\ w_k \propto e^{-\lambda k}"),
    "ts_decay_exp_window": _d("指数衰减滚动窗口。", "窗口内指数权重加权。", r"\sum_{k=0}^{d-1} e^{-\lambda k} X_{t-k}"),
    "ts_sum_decay": _d("衰减求和。", "带衰减因子的滚动求和。", r"S_t = \sum_{k=0}^{d-1} \lambda^k X_{t-k}"),
    "aggr_top_n": _d("Top-N 自定义聚合。", "按 sort_col 排序取 top 后做 sum/mean/max 等。", r"Y = \mathrm{aggr}(\mathrm{top}_N(X,\ \mathrm{sort}))"),
    "cum_top_n_sum": _d("累积 Top-N 求和。", "从起点到 t 每步取 top-N 后累加求和。", r"C_t = \sum_{s\le t}\mathrm{sum}(\mathrm{top}_N(X_s))"),
    "cum_top_n_avg": _d("累积 Top-N 均值。", "累积 top-N 的均值。", r"C_t = \mathrm{mean}(\mathrm{cum\_top}_N)"),
    "tm_top_n_sum": _d("时间窗口 Top-N 求和。", "在 tm 窗口内取 top-N 求和。", r"S_t = \sum_{j\in \mathrm{top}_N} X_{t-j}"),
    "tm_top_n_avg": _d("时间窗口 Top-N 均值。", "tm 窗口 top-N 均值。", r"\bar{X}_t = \mathrm{mean}(\mathrm{top}_N(X_{t-m+1:t}))"),
    "cum_first": _d("累计首个有效值。", "到 t 为止第一个非 NaN。", r"F_t = X_{t_0},\ t_0=\min\{s\le t: X_s\ \text{有效}\}"),
    "cum_last": _d("累计最后有效值。", "到 t 为止最后一个非 NaN。", r"L_t = X_{t_1},\ t_1=\max\{s\le t: X_s\ \text{有效}\}"),
    "cum_positive_streak": _d("连续正值计数。", "X>0 连续 bar 数。", r"C_t = \begin{cases}C_{t-1}+1 & X_t>0\\ 0 & \text{否则}\end{cases}"),
    "cum_standardize": _d("累积 Z-Score。", "用 X_{1:t} 的均值/标准差标准化 X_t。", r"Z_t = \frac{X_t - \mu_{1:t}}{\sigma_{1:t}}"),
    # ===== 技术信号 =====
    "ADXR": _d("平滑 ADX。", "ADX 的 EMA 平滑。", r"\mathrm{ADXR} = \mathrm{EMA}(\mathrm{ADX})"),
    "AROON": _d("Aroon 指标。", "Aroon Up - Aroon Down。", r"\mathrm{Aroon} = \mathrm{AroonUp} - \mathrm{AroonDown}"),
    "AROON_up": _d("Aroon 上升。", "距最高价的天数占比 × 100。", r"\mathrm{AroonUp} = \frac{d - \mathrm{days\ since\ high}}{d}\times 100"),
    "AROON_down": _d("Aroon 下降。", "距最低价的天数占比 × 100。", r"\mathrm{AroonDown} = \frac{d - \mathrm{days\ since\ low}}{d}\times 100"),
    "DPO": _d("去趋势价格振荡器。", "Close - SMA(Close, d) 再滞后。", r"\mathrm{DPO} = P_t - \mathrm{SMA}_t(P)"),
    "KAMA": _d("考夫曼自适应均线 KAMA。", "按效率比 ER 自适应平滑系数。", r"\mathrm{KAMA}_t = \mathrm{KAMA}_{t-1} + SC\cdot(P_t - \mathrm{KAMA}_{t-1})"),
    "where": _d("条件选择。", "condition 为真取 a，否则 b（同 if_else）。", r"\begin{cases}a & c\\ b & \neg c\end{cases}"),
    "is_finite": _d("是否有限数。", "非 NaN 且非 inf。", r"\mathbf{1}\{|x|<\infty\}"),
    "vwap": _d("成交量加权平均价 VWAP。", "Σ(P·V)/ΣV。", r"\mathrm{VWAP} = \frac{\sum P_t V_t}{\sum V_t}"),
    "vp_weighted_price": _d("量价加权价格。", "嵌入成交量、波动率、K 线结构的加权价。", r"P^* = \frac{\sum P_i V_i \sigma_i r_i}{\sum V_i}"),
    "vpmacd": _d("VP-MACD。", "量价结构增强的 MACD。", r"\mathrm{VPMACD} = \mathrm{EMA}_f(P^*) - \mathrm{EMA}_s(P^*)"),
    "vpmacd_signal": _d("VP-MACD 交易信号。", "1=买，-1=卖，0=持有。", r"s_t \in \{-1,0,1\}"),
    # ===== 数据清洗 =====
    "is_nan": _d("是否为 NaN。", "逐元素 NaN 检测。", r"\mathbf{1}\{\mathrm{isNaN}(x)\}"),
    "is_inf": _d("是否为无穷。", "逐元素 inf 检测。", r"\mathbf{1}\{|x|=\infty\}"),
    "fillna_const": _d("常量填充缺失。", "NaN 替换为指定常数。", r"\tilde{x} = \begin{cases}x & \text{有效}\\ c & \text{NaN}\end{cases}"),
    "fillna_interpolate": _d("插值填充。", "linear/quadratic/cubic 插值。", r"\tilde{x}_t = \mathrm{interp}(x_{t-1},x_{t+1})"),
    "nan_to_num": _d("NaN/inf 转数值。", "NaN→0，±inf→大数。", r"\mathrm{nan\_to\_num}(x)"),
    "winsorize_mean": _d("截尾均值。", "winsorize 后求均值。", r"\mathrm{mean}(\mathrm{winsorize}(X))"),
    # ===== 截面 / 分组 =====
    "c_mean": _d("截面算术均值。", "每个交易日全市场均值。", r"\bar{X}_{\cdot,t} = \frac{1}{N_t}\sum_i X_{i,t}"),
    "c_std": _d("截面标准差。", "每个交易日全市场样本标准差。", r"\sigma_{\cdot,t} = \mathrm{std}_i(X_{i,t})"),
    "c_sum": _d("截面求和。", "每个交易日全市场求和。", r"S_{\cdot,t} = \sum_i X_{i,t}"),
    "c_count": _d("截面有效计数。", "每个交易日非 NaN 标的个数。", r"N_t = \#\{i: X_{i,t}\ \text{有效}\}"),
    "c_percentile": _d("截面分位位置。", "当前值在截面中的分位 [0,1]。", r"R_{i,t} = \frac{\mathrm{rank}(X_{i,t})-1}{N_t-1}"),
    "panel_rank": _d("面板行百分位排名。", "每个 timestamp 行内 [0,1] 秩。", r"R_{i,t} = \mathrm{rank}_i(X_{\cdot,t})"),
    "panel_zscore": _d("面板行 Z-Score。", "每个 timestamp 行内标准化。", r"Z_{i,t} = \frac{X_{i,t}-\mu_t}{\sigma_t}"),
    "panel_standardize": _d("面板行标准化。", "同 panel_zscore。", r"Z_{i,t} = \frac{X_{i,t}-\mu_t}{\sigma_t}"),
    "panel_neutralize": _d("面板分组中性化。", "按组去均值。", r"\tilde{X}_{i,t} = X_{i,t} - \bar{X}_{g(i),t}"),
    "group_normalize": _d("组内 [0,1] 归一化。", "组内 min-max 缩放。", r"\tilde{X} = \frac{X - X_{\min}}{X_{\max}-X_{\min}}"),
    "group_percentile": _d("组内分位指示。", "判断值是否高于组内分位阈值。", r"\mathbf{1}\{X_{i,t} \ge Q_p(X_{g,t})\}"),
    "group_winsorize": _d("组内缩尾。", "组内两端超出分位截断。", r"\tilde{X} = \mathrm{clip}(X, Q_a, Q_{1-a})"),
    "group_decay_linear": _d("组内线性衰减加权。", "组内按排名线性递减权重。", r"\sum_j w_j X_j,\ w_j \propto (N-j+1)"),
    "move": _d("滑动窗口均值。", "同 SMA/m_avg，长度为 d 的滚动均值。", r"\bar{X}_t = \frac{1}{d}\sum_{k=0}^{d-1} X_{t-k}"),
    "ratios": _d("环比比率。", "X_t / X_{t-1}。", r"R_t = \frac{X_t}{X_{t-1}}"),
}
