#!/usr/bin/env python3
"""
Smoke Test Runner
Executes all smoke tests and generates a comprehensive report.
"""
import subprocess
import sys
import time
import json
from pathlib import Path
from datetime import datetime


def run_smoke_tests():
    """Run all smoke tests and collect results."""
    start_time = time.time()

    smoke_dir = Path("/home/shw/quant_projects/tests/smoke")

    print("=" * 80)
    print("QUANT PROJECTS SMOKE TEST SUITE")
    print("=" * 80)
    print(f"Started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"Python: {sys.version}")
    print(f"Test directory: {smoke_dir}")
    print()

    # Run pytest with verbose output
    result = subprocess.run(
        [
            sys.executable, "-m", "pytest",
            str(smoke_dir),
            "-v",
            "--tb=short",
            "--color=yes",
            "-ra",
            f"--junitxml={smoke_dir}/smoke_results.xml"
        ],
        capture_output=True,
        text=True
    )

    elapsed_time = time.time() - start_time

    # Print output
    print(result.stdout)
    if result.stderr:
        print("STDERR:", result.stderr)

    print()
    print("=" * 80)
    print(f"Total elapsed time: {elapsed_time:.2f} seconds")
    print("=" * 80)

    return {
        "returncode": result.returncode,
        "stdout": result.stdout,
        "stderr": result.stderr,
        "elapsed_time": elapsed_time
    }


def generate_report(results):
    """Generate markdown report from test results."""
    report_path = Path("/home/shw/quant_projects/tests/smoke/SMOKE_TEST_REPORT.md")

    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    report = f"""# Smoke Test Report

**Generated:** {timestamp}
**Duration:** {results['elapsed_time']:.2f} seconds
**Status:** {'✅ PASSED' if results['returncode'] == 0 else '❌ FAILED'}

## Summary

This report covers comprehensive smoke tests for the quant_projects platform:

1. **Package Imports** - All 4 core packages (dataaccess, factor_engine, factor_optimizer, quant_evaluator)
2. **Backend Availability** - numpy, numba, polars, cupy, pandas, duckdb
3. **Basic Workflows** - End-to-end workflow tests for each package
4. **CLI Tools** - Script execution and syntax validation
5. **Documentation** - Documentation completeness and readability
6. **Benchmarks** - Benchmark suite availability and execution

## Test Results

```
{results['stdout']}
```

## Test Categories

### 1. Package Imports
Tests that all core packages can be imported without errors:
- dataaccess
- factor_engine
- factor_optimizer
- quant_evaluator

### 2. Backend Availability
Tests computational backend availability:
- **numpy**: Core numerical computing (required)
- **numba**: JIT compilation for performance
- **polars**: High-performance dataframes
- **cupy**: GPU acceleration (optional)
- **pandas**: Data manipulation
- **duckdb**: SQL analytics engine

### 3. Basic Workflows
Tests end-to-end functionality:
- DataAccess: Registry and data source operations
- FactorEngine: Operator registry and execution
- FactorOptimizer: Basic optimization workflows
- QuantEvaluator: Metrics calculation

### 4. CLI Tools
Tests command-line tools:
- Python scripts: --help flag and basic execution
- Shell scripts: Syntax validation

### 5. Documentation
Tests documentation completeness:
- Main README
- Package READMEs
- Documentation directory structure
- Markdown file readability (including Chinese)

### 6. Benchmarks
Tests benchmark suite:
- Benchmark scripts existence
- Execution capability
- Documentation availability
- Results analysis tools

## Performance Target

Target: < 2 minutes
Actual: {results['elapsed_time']:.2f} seconds
Status: {'✅ Within target' if results['elapsed_time'] < 120 else '⚠️ Exceeded target'}

## Next Steps

{'✅ All smoke tests passed. System is operational.' if results['returncode'] == 0 else '''
⚠️ Some tests failed or were skipped. Review the output above for details.

Common reasons for test failures:
- Missing dependencies (install with pip/conda)
- Configuration required (check package documentation)
- GPU not available (cupy tests will be skipped)
- Network connectivity (for remote data sources)
'''}

## Test Execution

To run smoke tests manually:

```bash
cd /home/shw/quant_projects
python3 -m pytest tests/smoke/ -v
```

To run a specific test category:

```bash
python3 -m pytest tests/smoke/test_imports.py -v
python3 -m pytest tests/smoke/test_backends.py -v
python3 -m pytest tests/smoke/test_workflows.py -v
python3 -m pytest tests/smoke/test_cli_tools.py -v
python3 -m pytest tests/smoke/test_documentation.py -v
python3 -m pytest tests/smoke/test_benchmarks.py -v
```

---
*Generated by smoke test runner*
"""

    report_path.write_text(report, encoding='utf-8')
    print(f"\n📄 Report generated: {report_path}")

    return report_path


if __name__ == "__main__":
    try:
        results = run_smoke_tests()
        report_path = generate_report(results)

        # Exit with same code as pytest
        sys.exit(results['returncode'])
    except Exception as e:
        print(f"❌ Error running smoke tests: {e}", file=sys.stderr)
        sys.exit(1)
