# -*- coding: utf-8 -*-
"""End-to-end multi-backend integration tests.

Tests cover:
- Complete factor computation flows
- Large-scale batch processing
- Memory-constrained scenarios
- Concurrent execution
- Failure recovery
"""
from __future__ import annotations

import pytest
import numpy as np
import pandas as pd

from factor_engine.planner.backend_region import (
    PhysicalBackend,
    Representation,
    BackendRegion,
    TransferEdge,
    TransferTransform,
    PhysicalRegionPlan,
    ExecutionAxis,
    PhysicalProperties,
    StateContract,
)


class TestSimpleFactorComputation:
    """Test simple end-to-end factor computation."""

    def test_single_backend_simple_factor(self, sample_panel_data):
        """Test simple factor on single backend."""
        df = sample_panel_data.copy()

        # Compute simple moving average factor
        df = df.sort_values(["instrument", "date"])
        df["sma_5"] = df.groupby("instrument")["close"].transform(
            lambda x: x.rolling(window=5, min_periods=1).mean()
        )

        assert "sma_5" in df.columns
        assert not df["sma_5"].isna().all()
        assert len(df) == len(sample_panel_data)

    def test_multi_backend_composite_factor(self, sample_panel_data):
        """Test composite factor requiring multiple backends."""
        df = sample_panel_data.copy()

        # Step 1: Time-series features (Polars/Pandas)
        df = df.sort_values(["instrument", "date"])
        df["returns_ma"] = df.groupby("instrument")["returns"].transform(
            lambda x: x.rolling(window=10, min_periods=1).mean()
        )

        # Step 2: Cross-sectional rank (would use DuckDB)
        df["rank_volume"] = df.groupby("date")["volume"].rank(pct=True)

        # Step 3: Combine
        df["composite"] = df["returns_ma"] * df["rank_volume"]

        assert "composite" in df.columns
        assert not df["composite"].isna().all()


class TestLargeScaleBatch:
    """Test large-scale batch processing."""

    def test_batch_100_factors(self, sample_panel_data):
        """Test computing 100 factors in batch."""
        df = sample_panel_data.copy()
        df = df.sort_values(["instrument", "date"])

        # Simulate computing 100 simple factors
        for i in range(10):  # 10 factors for test speed
            window = 5 + i
            df[f"sma_{window}"] = df.groupby("instrument")["close"].transform(
                lambda x: x.rolling(window=window, min_periods=1).mean()
            )

        # Check all factors computed
        for i in range(10):
            assert f"sma_{5+i}" in df.columns

    def test_batch_1000_factors_plan_only(self):
        """Test planning for 1000 factors (plan only, no execution)."""
        # Create a plan for 1000 factors
        # In practice, this would be generated by the planner

        num_factors = 1000
        factors_per_region = 50

        regions = []
        for i in range(num_factors // factors_per_region):
            node_ids = tuple(f"n{i*factors_per_region + j}" for j in range(factors_per_region))
            regions.append(
                BackendRegion(
                    region_id=f"r{i}",
                    backend=PhysicalBackend.POLARS_PANEL,
                    representation=Representation.POLARS_LONG,
                    node_ids=node_ids,
                    execution_axis=ExecutionAxis.TIME_PER_INSTRUMENT,
                    required_properties=PhysicalProperties(),
                    state_contract=StateContract(),
                    estimated_rows=100_000,
                    estimated_compute_ms=50.0,
                    estimated_memory_bytes=8_000_000,
                )
            )

        plan = PhysicalRegionPlan(
            plan_id="large_batch_plan",
            regions=tuple(regions),
            edges=(),
            topological_order=tuple(f"r{i}" for i in range(len(regions))),
            root_region_ids=tuple(f"r{i}" for i in range(len(regions))),
            total_compute_ms=5000.0,
            total_transfer_ms=0.0,
            total_ttdc_ms=5000.0,
            peak_memory_bytes=160_000_000,
            logical_node_count=num_factors,
            backend_switch_count=0,
            native_fraction=0.95,
        )

        assert plan.logical_node_count == num_factors
        assert len(plan.regions) == num_factors // factors_per_region

    def test_large_batch_memory_tracking(self, large_panel_data):
        """Test memory tracking for large batch."""
        df = large_panel_data.copy()

        # Estimate memory usage
        initial_memory = df.memory_usage(deep=True).sum()

        # Compute several factors
        df = df.sort_values(["instrument", "date"])
        for i in range(5):
            df[f"feature_{i}"] = df.groupby("instrument")["close"].transform(
                lambda x: x.rolling(window=10+i, min_periods=1).mean()
            )

        final_memory = df.memory_usage(deep=True).sum()

        # Memory should increase with new columns
        assert final_memory > initial_memory


class TestMemoryConstrainedScenarios:
    """Test execution under memory constraints."""

    def test_streaming_execution_low_memory(self):
        """Test streaming execution in low memory scenario."""
        # Plan using streaming-capable backend
        region = BackendRegion(
            region_id="r1",
            backend=PhysicalBackend.DUCKDB_SQL,
            representation=Representation.DUCKDB_RELATION,
            node_ids=("filter", "aggregate", "sort"),
            execution_axis=ExecutionAxis.RELATIONAL,
            required_properties=PhysicalProperties(),
            state_contract=StateContract(),
            estimated_rows=10_000_000,
            estimated_compute_ms=50.0,
            estimated_memory_bytes=50_000_000,
            streaming_capable=True,
        )

        plan = PhysicalRegionPlan(
            plan_id="streaming_plan",
            regions=(region,),
            edges=(),
            topological_order=("r1",),
            root_region_ids=("r1",),
            total_compute_ms=120.0,
            total_transfer_ms=0.0,
            total_ttdc_ms=120.0,
            peak_memory_bytes=50_000_000,
            logical_node_count=3,
            backend_switch_count=0,
            native_fraction=1.0,
        )

        assert region.streaming_capable is True
        assert plan.peak_memory_bytes == 50_000_000

    def test_spill_to_disk_when_oom(self):
        """Test spill-to-disk behavior when out of memory."""
        # This would test actual spill behavior in real implementation
        # For now, we verify the plan accounts for large memory

        large_region = BackendRegion(
            region_id="r1",
            backend=PhysicalBackend.POLARS_PANEL,
            representation=Representation.POLARS_LONG,
            node_ids=("n1", "n2", "n3"),
            execution_axis=ExecutionAxis.TIME_PER_INSTRUMENT,
            required_properties=PhysicalProperties(),
            state_contract=StateContract(),
            estimated_rows=100_000_000,
            estimated_compute_ms=50.0,
            estimated_memory_bytes=8_000_000_000,  # 8GB
        )

        # Memory budget exceeded - would trigger spill
        memory_budget = 4_000_000_000  # 4GB
        assert large_region.estimated_memory_bytes > memory_budget

    def test_batch_size_reduction_under_memory_pressure(self):
        """Test reducing batch size under memory pressure."""
        # Normal batch size
        normal_batch = 10_000
        normal_memory = normal_batch * 1000  # bytes per row

        # Reduced batch size
        memory_budget = 5_000_000  # 5MB
        reduced_batch = memory_budget // 1000

        assert reduced_batch < normal_batch
        assert reduced_batch * 1000 <= memory_budget


class TestConcurrentExecution:
    """Test concurrent region execution."""

    def test_parallel_independent_regions(self):
        """Test parallel execution of independent regions."""
        # Two independent regions that can run in parallel
        region1 = BackendRegion(
            region_id="r1",
            backend=PhysicalBackend.POLARS_PANEL,
            representation=Representation.POLARS_LONG,
            node_ids=("n1", "n2"),
            execution_axis=ExecutionAxis.TIME_PER_INSTRUMENT,
            required_properties=PhysicalProperties(),
            state_contract=StateContract(),
            estimated_rows=100_000,
            estimated_compute_ms=50.0,
            estimated_memory_bytes=8_000_000,
        )

        region2 = BackendRegion(
            region_id="r2",
            backend=PhysicalBackend.POLARS_PANEL,
            representation=Representation.POLARS_LONG,
            node_ids=("n3", "n4"),
            execution_axis=ExecutionAxis.TIME_PER_INSTRUMENT,
            required_properties=PhysicalProperties(),
            state_contract=StateContract(),
            estimated_rows=100_000,
            estimated_compute_ms=50.0,
            estimated_memory_bytes=8_000_000,
        )

        plan = PhysicalRegionPlan(
            plan_id="parallel_plan",
            regions=(region1, region2),
            edges=(),  # No dependencies
            topological_order=("r1", "r2"),
            root_region_ids=("r1", "r2"),
            total_compute_ms=50.0,  # Can run in parallel
            total_transfer_ms=0.0,
            total_ttdc_ms=50.0,  # Not 100ms (would be sequential)
            peak_memory_bytes=16_000_000,
            logical_node_count=4,
            backend_switch_count=0,
            native_fraction=1.0,
        )

        # Both are roots (independent)
        assert len(plan.root_region_ids) == 2

    def test_sequential_dependent_regions(self):
        """Test sequential execution of dependent regions."""
        region1 = BackendRegion(
            region_id="r1",
            backend=PhysicalBackend.POLARS_PANEL,
            representation=Representation.POLARS_LONG,
            node_ids=("n1", "n2"),
            execution_axis=ExecutionAxis.TIME_PER_INSTRUMENT,
            required_properties=PhysicalProperties(),
            state_contract=StateContract(),
            estimated_rows=100_000,
            estimated_compute_ms=50.0,
            estimated_memory_bytes=8_000_000,
        )

        region2 = BackendRegion(
            region_id="r2",
            backend=PhysicalBackend.DUCKDB_SQL,
            representation=Representation.DUCKDB_RELATION,
            node_ids=("n3", "n4"),
            execution_axis=ExecutionAxis.RELATIONAL,
            required_properties=PhysicalProperties(),
            state_contract=StateContract(),
            estimated_rows=100_000,
            estimated_compute_ms=50.0,
            estimated_memory_bytes=6_000_000,
        )

        edge = TransferEdge(
            edge_id="e1",
            producer_region="r1",
            consumer_region="r2",
            source_backend=PhysicalBackend.POLARS_PANEL,
            target_backend=PhysicalBackend.DUCKDB_SQL,
            source_representation=Representation.POLARS_LONG,
            target_representation=Representation.DUCKDB_RELATION,
            estimated_rows=100_000,
            estimated_bytes=800_000,
            estimated_transfer_ms=15.0,
            transform=TransferTransform.POLARS_TO_NUMPY,
        )

        plan = PhysicalRegionPlan(
            plan_id="sequential_plan",
            regions=(region1, region2),
            edges=(edge,),
            topological_order=("r1", "r2"),
            root_region_ids=("r2",),  # Only r2 is root
            total_compute_ms=80.0,
            total_transfer_ms=15.0,
            total_ttdc_ms=95.0,  # Sequential: 50 + 15 + 30
            peak_memory_bytes=14_000_000,
            logical_node_count=4,
            backend_switch_count=1,
            native_fraction=0.85,
        )

        # Only one root (r2 depends on r1)
        assert len(plan.root_region_ids) == 1
        assert plan.topological_order == ("r1", "r2")


class TestFailureRecovery:
    """Test failure recovery scenarios."""

    def test_backend_unavailable_fallback(self):
        """Test fallback when preferred backend is unavailable."""
        # Preferred plan with DuckDB
        preferred_plan = PhysicalRegionPlan(
            plan_id="preferred",
            regions=(
                BackendRegion(
                    region_id="r1",
                    backend=PhysicalBackend.DUCKDB_SQL,
                    representation=Representation.DUCKDB_RELATION,
                    node_ids=("n1", "n2"),
                    execution_axis=ExecutionAxis.RELATIONAL,
                    required_properties=PhysicalProperties(),
                    state_contract=StateContract(),
                    estimated_rows=100_000,
                    estimated_compute_ms=50.0,
                    estimated_memory_bytes=6_000_000,
                ),
            ),
            edges=(),
            topological_order=("r1",),
            root_region_ids=("r1",),
            total_compute_ms=30.0,
            total_transfer_ms=0.0,
            total_ttdc_ms=30.0,
            peak_memory_bytes=6_000_000,
            logical_node_count=2,
            backend_switch_count=0,
            native_fraction=1.0,
        )

        # Fallback plan with Pandas
        fallback_plan = PhysicalRegionPlan(
            plan_id="fallback",
            regions=(
                BackendRegion(
                    region_id="r1",
                    backend=PhysicalBackend.PANDAS_NUMPY,
                    representation=Representation.PANDAS_LONG,
                    node_ids=("n1", "n2"),
                    execution_axis=ExecutionAxis.TIME_PER_INSTRUMENT,
                    required_properties=PhysicalProperties(),
                    state_contract=StateContract(),
                    estimated_rows=100_000,
                    estimated_compute_ms=50.0,
                    estimated_memory_bytes=8_000_000,
                ),
            ),
            edges=(),
            topological_order=("r1",),
            root_region_ids=("r1",),
            total_compute_ms=60.0,  # Slower but available
            total_transfer_ms=0.0,
            total_ttdc_ms=60.0,
            peak_memory_bytes=8_000_000,
            logical_node_count=2,
            backend_switch_count=0,
            native_fraction=0.80,
        )

        # Fallback should have same logical nodes
        assert (
            preferred_plan.logical_node_count ==
            fallback_plan.logical_node_count
        )

    def test_timeout_handling(self):
        """Test timeout handling for long-running operations."""
        # This would test actual timeout behavior
        # For now, verify timeout is tracked in plan

        region = BackendRegion(
            region_id="r1",
            backend=PhysicalBackend.DUCKDB_SQL,
            representation=Representation.DUCKDB_RELATION,
            node_ids=("expensive_op",),
            execution_axis=ExecutionAxis.RELATIONAL,
            required_properties=PhysicalProperties(),
            state_contract=StateContract(),
            estimated_rows=100_000_000,
            estimated_compute_ms=50.0,
            estimated_memory_bytes=1_000_000_000,
        )

        plan = PhysicalRegionPlan(
            plan_id="long_running",
            regions=(region,),
            edges=(),
            topological_order=("r1",),
            root_region_ids=("r1",),
            total_compute_ms=300_000.0,  # 5 minutes
            total_transfer_ms=0.0,
            total_ttdc_ms=300_000.0,
            peak_memory_bytes=1_000_000_000,
            logical_node_count=1,
            backend_switch_count=0,
            native_fraction=1.0,
        )

        # Would timeout with 1-minute deadline
        timeout_ms = 60_000  # 1 minute
        assert plan.total_ttdc_ms > timeout_ms

    def test_partial_failure_recovery(self):
        """Test recovery from partial failures."""
        # Scenario: 3 regions, middle one fails
        region1 = BackendRegion(
            region_id="r1",
            backend=PhysicalBackend.POLARS_PANEL,
            representation=Representation.POLARS_LONG,
            node_ids=("n1",),
            execution_axis=ExecutionAxis.TIME_PER_INSTRUMENT,
            required_properties=PhysicalProperties(),
            state_contract=StateContract(),
            estimated_rows=100_000,
            estimated_compute_ms=50.0,
            estimated_memory_bytes=8_000_000,
        )

        region2_failed = BackendRegion(
            region_id="r2",
            backend=PhysicalBackend.DUCKDB_SQL,
            representation=Representation.DUCKDB_RELATION,
            node_ids=("n2",),
            execution_axis=ExecutionAxis.RELATIONAL,
            required_properties=PhysicalProperties(),
            state_contract=StateContract(),
            estimated_rows=100_000,
            estimated_compute_ms=50.0,
            estimated_memory_bytes=6_000_000,
        )

        region3 = BackendRegion(
            region_id="r3",
            backend=PhysicalBackend.POLARS_PANEL,
            representation=Representation.POLARS_LONG,
            node_ids=("n3",),
            execution_axis=ExecutionAxis.TIME_PER_INSTRUMENT,
            required_properties=PhysicalProperties(),
            state_contract=StateContract(),
            estimated_rows=100_000,
            estimated_compute_ms=50.0,
            estimated_memory_bytes=7_000_000,
        )

        # Original plan with r2
        original_plan = PhysicalRegionPlan(
            plan_id="original",
            regions=(region1, region2_failed, region3),
            edges=(
                TransferEdge(
                    edge_id="e12",
                    producer_region="r1",
                    consumer_region="r2",
                    source_backend=PhysicalBackend.POLARS_PANEL,
                    target_backend=PhysicalBackend.DUCKDB_SQL,
                    source_representation=Representation.POLARS_LONG,
                    target_representation=Representation.DUCKDB_RELATION,
                    estimated_rows=100_000,
                    estimated_bytes=8_000_000,
                    estimated_transfer_ms=10.0,
                    transform=TransferTransform.POLARS_TO_NUMPY,
                ),
                TransferEdge(
                    edge_id="e23",
                    producer_region="r2",
                    consumer_region="r3",
                    source_backend=PhysicalBackend.DUCKDB_SQL,
                    target_backend=PhysicalBackend.POLARS_PANEL,
                    source_representation=Representation.DUCKDB_RELATION,
                    target_representation=Representation.POLARS_LONG,
                    estimated_rows=100_000,
                    estimated_bytes=7_000_000,
                    estimated_transfer_ms=10.0,
                    transform=TransferTransform.POLARS_TO_NUMPY,
                ),
            ),
            topological_order=("r1", "r2", "r3"),
            root_region_ids=("r3",),
            total_compute_ms=90.0,
            total_transfer_ms=20.0,
            total_ttdc_ms=110.0,
            peak_memory_bytes=21_000_000,
            logical_node_count=3,
            backend_switch_count=2,
            native_fraction=0.85,
        )

        # Recovery: replan without r2, merge into r1 or r3
        # In practice, would recompute r2 in different backend
        assert len(original_plan.regions) == 3


class TestComplexDataFlows:
    """Test complex multi-backend data flows."""

    def test_join_across_backends(self, sample_panel_data):
        """Test join operation across different backends."""
        df1 = sample_panel_data[["date", "instrument", "close"]].copy()
        df2 = sample_panel_data[["date", "instrument", "volume"]].copy()

        # Join in Pandas (simulates cross-backend join)
        result = pd.merge(
            df1,
            df2,
            on=["date", "instrument"],
            how="inner"
        )

        assert len(result) == len(sample_panel_data)
        assert "close" in result.columns
        assert "volume" in result.columns

    def test_aggregation_then_rolling(self, sample_panel_data):
        """Test aggregation (SQL) then rolling (Polars) workflow."""
        df = sample_panel_data.copy()

        # Step 1: Aggregation (would use DuckDB)
        daily_agg = df.groupby("date").agg({
            "close": "mean",
            "volume": "sum"
        }).reset_index()

        # Step 2: Rolling window (would use Polars)
        daily_agg = daily_agg.sort_values("date")
        daily_agg["close_ma"] = daily_agg["close"].rolling(window=5).mean()

        assert "close_ma" in daily_agg.columns
        assert len(daily_agg) == df["date"].nunique()

    def test_multi_way_merge(self, sample_panel_data):
        """Test multi-way merge from different backends."""
        df = sample_panel_data.copy()

        # Three separate computations (could be different backends)
        df1 = df[["date", "instrument", "close"]].copy()
        df1["feature1"] = df1["close"] * 2

        df2 = df[["date", "instrument", "volume"]].copy()
        df2["feature2"] = df2["volume"] / 1000

        df3 = df[["date", "instrument", "returns"]].copy()
        df3["feature3"] = df3["returns"].abs()

        # Merge all three
        result = df1.merge(df2, on=["date", "instrument"])
        result = result.merge(df3, on=["date", "instrument"])

        assert all(col in result.columns for col in ["feature1", "feature2", "feature3"])
        assert len(result) == len(sample_panel_data)