#!/usr/bin/env python3
"""Script to add metadata to all 112 operators in ts_batch1.py"""

import re

# Read the file
with open("/home/shw/quant_projects/factor_engine/cleaned_operators/polars_native/ts_batch1.py", "r") as f:
    content = f.read()

# Metadata templates for each operator pattern
def create_metadata(class_name, op_name, description, params, param_specs_dict, category="time_series"):
    """Generate metadata string for an operator"""
    param_specs_lines = []
    for param, spec in param_specs_dict.items():
        param_specs_lines.append(f'        "{param}": {spec},')

    param_specs_str = "\n".join(param_specs_lines) if param_specs_lines else ""

    metadata = f'''
    metadata = OperatorMetadata(
        name="{op_name}",
        category="{category}",
        description="{description}",
        param_names={params},
        return_type="series",
        tags=["time_series", "rolling", "pit_safe", "polars_native"],
    )'''

    if param_specs_str:
        metadata += f'''
    metadata.param_specs = {{
{param_specs_str}
    }}'''

    return metadata

# Define all operators with their metadata
operators = [
    ("TSMinIfPolarsNative", "ts_min_if", "Conditional rolling minimum", ["feature", "condition", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSMaxIfPolarsNative", "ts_max_if", "Conditional rolling maximum", ["feature", "condition", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSMedianPolarsNative", "ts_median", "Rolling median", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSQuantilePolarsNative", "ts_quantile", "Rolling quantile", ["feature", "window", "quantile"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)",
      "quantile": "ParamSpec(dtype=float, min=0.0, max=1.0, default=0.5, param_role=ParamRole.SCALAR)"}),
    ("TSQuantileIfPolarsNative", "ts_quantile_if", "Conditional rolling quantile", ["feature", "condition", "window", "quantile"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)",
      "quantile": "ParamSpec(dtype=float, min=0.0, max=1.0, default=0.5, param_role=ParamRole.SCALAR)"}),
    ("TSRankIfPolarsNative", "ts_rank_if", "Conditional rolling rank (current value rank in window)", ["feature", "condition", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSCorrPolarsNative", "ts_corr", "Rolling correlation between two series", ["x", "y", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSCovPolarsNative", "ts_cov", "Rolling covariance between two series", ["x", "y", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSCorrIfPolarsNative", "ts_corr_if", "Conditional rolling correlation", ["x", "y", "condition", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSCovIfPolarsNative", "ts_cov_if", "Conditional rolling covariance", ["x", "y", "condition", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSNthValuePolarsNative", "ts_nth_value", "Get nth value from current position (negative=past, positive=future)", ["feature", "n"],
     {"n": "ParamSpec(dtype=int, param_role=ParamRole.SCALAR)"}),
    ("TSLastIfPolarsNative", "ts_last_if", "Get last value where condition was True within window", ["feature", "condition", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSCountIfPolarsNative", "ts_count_if", "Count of True values in rolling window", ["condition", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSValidCountPolarsNative", "ts_valid_count", "Count of non-null values in rolling window", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSCoverageRatioPolarsNative", "ts_coverage_ratio", "Ratio of non-null values in rolling window", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSPositiveRatioPolarsNative", "ts_positive_ratio", "Ratio of positive values in rolling window", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSNegativeRatioPolarsNative", "ts_negative_ratio", "Ratio of negative values in rolling window", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSZeroRatioPolarsNative", "ts_zero_ratio", "Ratio of zero values in rolling window", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSArgmaxPolarsNative", "ts_argmax", "Index of maximum value in rolling window (0=oldest, window-1=current)", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSArgminPolarsNative", "ts_argmin", "Index of minimum value in rolling window", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSArgmaxAgePolarsNative", "ts_argmax_age", "Periods since maximum value in rolling window", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSArgminAgePolarsNative", "ts_argmin_age", "Periods since minimum value in rolling window", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSTopkMeanPolarsNative", "ts_topk_mean", "Mean of top k values in rolling window", ["feature", "window", "k"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)",
      "k": "ParamSpec(dtype=int, min=1, param_role=ParamRole.SCALAR)"}),
    ("TSTopkSumPolarsNative", "ts_topk_sum", "Sum of top k values in rolling window", ["feature", "window", "k"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)",
      "k": "ParamSpec(dtype=int, min=1, param_role=ParamRole.SCALAR)"}),
    ("TSTopkStdPolarsNative", "ts_topk_std", "Std of top k values in rolling window", ["feature", "window", "k"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)",
      "k": "ParamSpec(dtype=int, min=1, param_role=ParamRole.SCALAR)"}),
    ("TSBottomkMeanPolarsNative", "ts_bottomk_mean", "Mean of bottom k values in rolling window", ["feature", "window", "k"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)",
      "k": "ParamSpec(dtype=int, min=1, param_role=ParamRole.SCALAR)"}),
    ("TSBottomkSumPolarsNative", "ts_bottomk_sum", "Sum of bottom k values in rolling window", ["feature", "window", "k"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)",
      "k": "ParamSpec(dtype=int, min=1, param_role=ParamRole.SCALAR)"}),
    ("TSBottomkStdPolarsNative", "ts_bottomk_std", "Std of bottom k values in rolling window", ["feature", "window", "k"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)",
      "k": "ParamSpec(dtype=int, min=1, param_role=ParamRole.SCALAR)"}),
    ("TSKurtPolarsNative", "ts_kurt", "Rolling kurtosis", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=4, param_role=ParamRole.WINDOW)"}),
    ("TSMomentPolarsNative", "ts_moment", "Rolling nth central moment", ["feature", "window", "n"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)",
      "n": "ParamSpec(dtype=int, min=1, default=2, param_role=ParamRole.SCALAR)"}),
    ("TSQuantileRangePolarsNative", "ts_quantile_range", "Rolling IQR or quantile range", ["feature", "window", "lower", "upper"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)",
      "lower": "ParamSpec(dtype=float, min=0.0, max=1.0, default=0.25, param_role=ParamRole.SCALAR)",
      "upper": "ParamSpec(dtype=float, min=0.0, max=1.0, default=0.75, param_role=ParamRole.SCALAR)"}),
    ("TSTrimmedMeanPolarsNative", "ts_trimmed_mean", "Rolling trimmed mean (exclude top/bottom percentiles)", ["feature", "window", "trim"],
     {"window": "ParamSpec(dtype=int, min=3, param_role=ParamRole.WINDOW)",
      "trim": "ParamSpec(dtype=float, min=0.0, max=0.5, default=0.1, param_role=ParamRole.SCALAR)"}),
    ("TSRatioPolarsNative", "ts_ratio", "Current value / rolling statistic (mean, median, etc.)", ["feature", "window", "stat"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)",
      "stat": "ParamSpec(dtype=str, default='mean', param_role=ParamRole.SCALAR)"}),
    ("TSLocationShiftPolarsNative", "ts_location_shift", "(current - rolling_mean) / rolling_std", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSScaleShiftPolarsNative", "ts_scale_shift", "Rolling std / long-term rolling std", ["feature", "short_window", "long_window"],
     {"short_window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)",
      "long_window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSDecayLinearPolarsNative", "ts_decay_linear", "Linear decay weighted sum: most recent gets weight window, oldest gets 1", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSSumDecayPolarsNative", "ts_sum_decay", "Exponentially decayed sum", ["feature", "window", "decay"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)",
      "decay": "ParamSpec(dtype=float, min=0.0, max=1.0, default=0.9, param_role=ParamRole.SCALAR)"}),
    ("TSDecayExpWindowPolarsNative", "ts_decay_exp_window", "Exponentially weighted mean with specified window", ["feature", "window", "alpha"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)",
      "alpha": "ParamSpec(dtype=float, min=0.0, max=1.0, default=None, param_role=ParamRole.SCALAR)"}),
    ("TSDaysSincePolarsNative", "ts_days_since", "Days since condition was last True", ["condition"],
     {}),
    ("TSDaysSinceHighPolarsNative", "ts_days_since_high", "Days since rolling window high", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSDaysSinceLowPolarsNative", "ts_days_since_low", "Days since rolling window low", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSTimeSinceChangePolarsNative", "ts_time_since_change", "Periods since value changed", ["feature"],
     {}),
    ("TSTrueStreakPolarsNative", "ts_true_streak", "Current streak length of True values", ["condition"],
     {}),
    ("TSTransitionCountPolarsNative", "ts_transition_count", "Count of state transitions (value changes) in rolling window", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSNewHighPolarsNative", "ts_new_high", "Boolean: current value equals rolling max", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSNewLowPolarsNative", "ts_new_low", "Boolean: current value equals rolling min", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSDistanceToHighPolarsNative", "ts_distance_to_high", "(rolling_max - current) / rolling_max", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSDistanceToLowPolarsNative", "ts_distance_to_low", "(current - rolling_min) / current", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSChannelWidthPolarsNative", "ts_channel_width", "rolling_max - rolling_min", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSChannelWidthPctPolarsNative", "ts_channel_width_pct", "(rolling_max - rolling_min) / rolling_mean", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSChannelPositionPolarsNative", "ts_channel_position", "(current - rolling_min) / (rolling_max - rolling_min)", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSMaxDrawdownPolarsNative", "ts_max_drawdown", "Maximum drawdown in rolling window", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSTimeUnderWaterPolarsNative", "ts_time_under_water", "Periods since last peak (underwater duration)", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSRecoveryFractionPolarsNative", "ts_recovery_fraction", "How much of max drawdown has been recovered", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSDownsideDeviationPolarsNative", "ts_downside_deviation", "Std of negative returns only", ["feature", "window", "threshold"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)",
      "threshold": "ParamSpec(dtype=float, default=0.0, param_role=ParamRole.SCALAR)"}),
    ("TSUpsideDeviationPolarsNative", "ts_upside_deviation", "Std of positive returns only", ["feature", "window", "threshold"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)",
      "threshold": "ParamSpec(dtype=float, default=0.0, param_role=ParamRole.SCALAR)"}),
    ("TSExpectedShortfallPolarsNative", "ts_expected_shortfall", "Mean of worst outcomes (CVaR)", ["feature", "window", "alpha"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)",
      "alpha": "ParamSpec(dtype=float, min=0.0, max=1.0, default=0.05, param_role=ParamRole.SCALAR)"}),
    ("TSLowerPartialMomentPolarsNative", "ts_lower_partial_moment", "LPM(n) - mean of (threshold - x)^n for x < threshold", ["feature", "window", "threshold", "n"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)",
      "threshold": "ParamSpec(dtype=float, default=0.0, param_role=ParamRole.SCALAR)",
      "n": "ParamSpec(dtype=int, min=1, default=2, param_role=ParamRole.SCALAR)"}),
    ("TSUpperPartialMomentPolarsNative", "ts_upper_partial_moment", "UPM(n) - mean of (x - threshold)^n for x > threshold", ["feature", "window", "threshold", "n"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)",
      "threshold": "ParamSpec(dtype=float, default=0.0, param_role=ParamRole.SCALAR)",
      "n": "ParamSpec(dtype=int, min=1, default=2, param_role=ParamRole.SCALAR)"}),
    ("TSVolOfVolPolarsNative", "ts_vol_of_vol", "Volatility of volatility - std of rolling std", ["feature", "short_window", "long_window"],
     {"short_window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)",
      "long_window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSRegressionSlopePolarsNative", "ts_regression_slope", "Linear regression slope of feature vs time", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSRegressionInterceptPolarsNative", "ts_regression_intercept", "Linear regression intercept", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSRegressionR2PolarsNative", "ts_regression_r2", "Linear regression R-squared", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSRegressionResidPolarsNative", "ts_regression_resid", "Current value - predicted value from rolling regression", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSTimeSlopePolarsNative", "ts_time_slope", "Alias for regression slope", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSMonotonicityPolarsNative", "ts_monotonicity", "Measure of monotonic trend: (up_count - down_count) / window", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSStalenessPolarsNative", "ts_staleness", "Ratio of unique values to window size (1 - uniqueness)", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSSignPersistencePolarsNative", "ts_sign_persistence", "Average streak length of same sign", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSEwmCorrPolarsNative", "ts_ewm_corr", "Exponentially weighted correlation", ["x", "y", "span"],
     {"span": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSEwmCovPolarsNative", "ts_ewm_cov", "Exponentially weighted covariance", ["x", "y", "span"],
     {"span": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSKamaPolarsNative", "ts_kama", "Kaufman Adaptive Moving Average", ["feature", "window", "fast", "slow"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)",
      "fast": "ParamSpec(dtype=int, min=1, default=2, param_role=ParamRole.SCALAR)",
      "slow": "ParamSpec(dtype=int, min=1, default=30, param_role=ParamRole.SCALAR)"}),
    ("TSAutocorrelationTimePolarsNative", "ts_autocorrelation_time", "Integrated autocorrelation time", ["feature", "window", "max_lag"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)",
      "max_lag": "ParamSpec(dtype=int, min=1, default=None, param_role=ParamRole.SCALAR)"}),
    ("TSMeanReversionHalfLifePolarsNative", "ts_mean_reversion_half_life", "Half-life of mean reversion (AR(1) model)", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=3, param_role=ParamRole.WINDOW)"}),
    ("TSPrevHighPolarsNative", "ts_prev_high", "Previous rolling window high", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSPrevLowPolarsNative", "ts_prev_low", "Previous rolling window low", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSSwingAmplitudePolarsNative", "ts_swing_amplitude", "Current swing range (from last pivot)", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSSwingAmplitudePctPolarsNative", "ts_swing_amplitude_pct", "Swing amplitude as percentage of price", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("TSPathEfficiencyPolarsNative", "ts_path_efficiency", "Straight-line distance / path distance", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSRoughnessPolarsNative", "ts_roughness", "Path roughness: sum of |diff| / straight distance", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSTurningRatePolarsNative", "ts_turning_rate", "Rate of direction changes (sign changes in first diff)", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=3, param_role=ParamRole.WINDOW)"}),
    ("TSScoreRankWeightedMeanPolarsNative", "ts_score_rank_weighted_mean", "Weighted mean where weights are ranks of a score series", ["feature", "score", "window"],
     {"window": "ParamSpec(dtype=int, min=1, param_role=ParamRole.WINDOW)"}),
    ("ExpandingRankPolarsNative", "expanding_rank", "Rank of current value within all historical values", ["feature"],
     {}),
    ("TSRobustZscorePriorPolarsNative", "ts_robust_zscore_prior", "Z-score using prior window (not including current value)", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSRobustZscoreInclusivePolarsNative", "ts_robust_zscore_inclusive", "Z-score using median and MAD instead of mean and std", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSQnScalePolarsNative", "ts_qn_scale", "Qn robust scale estimator", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSRegressionResidMeanPolarsNative", "ts_regression_resid_mean", "Mean of regression residuals in window", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSRegressionTstatPolarsNative", "ts_regression_tstat", "T-statistic of regression slope", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=3, param_role=ParamRole.WINDOW)"}),
    ("TSRegressionForecastErrorPolarsNative", "ts_regression_forecast_error", "Forecast error: actual next value - predicted next value", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSRegressionForecastErrorZPolarsNative", "ts_regression_forecast_error_z", "Standardized forecast error", ["feature", "window"],
     {"window": "ParamSpec(dtype=int, min=3, param_role=ParamRole.WINDOW)"}),
    ("TSBetaIfPolarsNative", "ts_beta_if", "Conditional rolling beta: cov(x,y) / var(y)", ["x", "y", "condition", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
    ("TSTailRatioPolarsNative", "ts_tail_ratio", "Ratio of upper tail to lower tail (e.g., 95th percentile / 5th percentile)", ["feature", "window", "upper", "lower"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)",
      "upper": "ParamSpec(dtype=float, min=0.0, max=1.0, default=0.95, param_role=ParamRole.SCALAR)",
      "lower": "ParamSpec(dtype=float, min=0.0, max=1.0, default=0.05, param_role=ParamRole.SCALAR)"}),
    ("TSTailMeanPolarsNative", "ts_tail_mean", "Mean of extreme tail (beyond threshold quantile)", ["feature", "window", "threshold"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)",
      "threshold": "ParamSpec(dtype=float, min=0.0, max=1.0, default=0.95, param_role=ParamRole.SCALAR)"}),
    ("TSExpectedShortfallAsymmetryPolarsNative", "ts_expected_shortfall_asymmetry", "Ratio of upper ES to lower ES", ["feature", "window", "alpha"],
     {"window": "ParamSpec(dtype=int, min=10, param_role=ParamRole.WINDOW)",
      "alpha": "ParamSpec(dtype=float, min=0.0, max=1.0, default=0.05, param_role=ParamRole.SCALAR)"}),
    ("TSPartialCorrPolarsNative", "ts_partial_corr", "Partial correlation of x and y controlling for z", ["x", "y", "z", "window"],
     {"window": "ParamSpec(dtype=int, min=3, param_role=ParamRole.WINDOW)"}),
    ("TSDistanceCorrPolarsNative", "ts_distance_corr", "Distance correlation (detects nonlinear dependencies)", ["x", "y", "window"],
     {"window": "ParamSpec(dtype=int, min=2, param_role=ParamRole.WINDOW)"}),
]

# Process each operator
for class_name, op_name, desc, params, param_specs in operators:
    # Find the class definition
    pattern = rf'(@register_operator\(name="{op_name}".*?\n)(class {class_name}\(SeriesOperator\):\n    """[^"]*""")\n(    def _calculate_series)'

    metadata_str = create_metadata(class_name, op_name, desc, params, param_specs)
    replacement = r'\1\2' + metadata_str + '\n\n\3'

    content = re.sub(pattern, replacement, content, flags=re.DOTALL)

# Write back
with open("/home/shw/quant_projects/factor_engine/cleaned_operators/polars_native/ts_batch1.py", "w") as f:
    f.write(content)

print("Metadata added to all operators in ts_batch1.py")
