# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nAuth.proto\x12\x04LQTP\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"r\n\rLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x1a\n\x12\x65xpires_in_seconds\x18\x03 \x01(\x03\x12\x18\n\x04user\x18\x04 \x01(\x0b\x32\n.LQTP.User\",\n\x13RefreshTokenRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"&\n\rLogoutRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"\x0f\n\rEmptyResponse\"K\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08is_admin\x18\x03 \x01(\x08\x12\x0e\n\x06status\x18\x04 \x01(\t\"I\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x10\n\x08is_admin\x18\x03 \x01(\x08\"W\n\x1cGrantFactorPermissionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x15\n\rdefinition_id\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x63tions\x18\x03 \x03(\t\"X\n\x1dGrantFactorPermissionResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x15\n\rdefinition_id\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x63tions\x18\x03 \x03(\t2\xde\x03\n\x0b\x41uthService\x12\x30\n\x05Login\x12\x12.LQTP.LoginRequest\x1a\x13.LQTP.LoginResponse\x12>\n\x0cRefreshToken\x12\x19.LQTP.RefreshTokenRequest\x1a\x13.LQTP.LoginResponse\x12\x32\n\x06Logout\x12\x13.LQTP.LogoutRequest\x1a\x13.LQTP.EmptyResponse\x12\x31\n\x0eGetCurrentUser\x12\x13.LQTP.EmptyResponse\x1a\n.LQTP.User\x12\x31\n\nCreateUser\x12\x17.LQTP.CreateUserRequest\x1a\n.LQTP.User\x12`\n\x15GrantFactorPermission\x12\".LQTP.GrantFactorPermissionRequest\x1a#.LQTP.GrantFactorPermissionResponse\x12\x61\n\x16RevokeFactorPermission\x12\".LQTP.GrantFactorPermissionRequest\x1a#.LQTP.GrantFactorPermissionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=20
  _globals['_LOGINREQUEST']._serialized_end=70
  _globals['_LOGINRESPONSE']._serialized_start=72
  _globals['_LOGINRESPONSE']._serialized_end=186
  _globals['_REFRESHTOKENREQUEST']._serialized_start=188
  _globals['_REFRESHTOKENREQUEST']._serialized_end=232
  _globals['_LOGOUTREQUEST']._serialized_start=234
  _globals['_LOGOUTREQUEST']._serialized_end=272
  _globals['_EMPTYRESPONSE']._serialized_start=274
  _globals['_EMPTYRESPONSE']._serialized_end=289
  _globals['_USER']._serialized_start=291
  _globals['_USER']._serialized_end=366
  _globals['_CREATEUSERREQUEST']._serialized_start=368
  _globals['_CREATEUSERREQUEST']._serialized_end=441
  _globals['_GRANTFACTORPERMISSIONREQUEST']._serialized_start=443
  _globals['_GRANTFACTORPERMISSIONREQUEST']._serialized_end=530
  _globals['_GRANTFACTORPERMISSIONRESPONSE']._serialized_start=532
  _globals['_GRANTFACTORPERMISSIONRESPONSE']._serialized_end=620
  _globals['_AUTHSERVICE']._serialized_start=623
  _globals['_AUTHSERVICE']._serialized_end=1101
# @@protoc_insertion_point(module_scope)
