#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""详情页「字段与算子释义」补全字典 (2026-08-29)。

扫描 470 个因子的 DSL（/home/sunhaiwei/factor_delivery_converted/formula_lqtp_all.json）
后提取出的全部字段名 + 算子名，与 rebuild_factor_detail_pages.py 内嵌的
FIELD_DOC / OP_DOC 对照，补全缺失登记项。

用法：
    from jobs.field_op_doc import apply_field_op_docs
    apply_field_op_docs(FIELD_DOC, OP_DOC)   # in-place update

约定：
- FIELD_DOC: name -> (中文含义, 一句话说明)
- OP_DOC:    name -> 算子说明
- 基础 OHLCV（open/high/low/close/volume/amount 及其 Adj 前缀别名）统一显示
  "基础行情字段" 简注；衍生字段给出详细解释。
"""

from __future__ import annotations

# ============================================================
# 基础行情字段 (Adj 前缀别名 + 大小写别名统一走此注)
# ============================================================
_BASE_OHLCV_NOTE = "基础行情字段"

FIELD_DOC_BASE = {
    # 标准 OHLCV（覆盖/简化原文件注释，统一为"基础行情字段"）
    "open": ("开盘价", _BASE_OHLCV_NOTE),
    "high": ("最高价", _BASE_OHLCV_NOTE),
    "low": ("最低价", _BASE_OHLCV_NOTE),
    "close": ("收盘价", _BASE_OHLCV_NOTE),
    "volume": ("成交量", _BASE_OHLCV_NOTE),
    "amount": ("成交额", _BASE_OHLCV_NOTE),
    "vwap": ("成交量加权均价", _BASE_OHLCV_NOTE),
    # Adj 前缀别名（后复权调整后行情）
    "AdjOpen": ("后复权开盘价", _BASE_OHLCV_NOTE),
    "AdjHigh": ("后复权最高价", _BASE_OHLCV_NOTE),
    "AdjLow": ("后复权最低价", _BASE_OHLCV_NOTE),
    "AdjClose": ("后复权收盘价", _BASE_OHLCV_NOTE),
    "AdjVolume": ("后复权成交量", _BASE_OHLCV_NOTE),
    "AdjAmount": ("后复权成交额", _BASE_OHLCV_NOTE),
    "adj_open": ("后复权开盘价", _BASE_OHLCV_NOTE),
    "adj_high": ("后复权最高价", _BASE_OHLCV_NOTE),
    "adj_low": ("后复权最低价", _BASE_OHLCV_NOTE),
    "adj_close": ("后复权收盘价", _BASE_OHLCV_NOTE),
    "adj_volume": ("后复权成交量", _BASE_OHLCV_NOTE),
    "adj_amount": ("后复权成交额", _BASE_OHLCV_NOTE),
    # 大小写别名
    "Open": ("开盘价", _BASE_OHLCV_NOTE),
    "High": ("最高价", _BASE_OHLCV_NOTE),
    "Low": ("最低价", _BASE_OHLCV_NOTE),
    "Close": ("收盘价", _BASE_OHLCV_NOTE),
    "Volume": ("成交量", _BASE_OHLCV_NOTE),
    "Amount": ("成交额", _BASE_OHLCV_NOTE),
    "AdjVolume_": ("后复权成交量", _BASE_OHLCV_NOTE),
    "adj_factor": ("复权因子", "后复权调整：复权价 = 未复权价 × adj_factor"),
    "pre_close": ("昨收", "T-1 收盘价；用于计算跳空 / 当日收益"),
    "prev_close": ("昨收 (别名)", "等同 pre_close / ts_delay(close,1)"),
    # 基本面列（LQTP 依赖列常用）
    "pb_lf": ("PB 市净率 (last_filed)", "最新披露市净率 = price / 每股净资产"),
    "debttoassets": ("资产负债率", "总负债 / 总资产"),
    "pe_ttm": ("PE 市盈率 TTM", "滚动 12 个月市盈率 = price / EPS_TTM"),
    "ps_ttm": ("PS 市销率 TTM", "滚动 12 个月市销率 = market_cap / revenue_TTM"),
    "roe_ttm": ("ROE TTM", "净资产收益率（滚动 12 个月）"),
    "roe_ttm2": ("ROE TTM (复权版)", "滚动 12 个月 ROE（当前披露版本）"),
    "roa2_ttm2": ("ROA TTM (复权版)", "滚动 12 个月 ROA"),
    "pcf_ocf_ttm": ("PCF TTM", "市现率（经营现金流口径）"),
    "eps_ttm": ("EPS TTM", "滚动 12 个月每股收益"),
    "free_turn": ("自由换手率", "剔除非流通股本后的换手率"),
    "turnover": ("换手率", "成交量 / 流通股本"),
    "mkt_cap_float": ("流通市值", "close × 流通股本"),
    "free_float_shares": ("流通股本", "剔除限售后的流通股本"),
    "TradingDay": ("交易日", "YYYY-MM-DD 日期"),
    "OrderBookId": ("标的代码", "内部证券唯一 ID"),
    "Symbol": ("股票代码", "外部代码"),
    "TradeDate": ("交易日", "parquet 日期字段"),
    "style_gate_resvol_high": ("高残差波动风格门控", "残差波动高位时触发"),
    "style_gate_size_large": ("大盘风格门控", "大市值时触发"),
    "style_gate_size_small": ("小盘风格门控", "小市值时触发"),
    "style_gate_liquidity_high": ("高流动性风格门控", "流动性高位时触发"),
    "style_gate_momentum_high": ("高动量风格门控", "动量高位时触发"),
    "qfa_yoygr": ("季度同比增速", "单季度财务同比增速"),
    "forecast_incap_chgr_mid": ("盈利预测修正", "分析师盈利预测变化（中等口径）"),
    "close_price": ("收盘价 (别名)", "等同 close；不同源可能列名不同"),
    "high_resvol": ("高残差波动期 (别名)", "resvol_high 的别名"),
}

# ============================================================
# 衍生字段（DSL 中间变量 / 语义字段）
# ============================================================
FIELD_DOC_EXTRA = {
    # ---- 成交量 / 量能 ----
    "vol": ("成交量 (简称)", "volume 的 DSL 简写；部分公式用 vol 指代成交量"),
    "V": ("成交量 (简称)", "volume 的 DSL 大写简写；如 V/MA20(V) 表示量比"),
    "vol_ratio": ("量比", "volume / ts_mean(volume, N)，>1 放量，<1 缩量"),
    "vol_rank": ("量能截面排名", "当日成交量在截面上的百分位排名"),
    "vol_trend": ("量能趋势", "volume / ts_mean(volume, N) 类长期量比；衡量放量趋势"),
    "vol_dev": ("量能偏离度", "成交量相对其均值的标准化偏离"),
    "vol_z": ("量能 Z-Score", "成交量 z-score 标准化（偏离均值的标准差倍数）"),
    "vol_z20": ("20 日量能 Z-Score", "近 20 日成交量 z-score"),
    "vol_20": ("20 日量能均值", "ts_mean(volume, 20)"),
    "vol_20_avg": ("20 日量能均值", "ts_mean(volume, 20)"),
    "vol_gate": ("量能门控", "以成交量条件作为开关的因子门控系数"),
    "vol_weight": ("量能权重", "以成交量比例构造的加权系数"),
    "vol_asym": ("量能不对称", "上行量 / 下行量等量能方向不对称度量"),
    "vol_ma": ("量能均线", "成交量的滚动均线（窗口由参数决定）"),
    "vol_ma20": ("20 日均量", "ts_mean(volume, 20)"),
    "vol_ma40": ("40 日均量", "ts_mean(volume, 40)"),
    "vol_ma60": ("60 日均量", "ts_mean(volume, 60)"),
    "vol_ma5": ("5 日均量", "ts_mean(volume, 5)"),
    "vol_ma_10": ("10 日均量", "ts_mean(volume, 10)"),
    "vol_ma_20": ("20 日均量", "ts_mean(volume, 20)"),
    "volume_ma20": ("20 日均量", "ts_mean(volume, 20)"),
    "ma_volume_20": ("20 日均量", "ts_mean(volume, 20)"),
    "ma_vol21": ("21 日均量", "ts_mean(volume, 21)"),
    "vol_ema": ("量能 EMA", "成交量的指数加权移动平均"),
    "vol_median": ("量能中位数", "成交量的滚动中位数"),
    "med_vol": ("量能中位数", "成交量的滚动中位数"),
    "med_vol_20": ("20 日量能中位数", "近 20 日成交量中位数"),
    "med_vol_60": ("60 日量能中位数", "近 60 日成交量中位数"),
    "med_volume": ("量能中位数", "成交量的滚动中位数"),
    "vol20": ("20 日量能", "近 20 日成交量（或其均值）"),
    "vol_ratio_20": ("20 日量比", "volume / ts_mean(volume, 20)"),
    "vol_ratio_10": ("10 日量比", "volume / ts_mean(volume, 10)"),
    "vol_ratio_risk_10": ("10 日量比（风险版）", "近 10 日量比，用于波动风险过滤"),
    "vol_chg": ("量能变化", "成交量的环比变化率"),
    "vol_pct": ("量能变化率", "成交量的百分比变化"),
    "vol_i": ("第 i 日成交量", "求和式中第 i 个交易日的成交量"),
    "volume_i": ("第 i 日成交量", "求和式中第 i 个交易日的成交量"),
    "vol_down": ("下行量", "下跌日（close<open）的成交量"),
    "vol_up": ("上行量", "上涨日（close>=open）的成交量"),
    "down_vol": ("下行量/下行波动", "下跌日成交量，或下行波动率（按上下文）"),
    "up_vol": ("上行量/上行波动", "上涨日成交量，或上行波动率（按上下文）"),
    "vol_down_sum_40": ("40 日下行量", "近 40 日下跌日成交量之和"),
    "up_vol_sum_40": ("40 日上行量", "近 40 日上涨日成交量之和"),
    "down_vol_sum_40": ("40 日下行量", "近 40 日下跌日成交量之和"),
    "dollar_volume": ("成交额", "price × volume；衡量资金参与规模"),
    "dollar": ("成交额", "price × volume 的简称"),
    "close_vol": ("收盘量", "与收盘价对应的成交量（上下文相关）"),
    "high_volume": ("高量能标志", "成交量高于阈值/均线的状态标志"),
    "med_volume": ("量能中位数", "成交量的滚动中位数"),
    "Volume_Ratio": ("量比", "Volume / ts_mean(Volume, N) 的 DSL 名称"),
    "volume_momentum": ("量能动量", "成交量的动量/变化率"),
    "vol_ma20_lag": ("20 日均量滞后", "ts_delay(vol_ma20, k)；用于构造延迟量能信号"),
    "vol_lag": ("滞后量能", "滞后 k 期的成交量"),
    "vol_ratio_EMA": ("量比 EMA", "对量比做指数加权移动平均"),
    "volume_ratio": ("量比", "volume / 均量"),
    "rolling_20d_mean_volume": ("20 日均量", "近 20 日成交量的滚动均值"),
    "median_vol": ("量能中位数", "成交量的滚动中位数"),
    "med_volume_": ("量能中位数", "成交量的滚动中位数"),
    # ---- 收益 / 动量 ----
    "ret": ("日收益", "(close - ts_delay(close,1)) / ts_delay(close,1)"),
    "returns": ("收益序列", "收益率序列（ret 或 ret_N）的统称"),
    "neg_ret": ("负收益", "当日收益的负值部分（ret<0 时取 |ret|）"),
    "pos_ret": ("正收益", "当日收益的正值部分（ret>0 时取 ret）"),
    "neg_returns": ("负收益序列", "min(ret, 0)；只取收益 ≤ 0 部分"),
    "pos_returns": ("正收益序列", "max(ret, 0)；只取收益 ≥ 0 部分"),
    "downside_returns": ("下行收益", "neg_returns 的别名"),
    "upside_returns": ("上行收益", "pos_returns 的别名"),
    "positive_returns": ("正收益序列", "max(ret, 0) 的别名"),
    "negative_returns": ("负收益序列", "min(ret, 0) 的别名"),
    "close_return": ("收盘收益", "基于 close 计算的收益（单期或多期）"),
    "close_ret": ("收盘收益", "基于 close 计算的收益"),
    "close_10d_return": ("10 日收盘收益", "(close - ts_delay(close,10)) / ts_delay(close,10)"),
    "close_10d_chg": ("10 日收盘变化", "近 10 日收盘价变化率"),
    "ret_5d": ("5 日收益", "(close - ts_delay(close,5)) / ts_delay(close,5)"),
    "ret_1d": ("1 日收益", "(close - ts_delay(close,1)) / ts_delay(close,1)"),
    "ret_10": ("10 日收益", "(close - ts_delay(close,10)) / ts_delay(close,10)"),
    "ret_daily": ("日收益", "每日收益率的统称"),
    "daily_ret": ("日收益", "每日收益率"),
    "daily_return": ("日收益", "每日收益率"),
    "DailyReturn": ("日收益", "每日收益率"),
    "pct_return": ("百分比收益", "以百分比计的收益率"),
    "pct_return_5": ("5 日百分比收益", "近 5 日百分比收益率"),
    "price_ret_5": ("5 日价格收益", "近 5 日价格收益率"),
    "pct_change": ("百分比变化", "x[t]/x[t-n] - 1 的收益率变化"),
    "close_pct_change": ("收盘价百分比变化", "收盘价的环比百分比变化"),
    "pct_vol_change": ("量能百分比变化", "成交量的环比百分比变化"),
    "log_return": ("对数收益", "log(close / ts_delay(close,1))"),
    "lag_ret": ("滞后收益", "ts_delay(ret, k) 的简称；用历史收益"),
    "lag_ret_5": ("5 日滞后收益", "ts_delay(ret, 5)"),
    "mom": ("动量", "过去 N 日收益率的统称"),
    "momentum": ("动量", "过去 N 日收益率"),
    "close_5d_ago": ("5 日前收盘", "ts_delay(close, 5)"),
    "close_10": ("10 日前收盘", "ts_delay(close, 10)"),
    "intraday_ret": ("日内收益", "vwap/close 与 open 之间的日内收益（close/open - 1 类）"),
    "intraday_return": ("日内收益", "日内收益率的统称"),
    "overnight_ret": ("隔夜收益", "(open - ts_delay(close,1)) / ts_delay(close,1)"),
    "overnight_return": ("隔夜收益", "open 相对昨收的收益"),
    "overnight_downside": ("隔夜下行", "隔夜收益的负值部分"),
    "intraday_downside": ("日内下行", "日内收益的负值部分"),
    "downside_open_low": ("开盘至最低下行", "open 到 low 的下行幅度"),
    "upside_high_open": ("最高至开盘上行", "high 到 open 的上行幅度"),
    "ret_1d": ("1 日收益", "当日收益"),
    "close_ret": ("收盘收益", "基于收盘价的收益"),
    "avg_abs_ret": ("平均绝对收益", "绝对收益率的滚动均值"),
    "impulse_lag": ("冲击滞后", "滞后量能冲击项（vol_lag / vol_ma20_lag - 1 类）"),
    "daily_drift": ("日漂移", "单日收益/漂移项"),
    "short_drift": ("短期漂移", "短窗口漂移累计（如 5 日）"),
    "long_drift": ("长期漂移", "长窗口漂移累计（如 15 日）"),
    "drift": ("漂移", "收益漂移/趋势项"),
    "short_drift_t": ("第 t 日短期漂移", "漂移公式中的短期项"),
    "long_drift_t": ("第 t 日长期漂移", "漂移公式中的长期项"),
    "drift_t": ("第 t 日漂移", "漂移公式中的日度项"),
    "delta": ("差分", "x[t] - x[t-n]（n 期差分）"),
    "Delta": ("差分", "x[t] - x[t-n]（n 期差分）"),
    "lagged": ("滞后", "滞后若干期的值"),
    "lag": ("滞后", "滞后若干期的算子/值"),
    "lag4": ("4 期滞后", "ts_delay(x, 4)"),
    "shift5": ("5 期移位", "ts_delay(x, 5)"),
    "shift1": ("1 期移位", "ts_delay(x, 1)"),
    "shift10": ("10 期移位", "ts_delay(x, 10)"),
    "trend": ("趋势", "中长期价格趋势项"),
    "short_trend": ("短期趋势", "短窗口趋势（如 20/40 日均线比）"),
    "long_trend": ("长期趋势", "长窗口趋势（如 20/80 日均线比）"),
    "momentum": ("动量", "过去 N 日收益率"),
    "reversion": ("反转", "均值回归信号"),
    "synergy": ("协同", "多信号协同项"),
    "symmetry": ("对称性", "(upper_shadow - lower_shadow)/(upper_shadow + lower_shadow) 类对称度量"),
    "sym_z": ("对称性 Z-Score", "对称性指标的 z-score"),
    "range_ratio_z": ("振幅比 Z-Score", "range_ratio 的 z-score"),
    # ---- 波动 / 振幅 ----
    "range": ("振幅", "high - low；当日价格区间"),
    "range_pct": ("日内振幅率", "(high - low) / close"),
    "range_ratio": ("振幅比", "(high-low)/close 或两段振幅之比"),
    "norm_range": ("归一化振幅", "(high - low) / close 的归一化"),
    "norm_pressure": ("归一化压力", "价格区间归一化后的压力项"),
    "smoothed_range": ("平滑振幅", "经 ewm/rolling 平滑的振幅"),
    "range10": ("10 日振幅", "近 10 日振幅（或其均值）"),
    "range20": ("20 日振幅", "近 20 日振幅（或其均值）"),
    "range60": ("60 日振幅", "近 60 日振幅（或其均值）"),
    "range_ratio": ("振幅比", "(high-low)/close"),
    "true_range": ("真实波幅", "max(high-low, |high-prev_close|, |low-prev_close|)"),
    "TR": ("真实波幅", "true_range 的简称"),
    "tr": ("真实波幅", "true_range 的简称"),
    "total_range": ("总振幅", "上行区间 + 下行区间（总波动区间）"),
    "up_range": ("上行区间", "high - max(open, close) 类上行幅度"),
    "down_range": ("下行区间", "min(open, close) - low 类下行幅度"),
    "avg_up_range": ("平均上行区间", "近 N 日上行区间的均值"),
    "avg_down_range": ("平均下行区间", "近 N 日下行区间的均值"),
    "up_ret": ("上行收益", "正收益部分"),
    "down_ret": ("下行收益", "负收益部分"),
    "down_avg": ("平均下行量/区间", "下行方向的均值"),
    "up_avg": ("平均上行量/区间", "上行方向的均值"),
    "up_squared_return": ("上行收益平方", "正收益的平方（上行波动项）"),
    "down_squared_return": ("下行收益平方", "负收益的平方（下行波动项）"),
    "volatility": ("波动率", "收益率的标准差（年化）"),
    "vol_vol": ("波动率的波动", "波动率的波动率"),
    "volatility_ratio": ("波动率比", "两段波动率之比"),
    "close_std": ("收盘价标准差", "收盘价的滚动标准差"),
    "std_20": ("20 日标准差", "近 20 日滚动标准差"),
    "daily_std": ("日度标准差", "日度数据的标准差"),
    "daily_mean": ("日度均值", "日度数据的均值"),
    "daily_skew": ("日度偏度", "日度数据的偏度"),
    "daily_kurt": ("日度峰度", "日度数据的峰度"),
    "std_imbalance": ("失衡标准差", "订单失衡序列的标准差"),
    "neg_std": ("负收益标准差", "负收益序列的标准差"),
    "pos_std": ("正收益标准差", "正收益序列的标准差"),
    "downside_ratio": ("下行比率", "下行风险 / 上行弹性类比率"),
    "downside_stress_ratio": ("下行压力比率", "下行压力度量比率"),
    "upside_vol": ("上行波动率", "正收益序列的波动率"),
    "downside_vol": ("下行波动率", "负收益序列的波动率"),
    "downside_volatility": ("下行波动率", "负收益序列的波动率"),
    "down_vol_60": ("60 日下行波动", "近 60 日负收益波动率"),
    "up_vol_60": ("60 日上行波动", "近 60 日正收益波动率"),
    "down_vol_sum_40": ("40 日下行量", "近 40 日下跌量累计"),
    "atr": ("ATR", "平均真实波幅；ts_atr(high,low,close,n)"),
    "ATR_20d": ("20 日 ATR", "近 20 日平均真实波幅"),
    "ATR_14": ("14 日 ATR", "近 14 日平均真实波幅"),
    "ATR_EMA90": ("ATR 与 EMA90 组合", "ATR 经 EMA90 平滑的组合项"),
    "exp_ratio": ("指数比", "指数加权均值的比值"),
    "roughness": ("粗糙度", "序列不规则性/粗糙度度量"),
    # ---- 回撤 / 深度 ----
    "drawdown": ("回撤", "(close - ts_max(close,N)) / ts_max(close,N)"),
    "drawdown_depth": ("回撤深度", "距前期高点的回撤幅度"),
    "drawdown_depth_50": ("50% 回撤深度", "回撤深度达到 50% 级别的度量"),
    "drawdown_depth_60": ("60% 回撤深度", "回撤深度达到 60% 级别的度量"),
    "drawdown_depth_20": ("20 日回撤深度", "近 20 日回撤深度"),
    "drawdown_duration": ("回撤持续期", "自高点回撤持续的交易日数"),
    "duration": ("回撤持续天数", "自 N 日高点的天数"),
    "duration_20": ("20 日回撤持续期", "近 20 日回撤持续天数"),
    "depth": ("回撤深度", "rolling_max(close,N) - close 归一化"),
    "depth_20": ("20 日回撤深度", "近 20 日回撤深度"),
    "normalized_drawdown": ("归一化回撤", "回撤 / ATR 等风险尺度归一化"),
    "drawdown_indicator": ("回撤标志", "处于回撤状态时为 1"),
    "drawdown40d": ("40 日回撤", "近 40 日回撤"),
    "drawdown_recovery_roughness": ("回撤恢复粗糙度", "回撤后恢复过程的不规则性"),
    "DD_60d": ("60 日回撤", "近 60 日回撤"),
    "cumulative_max_drawdown_sum_60d": ("60 日累计最大回撤", "近 60 日最大回撤累计"),
    "rolling_max_drawdown_sum_60d": ("60 日滚动最大回撤", "近 60 日滚动最大回撤累计"),
    "DD": ("回撤", "drawdown 的简称"),
    "Dur": ("回撤持续期", "drawdown duration 的简称"),
    "Rec": ("回撤恢复", "drawdown recovery 的简称"),
    "recovery": ("恢复强度", "回撤后反弹/跌幅"),
    "drawdown_recovery": ("回撤恢复", "回撤后恢复幅度"),
    "MA20_V": ("20 日均量 (V 版)", "V/MA20(V) 中的 20 日均量"),
    "drawdown_vol": ("回撤波动", "回撤序列的波动率"),
    "tail_fragility_20": ("20 日尾部脆弱性", "基于尾部事件的脆弱度度量"),
    "lower_wick": ("下影线", "min(open,close) - low"),
    "lower_wick_fraction": ("下影线占比", "下影线 / 振幅（相对下影线比例）"),
    "upper_shadow": ("上影线", "high - max(open,close)"),
    "lower_shadow": ("下影线", "min(open,close) - low"),
    "close_loc": ("收盘位置", "(close - low) / (high - low)"),
    "close_location": ("收盘位置", "(close - low) / (high - low)"),
    "close_loc_": ("收盘位置", "(close - low) / (high - low)"),
    # ---- 突破 / 极值 ----
    "prior_high": ("前期高点", "过去 N 日最高价（滞后一期防未来）"),
    "prior_high5": ("5 日前期高点", "ts_delay(ts_max(high,5),1) 类前期高点"),
    "prior_high20_": ("20 日前期高点", "近 20 日前期高点"),
    "prior_high_": ("前期高点", "过去 N 日最高价的统称"),
    "Low30_lagged": ("30 日低点滞后", "ts_delay(ts_min(low,30),1) 类前期低点"),
    "breakout": ("突破标志", "价格突破前期高点/低点的事件标志"),
    "H20_shift": ("20 日高点移位", "ts_delay(ts_max(high,20),1) 类"),
    "high_t": ("第 t 日最高价", "公式中第 t 期 high"),
    "low_t": ("第 t 日最低价", "公式中第 t 期 low"),
    "close_t": ("第 t 日收盘价", "公式中第 t 期 close"),
    "recent": ("近期", "近期窗口（相对 recent breakout 等事件的修饰）"),
    "close_5d_ago": ("5 日前收盘", "ts_delay(close,5)"),
    "high_momentum": ("高位动量", "接近前期高点时的动量项"),
    "trailing_max": ("滚动最大值", "rolling_max 的简称；常与窗口参数连用"),
    "trailing": ("滚动/尾随", "trailing 窗口（如 trailing_max/trailing_vol）"),
    "trailing_vol": ("滚动波动率", "trailing 窗口波动率（如近 20 日收益波动）"),
    "regime_adaptive_trailing_high": ("状态自适应前期高点", "按波动状态切换窗口的前期高点"),
    "resvol": ("残差波动", "残差波动率"),
    "resvol_high": ("高残差波动标志", "残差波动处于高位时为 True"),
    "resvol_low": ("低残差波动标志", "残差波动处于低位时为 True"),
    "low_volume_regime": ("低量能状态", "成交量处于低位区间的状态标志"),
    "volume_regime": ("量能状态", "成交量状态（高/中/低）"),
    "high_volume": ("高量能", "成交量处于高位状态"),
    "defined_high_volume": ("定义的高量能", "按规则定义的高量能状态"),
    "transition": ("状态转换", "状态切换事件"),
    "transition_into_high_volume": ("转入高量能", "从低量能转入高量能的事件"),
    "transition_into_EMA": ("EMA 状态转换", "进入 EMA 定义状态的转换"),
    "regime": ("状态", "量能/波动等状态变量"),
    "gate": ("门控", "条件开关"),
    "vol_gate": ("量能门控", "以量能条件做开关"),
    "style_gate_resvol_high": ("高残差波动风格门控", "残差波动高位时触发"),
    "style_gate_liquidity_high": ("高流动性风格门控", "流动性高位时触发"),
    "style_gate_size_large": ("大盘风格门控", "大市值时触发"),
    "style_gate_size_small": ("小盘风格门控", "小市值时触发"),
    "style_gate_momentum_high": ("高动量风格门控", "动量高位时触发"),
    "liquidity_high": ("高流动性标志", "amount/turnover 高位分类"),
    "classify_volume_regime_multiplier": ("量能分类乘数", "classify_volume_regime 输出的乘数"),
    # ---- 估值 / 基本面 ----
    "book_yield": ("账面收益率", "1 / pb_lf（市净率的倒数）"),
    "book_yield_smoothed": ("平滑账面收益率", "对 1/pb_lf 做平滑"),
    "smooth_book_yield": ("平滑账面收益率", "ts_mean/ewm 平滑的 1/pb_lf"),
    "cheapness": ("便宜度", "1/pe_ttm 或 1/pb_lf 类估值便宜度"),
    "PB_cheapness": ("PB 便宜度", "基于 PB 的便宜度度量"),
    "pb_pos": ("正 PB", "PB 为正的部分"),
    "pb": ("市净率", "price / 每股净资产"),
    "pe": ("市盈率", "price / EPS"),
    "PB": ("市净率", "price / 每股净资产"),
    "PE": ("市盈率", "price / EPS"),
    "growth_adjusted_ey": ("增长调整盈利收益率", "盈利收益率经增长调整"),
    "roe_ttm2": ("ROE TTM (复权版)", "滚动 12 个月 ROE（当前披露版本）"),
    "roa2_ttm2": ("ROA TTM (复权版)", "滚动 12 个月 ROA"),
    "roa_conf": ("ROA 置信项", "(1 + roa2_ttm2/100) clipped 的置信项"),
    "roa": ("ROA", "总资产收益率"),
    "roe": ("ROE", "净资产收益率"),
    "pcf_ocf_ttm": ("PCF 经营现金流 TTM", "市现率（经营现金流口径）"),
    "leverage_adj": ("杠杆调整", "(1 - debt_ratio) 裁剪的杠杆调整系数"),
    "debt_ratio": ("负债率", "总负债 / 总资产"),
    "debt": ("负债", "总负债"),
    "assets": ("资产", "总资产"),
    "qfa_yoygr": ("季度同比增速", "单季度财务同比增速"),
    "forecast_incap_chgr_mid": ("盈利预测修正", "分析师盈利预测变化（中等口径）"),
    "exp_ratio": ("费用率", "费用 / 营收类比率"),
    "free_float_shares": ("流通股本", "剔除限售后的流通股本"),
    "mkt_cap_float": ("流通市值", "close × 流通股本"),
    "log_size": ("对数市值", "log(市值)"),
    "size_dev": ("市值偏离", "log(mkt_cap_float) 相对其均值的偏离"),
    "size_rank": ("市值排名", "市值截面排名"),
    "size_z": ("市值 Z-Score", "市值 z-score"),
    "size_w": ("市值权重", "基于市值排名的权重"),
    "size_weight": ("市值权重", "基于市值构造的权重"),
    "size_small": ("小盘", "小市值状态"),
    "size_large": ("大盘", "大市值状态"),
    "small_signal": ("小盘信号", "小市值条件下计算的信号"),
    "large_signal": ("大盘信号", "大市值条件下计算的信号"),
    "large_val": ("大市值值", "大市值分支的值"),
    "small_cap": ("小盘", "小市值状态"),
    "large_cap": ("大盘", "大市值状态"),
    "size_trend_value": ("市值趋势价值", "市值趋势与价值结合的因子"),
    "size_gated_value_leverage": ("市值门控价值杠杆", "按市值门控的价值杠杆因子"),
    "value_quality_growth_sales_yield": ("价值质量成长销售收益率", "综合价值质量成长因子"),
    "midpoint": ("中间价", "(high + low) / 2"),
    "health": ("基本面健康度", "财务健康综合度量"),
    # ---- 订单流 / 结构 ----
    "imbalance": ("订单失衡", "(volume_up - volume_down) / (volume_up + volume_down) 类"),
    "flow": ("资金流", "imbalance × volume"),
    "CLV": ("收盘位置值", "(2*close - high - low) / (high - low)"),
    "CLV_i": ("第 i 日 CLV", "求和式中第 i 日的收盘位置值"),
    "OI": ("订单失衡累计", "CLV × volume 的累计"),
    "OI_10": ("10 日订单失衡累计", "近 10 日 CLV × volume 累计"),
    "ema_imbalance": ("EMA 订单失衡", "订单失衡的指数加权平均"),
    "net_dir": ("净方向", "买卖净方向"),
    "price_impact": ("价格冲击", "成交量对价格的冲击"),
    "impact": ("冲击", "价格冲击项"),
    "impact_efficiency": ("冲击效率", "冲击项的效率度量"),
    "directional_efficiency": ("方向效率", "价格方向运动效率"),
    "herding": ("羊群效应", "交易羊群行为度量"),
    "occupancy": ("驻留度", "价格在区间内驻留的比例"),
    "participation": ("参与度", "成交量占流通盘的比例"),
    "dampener": ("阻尼系数", "对信号的衰减/阻尼项"),
    "modifier": ("修正项", "对信号的修正系数"),
    "multiplied": ("乘数", "相乘的调节项"),
    "amplification": ("放大系数", "对信号的放大项"),
    "drag": ("拖拽项", "对信号的抑制项"),
    "premium": ("溢价项", "下行冲击溢价的累计项"),
    "stress": ("压力", "回撤/下行压力项"),
    "stress_fast": ("快速压力", "短窗口压力项"),
    "stress_slow": ("慢速压力", "长窗口压力项"),
    "stress_ratio": ("压力比率", "压力度量的比率"),
    "downside_damage_12": ("12 日下行损伤", "近 12 日下行损伤项"),
    "downside_energy": ("下行能量", "下行收益的平方能量"),
    "downside_energy_share_20": ("20 日下行能量占比", "近 20 日下行能量占比"),
    "downside_energy_share_30": ("30 日下行能量占比", "近 30 日下行能量占比"),
    "overnight_downside_energy_share": ("隔夜下行能量占比", "隔夜下行能量占比"),
    "excursion": ("偏离", "价格相对某基准的偏离幅度"),
    "excursion_squared": ("偏离平方", "偏离幅度的平方"),
    "squared_excursion": ("偏离平方", "偏离幅度的平方"),
    "shock": ("冲击事件", "收益跌破阈值的事件标志（如 ret < -0.02）"),
    "outlier": ("异常值", "极端异常观测"),
    "holding": ("持有", "持有状态"),
    "hold_persistence": ("持有持续", "突破后持有/持续强度"),
    "persistence": ("持续性", "信号的持续性度量"),
    "consensus": ("共识度", "多信号一致性度量"),
    "smooth_corr": ("平滑相关", "经 ewm 平滑的相关系数"),
    "corr": ("相关系数", "Pearson 相关"),
    "rank_corr": ("秩相关", "Spearman 秩相关"),
    "daily_corr": ("日度相关", "日度数据计算的相关系数"),
    "rolling_corr": ("滚动相关", "滚动窗口相关系数"),
    "rolling_20_corr": ("20 日滚动相关", "近 20 日滚动相关系数"),
    "Corr20": ("20 日相关", "近 20 日相关系数"),
    "ROC20": ("20 日变动率", "近 20 日变动率指标"),
    "ROC5": ("5 日变动率", "近 5 日变动率指标"),
    "roc40": ("40 日变动率", "近 40 日变动率"),
    "roc10": ("10 日变动率", "近 10 日变动率"),
    "blend": ("混合系数", "多信号融合的混合权重"),
    "asym_ratio": ("不对称比", "上行/下行不对称比率"),
    "asymmetry": ("不对称性", "上行/下行不对称度量"),
    "downside": ("下行", "下行方向的统称"),
    "upside": ("上行", "上行方向的统称"),
    "down": ("下行", "下行方向的统称"),
    "up": ("上行", "上行方向的统称"),
    "composite": ("复合项", "多成分复合信号"),
    "base_factor": ("基础因子", "复合因子的基础成分"),
    "scaled_rank": ("缩放排名", "(rank - 0.5) * 2 类缩放排名"),
    "rank_p": ("排名百分位", "截面排名百分位"),
    "rank_": ("排名", "排名统称"),
    "rank": ("排名", "截面排名"),
    "percentile_rank": ("百分位排名", "截面百分位排名"),
    "smoothed": ("平滑值", "经 ewm/rolling 平滑的信号"),
    "smoothed_range": ("平滑振幅", "平滑后的振幅"),
    "raw": ("原始信号", "未平滑/未标准化的因子值"),
    "signal": ("信号", "中间合成信号"),
    "normalized": ("归一化值", "标准化到 0~1 或 -1~1"),
    "adjusted_ratio": ("调整比率", "经调整的比率项"),
    "weight": ("权重", "加权系数"),
    "weight_long": ("长期权重", "长期信号的权重（1-weight_long 给短期）"),
    "change": ("变化", "变化量/变化率统称"),
    "direction": ("方向", "趋势/收益方向"),
    "trend": ("趋势", "趋势项"),
    "rev": ("反转", "反转信号"),
    "stretch": ("拉伸项", "突破强度拉伸项"),
    "efficiency": ("效率", "趋势效率度量"),
    "reduce": ("衰减", "对信号的衰减"),
    "forward": ("前向", "前向（未来）项"),
    "positive": ("正值", "正值部分"),
    "negative": ("负值", "负值部分"),
    "magnitude": ("幅度", "信号幅度"),
    "price": ("价格", "价格统称"),
    "price_amp": ("价格振幅", "价格振幅项"),
    "close_vol": ("收盘量", "收盘对应的量"),
    "close_5d_ago": ("5 日前收盘", "ts_delay(close,5)"),
    "close_10": ("10 日前收盘", "ts_delay(close,10)"),
    "vwap_deviation": ("VWAP 偏离", "close / vwap - 1 类"),
    "vwap_squared_deviation_intensity": ("VWAP 偏离平方强度", "VWAP 偏离平方的强度"),
    "vwap_deviation_intensity_squared_amount_weighted": ("VWAP 偏离平方金额加权", "按成交额加权的 VWAP 偏离平方强度"),
    "rolling_vwap": ("滚动 VWAP", "滚动窗口成交量加权均价"),
    "daily_last": ("日末值", "每日最后一个值"),
    "C": ("收盘价 (简称)", "close 的 DSL 简写"),
    "C_": ("收盘价 (下标)", "公式下标中的收盘价"),
    "C_t": ("第 t 日收盘", "公式中第 t 期 close"),
    "O": ("开盘价 (简称)", "open 的 DSL 简写"),
    "H": ("最高价 (简称)", "high 的 DSL 简写"),
    "L": ("最低价 (简称)", "low 的 DSL 简写"),
    "B": ("前期高点 (简称)", "公式中突破基准（前期高点）"),
    "I": ("指示函数", "条件为真时为 1 的指示变量"),
    "S": ("信号 (简称)", "公式中中间信号"),
    "E": ("期望/均值 (简称)", "均值或期望的简写"),
    "F": ("事件标志 (简称)", "事件指示标志"),
    "R": ("前期高点 (简称)", "公式中作为参考的前期高点"),
    "Z": ("Z-Score (简称)", "标准化得分的简写"),
    "close_loc": ("收盘位置", "(close-low)/(high-low)"),
    "E_t": ("第 t 期均值", "公式中第 t 期均值项"),
    "w_t": ("第 t 期权重", "公式中第 t 期权重"),
    "volume_ma20": ("20 日均量", "ts_mean(volume,20)"),
    "MA20_V": ("20 日均量 (V)", "V/MA20(V) 中的 20 日均量"),
    "avg_abs_ret": ("平均绝对收益", "绝对收益的滚动均值"),
    "mean_16": ("16 日均值", "ts_mean(x,16)"),
    "mean_12": ("12 日均值", "ts_mean(x,12)"),
    "mean_10": ("10 日均值", "ts_mean(x,10)"),
    "mean_5": ("5 日均值", "ts_mean(x,5)"),
    "mean20": ("20 日均值", "ts_mean(x,20)"),
    "max20": ("20 日最大值", "ts_max(x,20)"),
    "max_20": ("20 日最大值", "ts_max(x,20)"),
    "max_10": ("10 日最大值", "ts_max(x,10)"),
    "max_": ("最大值", "最大值的统称"),
    "median_20": ("20 日中位数", "ts_median(x,20)"),
    "sum_20": ("20 日求和", "ts_sum(x,20)"),
    "sum_": ("求和", "ts_sum 的统称"),
    "ts_rank_": ("滚动排名", "ts_rank 的统称"),
    "rolling_mean_": ("滚动均值", "rolling mean 的统称"),
    "rolling_mean_20": ("20 日滚动均值", "近 20 日滚动均值"),
    "rolling_std_20": ("20 日滚动标准差", "近 20 日滚动标准差"),
    "rollingmean": ("滚动均值", "rolling mean 的统称"),
    "EWMA_24": ("24 日 EWMA", "span=24 的指数加权移动平均"),
    "EWMA_30": ("30 日 EWMA", "span=30 的指数加权移动平均"),
    "EWMA_45": ("45 日 EWMA", "span=45 的指数加权移动平均"),
    "EWMA_up_vol": ("上行量 EWMA", "上涨日成交量的 EWMA"),
    "EWMA_down_vol": ("下行量 EWMA", "下跌日成交量的 EWMA"),
    "EWM": ("EWM", "指数加权（pandas ewm 简称）"),
    "EMA_": ("EMA", "指数均线的简写"),
    "EWM_std": ("EWM 标准差", "指数加权标准差"),
    "EMA_volume": ("量能 EMA", "成交量的指数移动平均"),
    "RollingStd60": ("60 日滚动标准差", "近 60 日滚动标准差"),
    "Var_60": ("60 日方差", "近 60 日方差"),
    "Var_40": ("40 日方差", "近 40 日方差"),
    "Cov_60": ("60 日协方差", "近 60 日协方差"),
    "Cov_40": ("40 日协方差", "近 40 日协方差"),
    "rolling_mean": ("滚动均值", "rolling mean"),
    "rolling_std": ("滚动标准差", "rolling std"),
    "rolling_skew": ("滚动偏度", "rolling skew"),
    "rolling_zscore": ("滚动 Z-Score", "rolling z-score"),
    "rolling_max": ("滚动最大值", "rolling max"),
    "cummax": ("累计最大值", "cumulative max"),
    "Robust_z": ("稳健 Z-Score", "基于中位数/MAD 的稳健标准化"),
    "robust_z": ("稳健 Z-Score", "基于中位数/MAD 的稳健标准化"),
    "Rng": ("振幅", "high - low 的 DSL 简写"),
    "skew": ("偏度", "收益率的偏度"),
    "signed": ("带符号", "带符号的取值"),
    "capped": ("裁剪", "clip 的形容词形式"),
    "clipped": ("裁剪", "clip 后的取值"),
    "filled": ("填充", "填充后的值"),
    "IC": ("信息系数", "因子与收益的相关性"),
    "delta_depth_10": ("回撤深度变化 (10 日)", "depth[t] - depth[t-10]"),
    "median": ("中位数", "中位数统称"),
    "median_vol": ("量能中位数", "成交量中位数"),
    "daily_ret": ("日收益", "日收益统称"),
    "close_10d_return": ("10 日收盘收益", "近 10 日收盘收益"),
    "close_10d_chg": ("10 日收盘变化率", "近 10 日收盘变化率"),
    "close_pct_change": ("收盘变化率", "收盘价的百分比变化"),
    "price_amp": ("价格振幅", "价格振幅"),
    "vol_dev": ("量能偏离", "成交量偏离均值的程度"),
    "smoothed": ("平滑值", "平滑后的信号"),
    "volatility": ("波动率", "年化波动率"),
    "momentum": ("动量", "动量统称"),
    "gap": ("跳空", "开盘跳空"),
    "open_gap": ("开盘跳空", "open 相对昨收的跳空"),
    "close_gap": ("收盘跳空", "close 相对昨收的跳空"),
    "typical_price": ("典型价", "(high + low + close) / 3"),
    "adj": ("复权", "复权调整的简称"),
    "skew_weighted_volume_event_intensity": ("偏度加权量事件强度", "以偏度加权的成交量事件强度"),
    "skew_weighted_volume_event_intensity_close": ("偏度加权量事件强度 (收盘)", "以偏度加权的量事件强度（收盘口径）"),
    "short_ma_abs_log_ret": ("短期均线绝对对数收益", "短窗口 |log return| 均值"),
    "long_ma_abs_log_ret": ("长期均线绝对对数收益", "长窗口 |log return| 均值"),
    "roughness": ("粗糙度", "序列粗糙度度量"),
    "Roughness_Ratio": ("粗糙度比", "粗糙度比率"),
    "halve": ("减半", "减半系数"),
    "ifnan": ("NaN 处理", "NaN 时返回指定值"),
    "winsorize": ("缩尾", "极值缩尾处理"),
    "rank_trailing": ("尾随排名", "trailing 窗口排名"),
    "close_ret": ("收盘收益", "收盘收益"),
    "base_factor": ("基础因子", "复合因子基础成分"),
    "factor": ("因子输出", "公式最终输出的因子值"),
    "Factor": ("因子输出", "公式最终输出的因子值"),
    "output": ("输出", "中间输出"),
    "score": ("评分", "中间评分信号"),
    "score_": ("评分", "中间评分"),
    "depth_score": ("回撤深度评分", "回撤深度综合评分"),
    "duration": ("持续期", "持续时间"),
    "intensity": ("强度", "信号强度"),
    "magnitude": ("幅度", "信号幅度"),
    "weight": ("权重", "权重"),
    "energy": ("能量", "收益平方类能量"),
    "shock": ("冲击", "冲击事件"),
    "premium": ("溢价", "溢价项"),
    "small": ("小", "小盘/小值"),
    "large": ("大", "大盘/大值"),
    "medium": ("中", "中盘/中值"),
    "tail": ("尾部", "尾部事件"),
    "bar": ("K 线", "K 线/柱"),
    "overnight": ("隔夜", "隔夜时段"),
    "intraday": ("日内", "日内时段"),
    "close_": ("收盘 (下标)", "下标收盘价"),
    "high_": ("最高 (下标)", "下标最高价"),
    "median20_": ("20 日中位数 (下标)", "下标 20 日中位数"),
    "vol_ma20_": ("20 日均量 (下标)", "下标 20 日均量"),
    "prior_high5": ("5 日前期高点", "5 日前期高点"),
    "prior_high20_": ("20 日前期高点", "20 日前期高点"),
    "prior_high_": ("前期高点", "前期高点"),
    "High": ("最高价", "high 别名"),
    "Low": ("最低价", "low 别名"),
    "Open": ("开盘价", "open 别名"),
    "Close": ("收盘价", "close 别名"),
    "Volume": ("成交量", "volume 别名"),
    "Amount": ("成交额", "amount 别名"),
    "Returns": ("收益", "returns 别名"),
    "Trend": ("趋势", "trend 别名"),
    "Range": ("振幅", "range 别名"),
    "price": ("价格", "价格"),
    "dollar_volume": ("成交额", "成交额"),
    "net_dir": ("净方向", "买卖净方向"),
    "consensus": ("共识度", "多信号一致性"),
    "v": ("成交量", "volume 简写"),
    "vol_ratio_risk_10": ("10 日量比风险", "10 日量比（风险过滤用）"),
    "pct_vol_change": ("量能变化率", "成交量百分比变化"),
    "close_5d_ago": ("5 日前收盘", "ts_delay(close,5)"),
    "opening_price": ("开盘价", "open 别名"),
    "vwap_deviation": ("VWAP 偏离", "close/vwap - 1"),
    "typical_price": ("典型价", "(high+low+close)/3"),
    "upper_shadow": ("上影线", "high - max(open,close)"),
    "lower_shadow": ("下影线", "min(open,close) - low"),
    "lower_wick": ("下影线", "min(open,close) - low"),
    "range_ratio_z": ("振幅比 Z-Score", "range_ratio 的 z-score"),
    "norm_pressure": ("归一化压力", "归一化压力"),
    "volume_tail_asymmetry": ("量能尾部不对称", "量能尾部不对称度量"),
    "range_volume_ratio": ("振幅量比", "振幅与量比结合"),
    "short_ma_abs_log_ret": ("短期绝对对数收益", "短窗口绝对对数收益"),
    "long_ma_abs_log_ret": ("长期绝对对数收益", "长窗口绝对对数收益"),
    "reversion": ("反转", "反转信号"),
    "close_5d_ago": ("5 日前收盘", "5 日前收盘"),
    "defined_high_volume": ("定义高量能", "高量能定义"),
    "transition_into_EMA": ("转入 EMA 状态", "EMA 状态转换"),
    "halve": ("减半", "减半"),
    "classification": ("分类", "分类状态"),
    "continuous": ("连续", "连续变量"),
    "path": ("路径", "路径/轨迹"),
    "formula": ("公式", "公式"),
    "moving": ("移动", "移动"),
    "reversed": ("反转", "反转"),
    "full": ("全部", "全窗口"),
    "conditional": ("条件", "条件"),
    "conditioned": ("条件化", "条件化"),
    "relative": ("相对", "相对"),
    "absolute": ("绝对", "绝对"),
    "cumulative": ("累计", "累计"),
    "bounded": ("有界", "有界"),
    "consecutive": ("连续", "连续"),
    "binary": ("二元", "二元标志"),
    "integer": ("整数", "整数"),
    "signed": ("带符号", "带符号"),
    "fraction": ("比例", "比例"),
    "percentage": ("百分比", "百分比"),
    "lower": ("下方", "下方向"),
    "upper": ("上方", "上方向"),
    "positive": ("正值", "正值"),
    "negative": ("负值", "负值"),
    "large_val": ("大值", "大值分支"),
    "midpoint": ("中间价", "(high+low)/2"),
    "size_gated_value_leverage": ("市值门控价值杠杆", "市值门控价值杠杆"),
    "size_trend_value": ("市值趋势价值", "市值趋势价值"),
    "value_quality_growth_sales_yield": ("价值质量成长销售收益率", "价值质量成长因子"),
    "share": ("占比", "占比"),
    "energy": ("能量", "平方收益能量"),
    "path": ("路径", "路径"),
    "series": ("序列", "序列"),
    "time": ("时间", "时间"),
    "IC": ("信息系数", "IC"),
    "weight_long": ("长期权重", "长期权重"),
    "close_ret": ("收盘收益", "收盘收益"),
    "price_impact": ("价格冲击", "价格冲击"),
    "efficiency": ("效率", "效率"),
    "impact": ("冲击", "冲击"),
    "flow": ("资金流", "资金流"),
    "imbalance": ("订单失衡", "订单失衡"),
    "dollar_volume": ("成交额", "成交额"),
    "occupancy": ("驻留度", "驻留度"),
    "participation": ("参与度", "参与度"),
    "modifier": ("修正项", "修正项"),
    "dampener": ("阻尼", "阻尼"),
    "premium": ("溢价", "溢价"),
    "stress": ("压力", "压力"),
    "stress_fast": ("快速压力", "快速压力"),
    "stress_slow": ("慢速压力", "慢速压力"),
    "stress_ratio": ("压力比", "压力比"),
    "downside_damage_12": ("12 日下行损伤", "12 日下行损伤"),
    "downside_energy_share_20": ("20 日下行能量占比", "20 日下行能量占比"),
    "downside_energy_share_30": ("30 日下行能量占比", "30 日下行能量占比"),
    "overnight_downside_energy_share": ("隔夜下行能量占比", "隔夜下行能量占比"),
    "excursion": ("偏离", "偏离"),
    "shock": ("冲击", "冲击"),
    "hold_persistence": ("持有持续", "持有持续"),
    "persistence": ("持续性", "持续性"),
    "consensus": ("共识", "共识"),
    "smooth_corr": ("平滑相关", "平滑相关"),
    "corr": ("相关", "相关"),
    "blend": ("混合", "混合"),
    "asym_ratio": ("不对称比", "不对称比"),
    "asymmetry": ("不对称", "不对称"),
    "composite": ("复合", "复合"),
    "base_factor": ("基础因子", "基础因子"),
    "scaled_rank": ("缩放排名", "缩放排名"),
    "rank_p": ("排名百分位", "排名百分位"),
    "rank": ("排名", "排名"),
    "percentile_rank": ("百分位排名", "百分位排名"),
    "smoothed": ("平滑", "平滑"),
    "raw": ("原始", "原始"),
    "signal": ("信号", "信号"),
    "normalized": ("归一化", "归一化"),
    "adjusted_ratio": ("调整比", "调整比"),
    "weight": ("权重", "权重"),
    "change": ("变化", "变化"),
    "direction": ("方向", "方向"),
    "rev": ("反转", "反转"),
    "stretch": ("拉伸", "拉伸"),
    "efficiency": ("效率", "效率"),
    "reduce": ("衰减", "衰减"),
    "forward": ("前向", "前向"),
    "magnitude": ("幅度", "幅度"),
    "price": ("价格", "价格"),
    "price_amp": ("价格振幅", "价格振幅"),
    "vwap_deviation": ("VWAP 偏离", "VWAP 偏离"),
    "vwap_squared_deviation_intensity": ("VWAP 偏离平方强度", "VWAP 偏离平方强度"),
    "vwap_deviation_intensity_squared_amount_weighted": ("VWAP 偏离平方金额加权强度", "VWAP 偏离平方金额加权强度"),
    "rolling_vwap": ("滚动 VWAP", "滚动 VWAP"),
    "daily_last": ("日末", "日末"),
    "close_loc": ("收盘位置", "收盘位置"),
    "close_location": ("收盘位置", "收盘位置"),
    "C": ("收盘价简写", "close 简写"),
    "O": ("开盘价简写", "open 简写"),
    "H": ("最高价简写", "high 简写"),
    "L": ("最低价简写", "low 简写"),
    "B": ("基准价", "公式基准价"),
    "I": ("指示函数", "指示函数"),
    "S": ("信号", "信号"),
    "E": ("均值", "均值"),
    "F": ("标志", "标志"),
    "R": ("参考价", "参考价"),
    "Z": ("标准化", "标准化"),
    "close_loc": ("收盘位置", "收盘位置"),
    "E_t": ("期均值", "期均值"),
    "w_t": ("期权重", "期权重"),
    "avg_abs_ret": ("平均绝对收益", "平均绝对收益"),
    "mean_16": ("16 日均值", "16 日均值"),
    "mean_12": ("12 日均值", "12 日均值"),
    "mean_10": ("10 日均值", "10 日均值"),
    "mean_5": ("5 日均值", "5 日均值"),
    "mean20": ("20 日均值", "20 日均值"),
    "max20": ("20 日最大值", "20 日最大值"),
    "max_20": ("20 日最大值", "20 日最大值"),
    "max_10": ("10 日最大值", "10 日最大值"),
    "median_20": ("20 日中位数", "20 日中位数"),
    "sum_20": ("20 日求和", "20 日求和"),
    "ts_rank_": ("滚动排名", "滚动排名"),
    "rolling_mean_20": ("20 日滚动均值", "20 日滚动均值"),
    "rolling_std_20": ("20 日滚动标准差", "20 日滚动标准差"),
    "EWMA_24": ("24 日 EWMA", "24 日 EWMA"),
    "EWMA_30": ("30 日 EWMA", "30 日 EWMA"),
    "EWMA_45": ("45 日 EWMA", "45 日 EWMA"),
    "EWMA_up_vol": ("上行量 EWMA", "上行量 EWMA"),
    "EWMA_down_vol": ("下行量 EWMA", "下行量 EWMA"),
    "EMA_": ("EMA 简写", "EMA"),
    "EWM_std": ("EWM 标准差", "EWM 标准差"),
    "EMA_volume": ("量能 EMA", "量能 EMA"),
    "RollingStd60": ("60 日滚动标准差", "60 日滚动标准差"),
    "Var_60": ("60 日方差", "60 日方差"),
    "Var_40": ("40 日方差", "40 日方差"),
    "Cov_60": ("60 日协方差", "60 日协方差"),
    "Cov_40": ("40 日协方差", "40 日协方差"),
    "rolling_mean": ("滚动均值", "滚动均值"),
    "rolling_std": ("滚动标准差", "滚动标准差"),
    "rolling_skew": ("滚动偏度", "滚动偏度"),
    "rolling_zscore": ("滚动 Z-Score", "滚动 Z-Score"),
    "rolling_max": ("滚动最大值", "滚动最大值"),
    "cummax": ("累计最大值", "累计最大值"),
    "Rng": ("振幅", "振幅"),
    "skew": ("偏度", "偏度"),
    "IC": ("信息系数", "信息系数"),
    "delta_depth_10": ("10 日回撤深度变化", "10 日回撤深度变化"),
    "median": ("中位数", "中位数"),
    "close_10d_return": ("10 日收盘收益", "10 日收盘收益"),
    "close_10d_chg": ("10 日收盘变化", "10 日收盘变化"),
    "close_pct_change": ("收盘变化率", "收盘变化率"),
    "price_amp": ("价格振幅", "价格振幅"),
    "vol_dev": ("量能偏离", "量能偏离"),
    "typical_price": ("典型价", "典型价"),
    "adj": ("复权", "复权"),
    "skew_weighted_volume_event_intensity": ("偏度加权量事件强度", "偏度加权量事件强度"),
    "skew_weighted_volume_event_intensity_close": ("偏度加权量事件强度(收盘)", "偏度加权量事件强度(收盘)"),
    "short_ma_abs_log_ret": ("短期绝对对数收益", "短期绝对对数收益"),
    "long_ma_abs_log_ret": ("长期绝对对数收益", "长期绝对对数收益"),
    "Roughness_Ratio": ("粗糙度比", "粗糙度比"),
    "ifnan": ("NaN 处理", "NaN 处理"),
    "winsorize": ("缩尾", "缩尾"),
    "rank_trailing": ("尾随排名", "尾随排名"),
    "factor": ("因子输出", "因子输出"),
    "score": ("评分", "评分"),
    "depth_score": ("回撤深度评分", "回撤深度评分"),
    "duration": ("持续期", "持续期"),
    "intensity": ("强度", "强度"),
    "energy": ("能量", "能量"),
    "small": ("小", "小"),
    "large": ("大", "大"),
    "medium": ("中", "中"),
    "tail": ("尾部", "尾部"),
    "bar": ("K线", "K线"),
    "overnight": ("隔夜", "隔夜"),
    "intraday": ("日内", "日内"),
    "close_": ("收盘(下标)", "收盘(下标)"),
    "high_": ("最高(下标)", "最高(下标)"),
    "median20_": ("20日中位数(下标)", "20日中位数(下标)"),
    "vol_ma20_": ("20日均量(下标)", "20日均量(下标)"),
    "prior_high5": ("5日前期高点", "5日前期高点"),
    "prior_high20_": ("20日前期高点", "20日前期高点"),
    "prior_high_": ("前期高点", "前期高点"),
    "Returns": ("收益", "收益"),
    "Trend": ("趋势", "趋势"),
    "Range": ("振幅", "振幅"),
    "opening_price": ("开盘价", "开盘价"),
    "vol_ratio_risk_10": ("10日量比风险", "10日量比风险"),
    "pct_vol_change": ("量能变化率", "量能变化率"),
    "volume_momentum": ("量能动量", "量能动量"),
    "close_5d_ago": ("5日前收盘", "5日前收盘"),
    "vwap_deviation": ("VWAP偏离", "VWAP偏离"),
    "upper_shadow": ("上影线", "上影线"),
    "lower_shadow": ("下影线", "下影线"),
    "lower_wick": ("下影线", "下影线"),
    "norm_pressure": ("归一化压力", "归一化压力"),
    "volume_tail_asymmetry": ("量能尾部不对称", "量能尾部不对称"),
    "range_volume_ratio": ("振幅量比", "振幅量比"),
    "reversion": ("反转", "反转"),
    "defined_high_volume": ("定义高量能", "定义高量能"),
    "transition_into_EMA": ("转入EMA状态", "转入EMA状态"),
    "halve": ("减半", "减半"),
    "classification": ("分类", "分类"),
    "continuous": ("连续", "连续"),
    "path": ("路径", "路径"),
    "formula": ("公式", "公式"),
    "moving": ("移动", "移动"),
    "reversed": ("反转", "反转"),
    "full": ("全部", "全部"),
    "conditional": ("条件", "条件"),
    "conditioned": ("条件化", "条件化"),
    "relative": ("相对", "相对"),
    "absolute": ("绝对", "绝对"),
    "cumulative": ("累计", "累计"),
    "bounded": ("有界", "有界"),
    "consecutive": ("连续", "连续"),
    "binary": ("二元", "二元"),
    "signed": ("带符号", "带符号"),
    "fraction": ("比例", "比例"),
    "percentage": ("百分比", "百分比"),
    "lower": ("下方", "下方"),
    "upper": ("上方", "上方"),
    "positive": ("正值", "正值"),
    "negative": ("负值", "负值"),
    "large_val": ("大值", "大值"),
    "size_gated_value_leverage": ("市值门控价值杠杆", "市值门控价值杠杆"),
    "size_trend_value": ("市值趋势价值", "市值趋势价值"),
    "value_quality_growth_sales_yield": ("价值质量成长销售收益率", "价值质量成长因子"),
    "share": ("占比", "占比"),
    "path": ("路径", "路径"),
    "series": ("序列", "序列"),
    "time": ("时间", "时间"),
    "price_impact": ("价格冲击", "价格冲击"),
    "flow": ("资金流", "资金流"),
    "imbalance": ("订单失衡", "订单失衡"),
    "dollar_volume": ("成交额", "成交额"),
    "occupancy": ("驻留度", "驻留度"),
    "participation": ("参与度", "参与度"),
    "modifier": ("修正项", "修正项"),
    "dampener": ("阻尼", "阻尼"),
    "stress": ("压力", "压力"),
    "stress_fast": ("快速压力", "快速压力"),
    "stress_slow": ("慢速压力", "慢速压力"),
    "stress_ratio": ("压力比", "压力比"),
    "downside_damage_12": ("12日下行损伤", "12日下行损伤"),
    "excursion": ("偏离", "偏离"),
    "shock": ("冲击", "冲击"),
    "hold_persistence": ("持有持续", "持有持续"),
    "persistence": ("持续性", "持续性"),
    "consensus": ("共识", "共识"),
    "smooth_corr": ("平滑相关", "平滑相关"),
    "corr": ("相关", "相关"),
    "blend": ("混合", "混合"),
    "asym_ratio": ("不对称比", "不对称比"),
    "asymmetry": ("不对称", "不对称"),
    "composite": ("复合", "复合"),
    "base_factor": ("基础因子", "基础因子"),
    "scaled_rank": ("缩放排名", "缩放排名"),
    "rank_p": ("排名百分位", "排名百分位"),
    "rank": ("排名", "排名"),
    "percentile_rank": ("百分位排名", "百分位排名"),
    "smoothed": ("平滑", "平滑"),
    "raw": ("原始", "原始"),
    "signal": ("信号", "信号"),
    "normalized": ("归一化", "归一化"),
    "adjusted_ratio": ("调整比", "调整比"),
    "weight": ("权重", "权重"),
    "change": ("变化", "变化"),
    "direction": ("方向", "方向"),
    "rev": ("反转", "反转"),
    "stretch": ("拉伸", "拉伸"),
    "efficiency": ("效率", "效率"),
    "reduce": ("衰减", "衰减"),
    "forward": ("前向", "前向"),
    "magnitude": ("幅度", "幅度"),
    "price": ("价格", "价格"),
    "price_amp": ("价格振幅", "价格振幅"),
    "close_loc": ("收盘位置", "收盘位置"),
    "close_location": ("收盘位置", "收盘位置"),
    # ---- 补漏（最后 4 个）----
    "prior": ("前期冲击累计", "shock 事件累计项：prior = ts_sum(60, ts_delay(shock))"),
    "pressure": ("压力项", "趋势/量能压力中间变量（见 trend_volume_tanh_rank 等公式）"),
    "pos_ret_10": ("10 日正收益累计", "近 10 日正收益的累计项"),
    "size": ("市值", "市值规模（用于市值分组/滚动市值百分位）"),
    # ---- 终验补充（2026-08-29：cleaned-call 形态中出现的字段 token）----
    "abs_ret": ("绝对收益", "日收益的绝对值 |ret|；衡量波动/冲击幅度"),
    "RSI_WILDER": ("RSI (Wilder)", "Wilder 平滑版相对强弱指数；RSI_WILDER(AdjClose, 14) 为 14 日"),
    "is_low_vol": ("低量能状态标志", "classify_volume_regime 输出的低量能状态"),
    "vol_ratio_cont": ("连续量比", "持续跟踪的量比信号（量比连续版本）"),
    "__ROLLKW__": ("滚动窗口聚合占位", "DSL 展开占位符：__ROLLKW__(x) 表示自定义滚动窗口聚合"),
    "o": ("Python 命名空间", "cleaned-call 形态的命名空间：o['ts_mean'] 等价算子 ts_mean"),
    "col": ("取列", "col('AdjClose') 按名称取数据列（等价 get）"),
    "eq": ("相等比较", "eq(a, b)：a == b 比较（结果 1/0）"),
    "ne": ("不等比较", "ne(a, b)：a != b 比较（结果 1/0）"),
    "neg": ("取负", "neg(x) 等价 -x；Python 形态禁止 nan，用 o['log'](-1.0) 处理非正数"),
    "identity": ("恒等映射", "identity(x) 原样返回，用于显式包装"),
    "is_finite": ("有限数判定", "is_finite(x)：非 inf/NaN 为 1，否则 0"),
    "is_nan": ("NaN 判定", "is_nan(x)：NaN 为 1，否则 0"),
    "safe_div_null": ("安全除法", "safe_div_null(a, b)：b=0 时返回空/NaN 不报错"),
    "flex_max": ("弹性区间上界", "窗口内最大值：flex_max(high_{t-22..t-3}) 类前期高点上界"),
    "flex_min": ("弹性区间下界", "窗口内最小值：flex_min(open, AdjClose) 类区间下界"),
    "ts_ewm_std": ("EWM 滚动标准差", "指数加权滚动标准差（近期权重更大的波动）"),
    "delay": ("滞后", "delay(x, n)：x[t-n] 同 ts_delay；x.delay(n) 形式亦可"),
}

# ============================================================
# 算子补充（DSL 中出现且 factor_engine 可解析，或 LQTP 伪算子）
# ============================================================
OP_DOC_EXTRA = {
    # ---- FE canonical 新增 ----
    "ewm_mean": "ewm_mean(x, span=n) → 指数加权移动平均 (EMA；span 控制衰减速度)",
    "ts_delay": "ts_delay(x, n) → x[t-n]（n 期滞后）",
    "tanh": "tanh(x) → 双曲正切，将值压到 (-1, 1)",
    "ts_atr": "ts_atr(n) → 平均真实波幅 (ATR, high/low/close 输入)",
    "cs_rank": "cs_rank(x) → 截面百分位排名 (0~1，同 rank)",
    "ts_pct": "ts_pct(x, n) → n 期变化率 (x[t]/x[t-n] - 1)",
    "cs_zscore": "cs_zscore(x) → 截面 Z-Score 标准化",
    "ts_adx": "ts_adx(n) → ADX 平均趋向指数（趋势强度）",
    "ts_skew": "ts_skew(x, n) → n 期滚动偏度",
    "ewm_std": "ewm_std(x, span=n) → 指数加权移动标准差",
    "ts_zscore": "ts_zscore(x, n) → n 期滚动 Z-Score",
    "fillna": "fillna(x, method) → 缺失值填充 (mean/median/zero/ffill)",
    "rank_corr": "rank_corr(x, y, n) → 滚动窗口秩相关",
    "sigmoid": "sigmoid(x) → 1/(1+exp(-x)) 的 S 形映射",
    "volatility": "volatility(x, n) → 年化波动率",
    "max_drawdown": "max_drawdown(x) → 最大回撤",
    "ts_rsi": "ts_rsi(n) → RSI 相对强弱指数",
    "correlation": "correlation(x, y, n) → 相关系数（corr 的别名）",
    "delta": "delta(x, n) → n 期差分 (ts_delta 别名)",
    "ts_delta": "ts_delta(x, n) → x[t] - x[t-n]（n 期差分）",
    "ts_ema": "ts_ema(x, n) → n 期指数移动平均",
    "ts_corr": "ts_corr(x, y, n) → 滚动相关",
    "ts_cov": "ts_cov(x, y, n) → 滚动协方差",
    "ts_rank": "ts_rank(x, n) → 当前值在窗口内百分位",
    "ts_median": "ts_median(x, n) → 滚动中位数",
    "ts_std": "ts_std(x, n) → 滚动标准差",
    "ts_sum": "ts_sum(x, n) → 滚动求和",
    "ts_max": "ts_max(x, n) → 滚动最大值",
    "ts_min": "ts_min(x, n) → 滚动最小值",
    "ts_mean": "ts_mean(x, n) → 滚动均值",
    "zscore": "zscore(x) → 截面 Z-Score 标准化",
    "rank": "rank(x) → 截面百分位排名 (0~1)",
    "scale": "scale(x) → 截面归一化 (和为 1)",
    "winsorize": "winsorize(x, lo, hi) → 极值缩尾",
    "where": "where(cond, x, y) → 条件选择",
    "clip": "clip(x, lo, hi) → 裁剪到区间",
    "abs": "abs(x) → 绝对值",
    "log": "log(x) → 自然对数",
    "sqrt": "sqrt(x) → 平方根",
    "sign": "sign(x) → 符号 (1/0/-1)",
    "exp": "exp(x) → e^x",
    "pow": "pow(x, n) → x^n",
    "min": "min(x, n) → 滚动最小 / 逐点最小",
    "max": "max(x, n) → 滚动最大 / 逐点最大",
    "mean": "mean(x, n) → 滚动均值",
    "sum": "sum(x, n) → 滚动求和",
    "std": "std(x, n) → 滚动标准差",
    "prod": "prod(x, n) → 滚动乘积",
    "ewm": "ewm(...) → pandas 指数加权",
    "ewma": "ewma(x, span=n) → 指数加权移动平均",
    "shift": "shift(n) → 滞后/移位",
    "rolling": "rolling(n) → 滚动窗口",
    "pct_change": "pct_change(n) → 变化率",
    "replace": "replace(...) → 替换值",
    # ---- LQTP 伪算子（DSL 语法近似）----
    "get": "get('field') → 按名称取数据列",
    "true_range": "true_range(high, low, close) → 真实波幅 TR",
    "mean20": "mean20(x) → 20 日滚动均值 (ts_mean 简写)",
    "max20": "max20(x) → 20 日滚动最大值",
    "mean_20": "mean_20(x) → 20 日滚动均值",
    "max_20": "max_20(x) → 20 日滚动最大值",
    "mean_10": "mean_10(x) → 10 日滚动均值",
    "mean_5": "mean_5(x) → 5 日滚动均值",
    "max_10": "max_10(x) → 10 日滚动最大值",
    "median_20": "median_20(x) → 20 日滚动中位数",
    "sum_20": "sum_20(x) → 20 日滚动求和",
    "rolling_max": "rolling_max(x, n) → 滚动最大值",
    "rolling_mean": "rolling_mean(x, n) → 滚动均值",
    "rolling_std": "rolling_std(x, n) → 滚动标准差",
    "rolling_skew": "rolling_skew(x, n) → 滚动偏度",
    "rolling_zscore": "rolling_zscore(x, n) → 滚动 Z-Score",
    "rolling_corr": "rolling_corr(x, y, n) → 滚动相关",
    "rolling_20_corr": "rolling_20_corr(x, y) → 20 日滚动相关",
    "rolling_20_mean": "rolling_20_mean(x) → 20 日滚动均值",
    "rolling_20_median": "rolling_20_median(x) → 20 日滚动中位数",
    "rolling_40_std": "rolling_40_std(x) → 40 日滚动标准差",
    "rollingmean": "rollingmean(x, n) → 滚动均值",
    "rolling20": "rolling20(x) → 20 日滚动",
    "corr": "corr(x, y, n) → 相关系数",
    "daily_corr": "daily_corr(x, y) → 日度相关系数",
    "rank_corr": "rank_corr(x, y, n) → 秩相关",
    "Corr20": "Corr20(x, y) → 20 日相关",
    "roc": "roc(x, n) → n 期变动率",
    "roc40": "roc40(x) → 40 期变动率",
    "roc10": "roc10(x) → 10 期变动率",
    "ROC20": "ROC20(x) → 20 期变动率指标",
    "ROC5": "ROC5(x) → 5 期变动率指标",
    "cummax": "cummax(x) → 累计最大值",
    "cum_min": "cum_min(x) → 累计最小值",
    "cum_mean": "cum_mean(x) → 累计均值",
    "cum_sum": "cum_sum(x) → 累计求和",
    "trailing_max": "trailing_max(x, n) → 滚动最大值（尾随窗口）",
    "trailing_vol": "trailing_vol(x, n) → 尾随窗口波动率",
    "EMA_volume": "EMA_volume(v, n) → 量能指数均线",
    "EMA20": "EMA20(x) → 20 期指数均线",
    "EMA50": "EMA50(x) → 50 期指数均线",
    "EMA200": "EMA200(x) → 200 期指数均线",
    "EWMA30": "EWMA30(x) → span=30 指数均线",
    "EWMA_30": "EWMA_30(x) → span=30 指数均线",
    "EWMA_45": "EWMA_45(x) → span=45 指数均线",
    "EWM_std": "EWM_std(x, n) → 指数加权标准差",
    "EWM": "EWM(...) → 指数加权",
    "MA20": "MA20(x) → 20 期移动均线",
    "MA30": "MA30(x) → 30 期移动均线",
    "MA40": "MA40(x) → 40 期移动均线",
    "MA80": "MA80(x) → 80 期移动均线",
    "MA": "MA(x, n) → n 期移动均线",
    "MA_volume": "MA_volume(v, n) → 量能移动均线",
    "SMA10": "SMA10(x) → 10 期简单均线",
    "SMA20": "SMA20(x) → 20 期简单均线",
    "SMA60": "SMA60(x) → 60 期简单均线",
    "SMA90": "SMA90(x) → 90 期简单均线",
    "SMA_5": "SMA_5(x) → 5 期简单均线",
    "SMA_10": "SMA_10(x) → 10 期简单均线",
    "SMA_21": "SMA_21(x) → 21 期简单均线",
    "SMA": "SMA(x, n) → 简单均线",
    "ema_10": "ema_10(x) → 10 期指数均线",
    "ATR5": "ATR5 → 5 日平均真实波幅",
    "ATR10": "ATR10 → 10 日平均真实波幅",
    "ATR14": "ATR14 → 14 日平均真实波幅",
    "ATR20": "ATR20 → 20 日平均真实波幅",
    "ATR21": "ATR21 → 21 日平均真实波幅",
    "ATR60": "ATR60 → 60 日平均真实波幅",
    "ATR90": "ATR90 → 90 日平均真实波幅",
    "ATR_14": "ATR_14 → 14 日平均真实波幅",
    "ATR_EMA90": "ATR_EMA90 → ATR 与 EMA90 组合",
    "PLUS_DI": "PLUS_DI(n) → 正向趋向指标 (+DI)",
    "MINUS_DI": "MINUS_DI(n) → 负向趋向指标 (-DI)",
    "down_vol": "down_vol(x, n) → 下行波动率",
    "up_vol": "up_vol(x, n) → 上行波动率",
    "downside_vol": "downside_vol(x, n) → 下行波动率",
    "upside_vol": "upside_vol(x, n) → 上行波动率",
    "downside_ratio": "downside_ratio(x, n) → 下行比率",
    "downside_stress_ratio": "downside_stress_ratio(x, n) → 下行压力比",
    "skew": "skew(x, n) → 滚动偏度",
    "daily_skew": "daily_skew(x) → 日度偏度",
    "daily_std": "daily_std(x) → 日度标准差",
    "daily_kurt": "daily_kurt(x) → 日度峰度",
    "daily_last": "daily_last(x) → 日末值",
    "daily_mean": "daily_mean(x) → 日度均值",
    "neg_std": "neg_std(x, n) → 负收益部分标准差",
    "pos_std": "pos_std(x, n) → 正收益部分标准差",
    "total_vol": "total_vol(x, n) → 总波动率",
    "close_std": "close_std(x, n) → 收盘价滚动标准差",
    "std_20": "std_20(x) → 20 期滚动标准差",
    "robust_z": "robust_z(x) → 稳健 Z-Score（基于中位数/MAD）",
    "m_zscore": "m_zscore(x, n) → 滚动 Z-Score",
    "m_skew": "m_skew(x, n) → 滚动偏度",
    "rank_trailing": "rank_trailing(x, n) → 尾随窗口排名",
    "rank_ts": "rank_ts(x, n) → 时序滚动排名",
    "rank_p": "rank_p(x) → 百分位排名",
    "percentile_rank": "percentile_rank(x) → 百分位排名",
    "cs_weighted_mean": "cs_weighted_mean(x, w) → 截面加权均值",
    "group_weighted_mean": "group_weighted_mean(x, w, g) → 分组加权均值",
    "Rng": "Rng(x, n) → n 期振幅",
    "RollingStd60": "RollingStd60(x) → 60 期滚动标准差",
    "Var_60": "Var_60(x) → 60 期方差",
    "Var_40": "Var_40(x) → 40 期方差",
    "Cov_60": "Cov_60(x, y) → 60 期协方差",
    "Cov_40": "Cov_40(x, y) → 40 期协方差",
    "CV": "CV(x, n) → 变异系数 (std/mean)",
    "momentum": "momentum(x, n) → n 期动量",
    "consensus": "consensus(x, n) → 多信号共识度",
    "score": "score(...) → 中间评分",
    "tr": "tr(...) → 真实波幅",
    "lag": "lag(x, n) → n 期滞后",
    "lag4": "lag4(x) → 4 期滞后",
    "shift1": "shift1(x) → 1 期滞后",
    "shift5": "shift5(x) → 5 期滞后",
    "shift10": "shift10(x) → 10 期滞后",
    "sma": "sma(x, n) → 简单均线",
    "sma_20": "sma_20(x) → 20 期简单均线",
    "sma_30": "sma_30(x) → 30 期简单均线",
    "v": "v(...) → 成交量（字段简写）",
    "vol": "vol(...) → 成交量（字段简写）",
    "V": "V(...) → 成交量（字段简写）",
    "vol_ratio": "vol_ratio(x, n) → 量比",
    "vol_ratio_EMA": "vol_ratio_EMA(x, n) → 量比 EMA",
    "vol_ratio_risk_10": "vol_ratio_risk_10(x) → 10 日量比（风险过滤）",
    "median_vol": "median_vol(x, n) → 量能中位数",
    "med_vol": "med_vol(x, n) → 量能中位数",
    "med_vol_20": "med_vol_20(x) → 20 日量能中位数",
    "med_vol_60": "med_vol_60(x) → 60 日量能中位数",
    "median": "median(x, n) → 滚动中位数",
    "regime_adaptive_trailing_high": "regime_adaptive_trailing_high(x, ...) → 状态自适应前期高点",
    "resvol_high": "resvol_high(...) → 高残差波动状态",
    "vwap_deviation": "vwap_deviation(x) → VWAP 偏离",
    "rolling_vwap": "rolling_vwap(x, w) → 滚动 VWAP",
    "EMA_gated": "EMA_gated(x, ...) → 门控 EMA",
    "drawdown": "drawdown(x) → 回撤",
    "directional_efficiency": "directional_efficiency(x, n) → 方向效率",
    "downside_energy": "downside_energy(x, n) → 下行能量",
    "downside_ratio": "downside_ratio(x, n) → 下行比率",
    "ret": "ret(...) → 收益率（字段）",
    "I": "I(cond) → 指示函数（条件为真=1）",
    "C": "C → 收盘价（简写）",
    "O": "O → 开盘价（简写）",
    "H": "H → 最高价（简写）",
    "L": "L → 最低价（简写）",
    "B": "B → 基准价",
    "S": "S → 信号",
    "E20": "E20(x) → 20 期均值",
    "E30": "E30(x) → 30 期均值",
    "MA30": "MA30(x) → 30 期均线",
    "E": "E(x) → 均值",
    "F": "F → 事件标志",
    "R": "R → 参考价",
    "Z": "Z → 标准化",
    "d": "d(...) → 差分/天数",
    "minutes": "minutes(...) → 分钟数",
    "np": "np.* → numpy 函数",
    "asym_vol_weighted": "asym_vol_weighted(...) → 自定义 DSL 因子",
    "drawdown_recovery_roughness": "drawdown_recovery_roughness(...) → 自定义 DSL 因子",
    "range_volume_ratio": "range_volume_ratio(...) → 自定义 DSL 因子",
    "size_gated_value_leverage": "size_gated_value_leverage(...) → 自定义 DSL 因子",
    "skew_weighted_volume_event_intensity": "skew_weighted_volume_event_intensity(...) → 自定义 DSL 因子",
    "skew_weighted_volume_event_intensity_close": "skew_weighted_volume_event_intensity_close(...) → 自定义 DSL 因子",
    "value_quality_growth_sales_yield": "value_quality_growth_sales_yield(...) → 自定义 DSL 因子",
    "vwap_deviation_intensity_squared_amount_weighted": "vwap_deviation_intensity_squared_amount_weighted(...) → 自定义 DSL 因子",
    "vwap_squared_deviation_intensity": "vwap_squared_deviation_intensity(...) → 自定义 DSL 因子",
    "MYDSL": "MYDSL(name) → 自定义命名 DSL（看 factor_manual_61 手动公式）",
    "if": "if(cond, a, b) → 条件选择（DSL 三元/if-else）",
    "else": "else → if-else 分支",
    "then": "then → if-else 分支",
    "If": "If(cond, a, b) → 条件选择",
    "Else": "Else → if-else 分支",
    "For": "For(...) → 循环",
    "when": "when(cond, a, b) → 条件选择",
    "otherwise": "otherwise → 否则分支",
    "smoothed": "smoothed(x, span=n) → 平滑（EMA/滚动）",
    "smoothing": "smoothing(...) → 平滑处理",
    "normalized": "normalized(x) → 归一化",
    "clipped": "clipped(x, lo, hi) → 裁剪",
    "capped": "capped(x, lo, hi) → 上限裁剪",
    "weighted": "weighted(x, w) → 加权",
    "absolute": "absolute(x) → 绝对值",
    "signed": "signed(x) → 带符号",
    "cumulative": "cumulative(...) → 累计",
    "multiplied": "multiplied(...) → 相乘",
    "divide": "divide(a, b) → 除法",
    "subtract": "subtract(a, b) → 减法",
    "add": "add(a, b) → 加法",
    "multiply": "multiply(a, b) → 乘法",
    "minus": "minus(a, b) → 减法",
    "reduce": "reduce(...) → 归约/衰减",
    "fill": "fill(x, v) → 填充",
    "lagged": "lagged(x, n) → 滞后",
    "trailing": "trailing(...) → 尾随窗口",
    "composite": "composite(...) → 复合",
    "direction": "direction(...) → 方向",
    "change": "change(x) → 变化",
    "price": "price(...) → 价格",
    "shock": "shock(...) → 冲击",
    "persistence": "persistence(...) → 持续性",
    "forward": "forward(...) → 前向",
    "overnight": "overnight(...) → 隔夜",
    "intraday": "intraday(...) → 日内",
    "adjust": "adjust(...) → 调整",
    "sigma_down": "sigma_down(x, n) → 滚动下行波动率（ret<0 部分 std）",
    "sigma_up": "sigma_up(x, n) → 滚动上行波动率（ret>0 部分 std）",
    "classify_volume_regime": "classify_volume_regime(vol, n) → 量能状态分类：(is_high, is_low, vol_ratio)",
    "days": "days → 英文文本（如 median over 10 days）",
    "ratio": "ratio → 比率（英文文本/比率项）",
    "binary": "binary(cond) → 条件为真=1 否则 0 的二元化",
    # ---- 末轮补全（2026-08-29 终验：DSL 中仍出现但未登记的算子/字段）----
    "o": "o['name'] → Python cleaned-call 命名空间（cleaned-call 形态：o['ts_mean'] 等价 ts_mean，o['neg'] 等价取负）",
    "col": "col('Field') → 按名称取数据列（等价 get('Field')；引擎列名如 AdjClose/AdjVwap/Volume）",
    "eq": "eq(a, b) → 相等比较（a == b，结果 1/0 或 NaN）",
    "ne": "ne(a, b) → 不等比较（a != b，结果 1/0）",
    "neg": "neg(x) → 取负（-x；Python 形态禁止 nan，等价 o['log'](-1.0) 处理非正数）",
    "identity": "identity(x) → 恒等映射（原样返回，用于显式包装避免歧义）",
    "is_finite": "is_finite(x) → 是否有限数（非 inf/NaN 为 1，否则 0）",
    "is_nan": "is_nan(x) → 是否 NaN（NaN 为 1，否则 0）",
    "safe_div_null": "safe_div_null(a, b) → 安全除法（b=0 时返回空/NaN，不报错）",
    "flex_max": "flex_max(a, b, ...) → 窗口内最大值（手动公式中的弹性上轨/区间上界）",
    "flex_min": "flex_min(a, b, ...) → 窗口内最小值（手动公式中的弹性下轨/区间下界）",
    "__ROLLKW__": "__ROLLKW__(x) → 自定义滚动窗口聚合（DSL 展开占位，见落地表达式）",
    "ts_ewm_std": "ts_ewm_std(x, span=n) → 指数加权滚动标准差（近期权重更大的波动）",
    "delay": "delay(x, n) → x[t-n]（n 期滞后；同 ts_delay，x.delay(n) 形式亦可）",
    # ---- 字段补充（终验：cleaned-call 形态中出现但未登记）----
    "RSI_WILDER": "RSI_WILDER → Wilder 平滑版 RSI 相对强弱指数",
    "abs_ret": "abs_ret → 绝对收益 |ret|（日收益的绝对值）",
    "is_low_vol": "is_low_vol → 低量能状态标志（classify_volume_regime 输出）",
    "vol_ratio_cont": "vol_ratio_cont → 连续量比（持续跟踪的量比信号）",
    "ema": "ema(x, span=n) → 指数加权移动平均（ts_ema 的 DSL 简写；span 为衰减窗口）",
    "EMA30": "EMA30(x) → 30 期指数均线",
    "EMA10": "EMA10(x) → 10 期指数均线",
    "EMA15": "EMA15(x) → 15 期指数均线",
    "EMA6": "EMA6(x) → 6 期指数均线",
    "EMA_20": "EMA_20(x) → 20 期指数均线",
    "EMA_10": "EMA_10(x) → 10 期指数均线",
    "VWAP": "VWAP → 成交量加权均价（vwap 的大写简写；amount/volume）",
    "power": "power(x, y) → x 的 y 次方（负数底数 & 非整数指数 → NaN）",
    "minimum": "minimum(x, y) → 逐元素取最小值 min(x,y)",
    "maximum": "maximum(x, y) → 逐元素取最大值 max(x,y)",
    "gt": "gt(a, b) → a > b 的比较结果（1/0）",
    "ge": "ge(a, b) → a ≥ b 的比较结果（1/0）",
    "lt": "lt(a, b) → a < b 的比较结果（1/0）",
    "ts_var": "ts_var(x, n) → n 期滚动方差",
    "ts_ewm_var": "ts_ewm_var(x, span=n) → 指数加权方差",
    "sum_30": "sum_30(x) → 30 期滚动求和",
    "delay": "delay(x, n) → x[t-n]（n 期滞后；同 ts_delay；x.delay(n) 方法形式亦可）",
    "ATR_WILDER": "ATR_WILDER(n) → Wilder 平滑版平均真实波幅",
    "RSI_WILDER": "RSI_WILDER(x, n) → Wilder 平滑版 RSI 相对强弱指数（如 RSI_WILDER(AdjClose, 14)）",
    "z_score": "z_score(x) → Z-Score 标准化（zscore 的别名）",
    "is_high_vol": "is_high_vol → 高量能状态标志（classify_volume_regime 输出）",
    "amount_weighted_mean": "amount_weighted_mean(x, w) → 按成交额加权的均值",
    "volume_weighted_mean": "volume_weighted_mean(x, w) → 按成交量加权的均值",
}

# 额外把 FE canonical 全量（466 个里 470 DSL 用到的）也放一份：resolve 到中文
# 上面已按 DSL 出现情况补全；此处给出通用兜底说明生成器（可选）。
def _canonical_doc_map():
    """返回 FE canonical → 描述（用于需要时动态补齐）。"""
    import sys, json
    try:
        sys.path.insert(0, "/home/sunhaiwei/quant_projects")
        from factor_engine.cleaned_operators.registry import OperatorRegistry
        reg = OperatorRegistry()
        cat = getattr(reg, "_catalog", {})
        return {k: (v.get("description") or "") for k, v in cat.items()}
    except Exception:
        return {}


# ============================================================
# DSL 语法噪声（关键字/循环变量/参数名）→ 渲染时直接隐藏
# ============================================================
DSL_NOISE = {
    # Python / DSL 控制词
    "if", "else", "elif", "then", "endif", "For", "for", "while", "return", "def", "import",
    "from", "as", "pass", "break", "continue", "with", "of", "to", "by", "and", "or", "not",
    "in", "is", "on", "at", "via", "per", "over", "under", "above", "below", "between",
    "when", "whenever", "within", "into", "out", "off", "any", "all", "each", "some", "this",
    "that", "these", "those", "what", "which", "whose", "how", "why", "no", "yes", "the",
    "its", "both", "vs", "against", "during", "after", "before", "until", "unless", "minus",
    "plus", "times", "Default", "default", "otherwise", "If", "Else", "AND", "or_", "and_",
    "not_", "text", "full", "dry", "tight", "health", "res20", "frac", "se", "np",
    # 单字母 / 循环下标
    "t", "i", "j", "k", "n", "m", "r", "d", "e", "z", "x", "y", "w", "a", "b", "c", "s",
    "p", "q", "u", "v", "T", "I", "J", "K", "N", "M", "R", "D", "E", "Z", "X", "Y", "W",
    "A", "B", "C", "S", "P", "Q", "U", "V", "O", "H", "L", "F", "G",
    "t_", "r_", "r_t", "_t", "I_t", "C_t", "C_", "F_", "H20_", "sum_", "mean_", "std_",
    "V_", "V_short_", "V_long_", "EMA_", "close_", "vol_", "auth_t", "signal_t",
    "stress_accum_t", "drift_t", "short_drift_t", "long_drift_t", "w_t", "E_t", "close_loc_",
    "median20_", "high_", "prior_high_", "vol_ma20_", "vol_ma20_lag", "vol_lag", "max_",
    "min_", "rank_", "ts_rank_", "rolling_mean_", "_",
    # 参数名
    "span", "window", "period", "periods", "min_periods", "lag", "lead", "shift", "fill",
    "eps", "epsilon", "quantiles", "pctl", "percentile", "threshold", "method", "axis",
    "dropna", "n", "k", "p", "q", "day", "days", "minute", "minutes", "bar", "bars",
    # 英文通用词（非字段）
    "squared", "clipped", "scaled", "weighted", "average", "median", "mean", "std", "sum",
    "ratio", "total", "large", "small", "medium", "high", "low", "Large", "Small", "Medium",
    "High", "Low", "absolute", "relative", "cumulative", "binary", "integer", "float", "str",
    "bool", "classification", "continuous", "magnitude", "fraction", "percentage",
    "participation", "modifier", "path", "formula", "vs", "adjusted", "signed", "bounded",
    "consecutive", "lower", "upper", "positive", "negative", "daily", "minute", "session",
    "intraday", "overnight", "annual", "monthly", "weekly", "smoothed", "smoothing", "gated",
    "capped", "conditioned", "conditional", "recent", "reversed", "moving", "result", "final",
    "output", "base", "value", "nan", "NaN", "NaNs", "inf", "None", "True", "False",
    "Debt", "ROE", "debt", "roe", "pe", "pb", "cap", "assets", "Roughness_Ratio",
    "Volume_Ratio", "Trend", "SDC", "CS", "CL", "CLV", "OI", "price", "time", "series",
    "dollar", "alpha_tools", "evoalpha_dsl_see_land_evoalpha14_build_formulas", "MYDSL",
    "Return", "return", "returns", "Returns", "formula", "text", "session",
    # 英文文本/算子名（不应作为字段展示）
    "caps", "EMA", "ATR", "EWMA", "MA10", "Rolling", "EMA5", "classify_volume_regime",
    "MA", "SMA", "ROC", "RSI", "MOM", "MACD", "ADX", "WMA", "STDDEV",
    # 终验补充：cleaned-call 形态的语法/命名空间噪声（2026-08-29）
    "o", "col", "eq", "ne", "neg", "is_finite", "is_nan", "identity",
    "flex_max", "flex_min", "safe_div_null", "__ROLLKW__", "ts_ewm_std", "delay",
    "abs_ret", "RSI_WILDER", "is_low_vol", "vol_ratio_cont", "nan", "inf",
}


def apply_field_op_docs(FIELD_DOC: dict, OP_DOC: dict) -> None:
    """把补全字典合并进 rebuild_factor_detail_pages 的 FIELD_DOC / OP_DOC。"""
    FIELD_DOC.update(FIELD_DOC_BASE)
    FIELD_DOC.update(FIELD_DOC_EXTRA)
    OP_DOC.update(OP_DOC_EXTRA)
