
# =====================================================================
# R59 surface promotion (2026-09-21): reviewed daily-surface migrations,
# waves v2/v4/v5 of the parity harness (date-column panels, domain retry
# ladder, param-min clamping) plus pandas-only execution evidence for
# canonicals whose polars backend is unsupported (auto routes to pandas).
# Evidence: evidence/r59/parity/<canonical>.json; waves merged in
# evidence/r59/R59_PROMOTION_MERGE.json.
_R59_PROMOTIONS: dict[str, dict[str, str]] = {
    'CoppockCurve': {"review_id": 'r59-surface-promotion:CoppockCurve', "semantic_hash": 'e661578ca25a66cb', "approved_authoring_tier": "daily"},
    'HMA': {"review_id": 'r59-surface-promotion:HMA', "semantic_hash": '5c1cdc0af36db3eb', "approved_authoring_tier": "daily"},
    'QQE': {"review_id": 'r59-surface-promotion:QQE', "semantic_hash": '40a8d178768f8c65', "approved_authoring_tier": "daily"},
    'RSX': {"review_id": 'r59-surface-promotion:RSX', "semantic_hash": '4058b559a290fb2f', "approved_authoring_tier": "daily"},
    'acos_bounded': {"review_id": 'r59-surface-promotion:acos_bounded', "semantic_hash": 'b0af21dd1fcd1c98', "approved_authoring_tier": "daily"},
    'aq1_cash_flow_volatility': {"review_id": 'r59-surface-promotion:aq1_cash_flow_volatility', "semantic_hash": 'fd61705ff052419d', "approved_authoring_tier": "daily"},
    'asin_bounded': {"review_id": 'r59-surface-promotion:asin_bounded', "semantic_hash": 'b0af21dd1fcd1c98', "approved_authoring_tier": "daily"},
    'category_age': {"review_id": 'r59-surface-promotion:category_age', "semantic_hash": '4745bde223b4c028', "approved_authoring_tier": "daily"},
    'category_age_lower_bound': {"review_id": 'r59-surface-promotion:category_age_lower_bound', "semantic_hash": '4745bde223b4c028', "approved_authoring_tier": "daily"},
    'category_frequency': {"review_id": 'r59-surface-promotion:category_frequency', "semantic_hash": '4745bde223b4c028', "approved_authoring_tier": "daily"},
    'category_transition_rate': {"review_id": 'r59-surface-promotion:category_transition_rate', "semantic_hash": '4745bde223b4c028', "approved_authoring_tier": "daily"},
    'category_transition_surprise': {"review_id": 'r59-surface-promotion:category_transition_surprise', "semantic_hash": '4745bde223b4c028', "approved_authoring_tier": "daily"},
    'cos_phase': {"review_id": 'r59-surface-promotion:cos_phase', "semantic_hash": 'b0af21dd1fcd1c98', "approved_authoring_tier": "daily"},
    'cs1_monthly_lag_ratio': {"review_id": 'r59-surface-promotion:cs1_monthly_lag_ratio', "semantic_hash": 'fa2526c7e2fb6163', "approved_authoring_tier": "daily"},
    'cs1_seasonal_relative_rank': {"review_id": 'r59-surface-promotion:cs1_seasonal_relative_rank', "semantic_hash": 'a7078b3c49d491cc', "approved_authoring_tier": "daily"},
    'cs1_seasonal_residual_smoothness': {"review_id": 'r59-surface-promotion:cs1_seasonal_residual_smoothness', "semantic_hash": 'f661ad20a58733ef', "approved_authoring_tier": "daily"},
    'cs1_week_cycle_phase': {"review_id": 'r59-surface-promotion:cs1_week_cycle_phase', "semantic_hash": '6f32e64cf17f9b4d', "approved_authoring_tier": "daily"},
    'cs1_weekday_anomaly': {"review_id": 'r59-surface-promotion:cs1_weekday_anomaly', "semantic_hash": '6615deb66b5cb849', "approved_authoring_tier": "daily"},
    'cs1_weekday_effect_strength': {"review_id": 'r59-surface-promotion:cs1_weekday_effect_strength', "semantic_hash": 'f661ad20a58733ef', "approved_authoring_tier": "daily"},
    'cs1_weekday_lag_ratio': {"review_id": 'r59-surface-promotion:cs1_weekday_lag_ratio', "semantic_hash": '46af1141dcfb1f3c', "approved_authoring_tier": "daily"},
    'cs1_weekday_lag_zscore': {"review_id": 'r59-surface-promotion:cs1_weekday_lag_zscore', "semantic_hash": 'a7078b3c49d491cc', "approved_authoring_tier": "daily"},
    'cs1_weekly_harmonic_power': {"review_id": 'r59-surface-promotion:cs1_weekly_harmonic_power', "semantic_hash": '6f32e64cf17f9b4d', "approved_authoring_tier": "daily"},
    'cs_isolation_forest_score': {"review_id": 'r59-surface-promotion:cs_isolation_forest_score', "semantic_hash": 'ba91831e10a7c9fb', "approved_authoring_tier": "daily"},
    'cs_physical_panel_coverage': {"review_id": 'r59-surface-promotion:cs_physical_panel_coverage', "semantic_hash": 'fdde8815cb1b40db', "approved_authoring_tier": "daily"},
    'cs_rank_combined_churn': {"review_id": 'r59-surface-promotion:cs_rank_combined_churn', "semantic_hash": '5d86d44f9835b3d6', "approved_authoring_tier": "daily"},
    'cs_rank_composition_churn': {"review_id": 'r59-surface-promotion:cs_rank_composition_churn', "semantic_hash": '5d86d44f9835b3d6', "approved_authoring_tier": "daily"},
    'cs_tail_breadth': {"review_id": 'r59-surface-promotion:cs_tail_breadth', "semantic_hash": '68457d1931476839', "approved_authoring_tier": "daily"},
    'ep1_earnings_autocorr': {"review_id": 'r59-surface-promotion:ep1_earnings_autocorr', "semantic_hash": '6506b168195a32e4', "approved_authoring_tier": "daily"},
    'ep1_earnings_consistency': {"review_id": 'r59-surface-promotion:ep1_earnings_consistency', "semantic_hash": 'd124eccde435e831', "approved_authoring_tier": "daily"},
    'ep1_earnings_surprise_decay': {"review_id": 'r59-surface-promotion:ep1_earnings_surprise_decay', "semantic_hash": '5c941acd1668cf13', "approved_authoring_tier": "daily"},
    'ep1_roa_stability': {"review_id": 'r59-surface-promotion:ep1_roa_stability', "semantic_hash": '718ffa2414a042af', "approved_authoring_tier": "daily"},
    'erd_burst_duration': {"review_id": 'r59-surface-promotion:erd_burst_duration', "semantic_hash": 'ab8b8a388802a194', "approved_authoring_tier": "daily"},
    'erd_cross_events_spacing': {"review_id": 'r59-surface-promotion:erd_cross_events_spacing', "semantic_hash": 'b40c41b3c478f819', "approved_authoring_tier": "daily"},
    'erd_event_rate_decay_slope': {"review_id": 'r59-surface-promotion:erd_event_rate_decay_slope', "semantic_hash": '050c481109f036a2', "approved_authoring_tier": "daily"},
    'erd_event_response_amplitude': {"review_id": 'r59-surface-promotion:erd_event_response_amplitude', "semantic_hash": 'fe460a8ae037f96d', "approved_authoring_tier": "daily"},
    'erd_half_life_decay_count': {"review_id": 'r59-surface-promotion:erd_half_life_decay_count', "semantic_hash": '1cd75d66070c251c', "approved_authoring_tier": "daily"},
    'erd_marked_event_decay': {"review_id": 'r59-surface-promotion:erd_marked_event_decay', "semantic_hash": 'fe460a8ae037f96d', "approved_authoring_tier": "daily"},
    'erd_post_event_hazard': {"review_id": 'r59-surface-promotion:erd_post_event_hazard', "semantic_hash": '4e314f052472dd01', "approved_authoring_tier": "daily"},
    'erd_recency_decay': {"review_id": 'r59-surface-promotion:erd_recency_decay', "semantic_hash": 'd86091495f1d95ff', "approved_authoring_tier": "daily"},
    'erd_sign_consistent_decay': {"review_id": 'r59-surface-promotion:erd_sign_consistent_decay', "semantic_hash": 'b656e008473abfe3', "approved_authoring_tier": "daily"},
    'es1_earnings_cv': {"review_id": 'r59-surface-promotion:es1_earnings_cv', "semantic_hash": '08fcedfc52347dc1', "approved_authoring_tier": "daily"},
    'es1_earnings_mean_reversion_speed': {"review_id": 'r59-surface-promotion:es1_earnings_mean_reversion_speed', "semantic_hash": '6506b168195a32e4', "approved_authoring_tier": "daily"},
    'es1_negative_earnings_streak': {"review_id": 'r59-surface-promotion:es1_negative_earnings_streak', "semantic_hash": 'cffa98f8bfacffd6', "approved_authoring_tier": "daily"},
    'event_cluster_duration': {"review_id": 'r59-surface-promotion:event_cluster_duration', "semantic_hash": 'b85fef435145a025', "approved_authoring_tier": "daily"},
    'event_decay_window': {"review_id": 'r59-surface-promotion:event_decay_window', "semantic_hash": '68a0cf5414aa5938', "approved_authoring_tier": "daily"},
    'event_direction_imbalance': {"review_id": 'r59-surface-promotion:event_direction_imbalance', "semantic_hash": 'b85fef435145a025', "approved_authoring_tier": "daily"},
    'event_direction_persistence': {"review_id": 'r59-surface-promotion:event_direction_persistence', "semantic_hash": 'b85fef435145a025', "approved_authoring_tier": "daily"},
    'event_fano_excess': {"review_id": 'r59-surface-promotion:event_fano_excess', "semantic_hash": 'a387925812ecac07', "approved_authoring_tier": "daily"},
    'event_flip_density': {"review_id": 'r59-surface-promotion:event_flip_density', "semantic_hash": 'b85fef435145a025', "approved_authoring_tier": "daily"},
    'event_response_effective_events': {"review_id": 'r59-surface-promotion:event_response_effective_events', "semantic_hash": '5e8cb135611ff65f', "approved_authoring_tier": "daily"},
    'event_response_overlap_ratio': {"review_id": 'r59-surface-promotion:event_response_overlap_ratio', "semantic_hash": '5e8cb135611ff65f', "approved_authoring_tier": "daily"},
    'event_streak': {"review_id": 'r59-surface-promotion:event_streak', "semantic_hash": 'b85fef435145a025', "approved_authoring_tier": "daily"},
    'financial_snapshot_lag': {"review_id": 'r59-surface-promotion:financial_snapshot_lag', "semantic_hash": 'de1cfcc8b6ca623e', "approved_authoring_tier": "daily"},
    'fundamental_staleness_days': {"review_id": 'r59-surface-promotion:fundamental_staleness_days', "semantic_hash": 'fcc111064fa20944', "approved_authoring_tier": "daily"},
    'hfl_variance_ratio': {"review_id": 'r59-surface-promotion:hfl_variance_ratio', "semantic_hash": 'e21fae14ce33b4f4', "approved_authoring_tier": "daily"},
    'intra_neighbor_event_class': {"review_id": 'r59-surface-promotion:intra_neighbor_event_class', "semantic_hash": 'd35b1f3e788f100d', "approved_authoring_tier": "daily"},
    'intra_same_slot_zscore': {"review_id": 'r59-surface-promotion:intra_same_slot_zscore', "semantic_hash": '1c365d3cf0d61bac', "approved_authoring_tier": "daily"},
    'intra_state_count': {"review_id": 'r59-surface-promotion:intra_state_count', "semantic_hash": '0267de32ffa750f9', "approved_authoring_tier": "daily"},
    'lf1_herfindahl_volume': {"review_id": 'r59-surface-promotion:lf1_herfindahl_volume', "semantic_hash": '7fd30d280d8aa34f', "approved_authoring_tier": "daily"},
    'lf1_liquidity_decay_base': {"review_id": 'r59-surface-promotion:lf1_liquidity_decay_base', "semantic_hash": '1f33e04fa3c7ea4a', "approved_authoring_tier": "daily"},
    'lf1_market_share_turnover': {"review_id": 'r59-surface-promotion:lf1_market_share_turnover', "semantic_hash": '82c7d3df4ebea6a0', "approved_authoring_tier": "daily"},
    'lf1_mean_variance_turnover': {"review_id": 'r59-surface-promotion:lf1_mean_variance_turnover', "semantic_hash": '7581ca3c529e4405', "approved_authoring_tier": "daily"},
    'lf1_own_volume_share': {"review_id": 'r59-surface-promotion:lf1_own_volume_share', "semantic_hash": '6c8bc5a6bde6efd7', "approved_authoring_tier": "daily"},
    'lf1_turnover_distribution_skew': {"review_id": 'r59-surface-promotion:lf1_turnover_distribution_skew', "semantic_hash": 'a40ee51013d794a4', "approved_authoring_tier": "daily"},
    'lf1_volume_amplification': {"review_id": 'r59-surface-promotion:lf1_volume_amplification', "semantic_hash": 'a0ea1e04b02b8a23', "approved_authoring_tier": "daily"},
    'm1_cs_momentum_dispersion': {"review_id": 'r59-surface-promotion:m1_cs_momentum_dispersion', "semantic_hash": 'd343cec12e1c75d4', "approved_authoring_tier": "daily"},
    'm1_momentum_regime': {"review_id": 'r59-surface-promotion:m1_momentum_regime', "semantic_hash": '52c0176264e27c1c', "approved_authoring_tier": "daily"},
    'm1_momentum_speed_change': {"review_id": 'r59-surface-promotion:m1_momentum_speed_change', "semantic_hash": 'af440e4e043f5a89', "approved_authoring_tier": "daily"},
    'm1_momentum_stability': {"review_id": 'r59-surface-promotion:m1_momentum_stability', "semantic_hash": '114dc166ee9af05a', "approved_authoring_tier": "daily"},
    'm1_momentum_strength': {"review_id": 'r59-surface-promotion:m1_momentum_strength', "semantic_hash": '114dc166ee9af05a', "approved_authoring_tier": "daily"},
    'm1_rank_momentum_gap': {"review_id": 'r59-surface-promotion:m1_rank_momentum_gap', "semantic_hash": '50f3858e1d4f68af', "approved_authoring_tier": "daily"},
    'm1_ranked_momentum': {"review_id": 'r59-surface-promotion:m1_ranked_momentum', "semantic_hash": 'd343cec12e1c75d4', "approved_authoring_tier": "daily"},
    'negative_event_age': {"review_id": 'r59-surface-promotion:negative_event_age', "semantic_hash": 'b85fef435145a025', "approved_authoring_tier": "daily"},
    'negative_event_rate': {"review_id": 'r59-surface-promotion:negative_event_rate', "semantic_hash": 'b85fef435145a025', "approved_authoring_tier": "daily"},
    'ofi_abs_imbalance_trend': {"review_id": 'r59-surface-promotion:ofi_abs_imbalance_trend', "semantic_hash": 'c16283c3013f2e0a', "approved_authoring_tier": "daily"},
    'ofi_dominant_direction': {"review_id": 'r59-surface-promotion:ofi_dominant_direction', "semantic_hash": '4b74e55959a85694', "approved_authoring_tier": "daily"},
    'ofi_imbalance_agreement': {"review_id": 'r59-surface-promotion:ofi_imbalance_agreement', "semantic_hash": 'c16283c3013f2e0a', "approved_authoring_tier": "daily"},
    'ofi_imbalance_cv': {"review_id": 'r59-surface-promotion:ofi_imbalance_cv', "semantic_hash": 'c16283c3013f2e0a', "approved_authoring_tier": "daily"},
    'ofi_imbalance_persistence': {"review_id": 'r59-surface-promotion:ofi_imbalance_persistence', "semantic_hash": 'c16283c3013f2e0a', "approved_authoring_tier": "daily"},
    'ofi_reversal_rate': {"review_id": 'r59-surface-promotion:ofi_reversal_rate', "semantic_hash": 'c16283c3013f2e0a', "approved_authoring_tier": "daily"},
    'ofi_volume_flow_regime': {"review_id": 'r59-surface-promotion:ofi_volume_flow_regime', "semantic_hash": '4b74e55959a85694', "approved_authoring_tier": "daily"},
    'ofi_volume_imbalance': {"review_id": 'r59-surface-promotion:ofi_volume_imbalance', "semantic_hash": 'c16283c3013f2e0a', "approved_authoring_tier": "daily"},
    'ofi_zero_flow_balance': {"review_id": 'r59-surface-promotion:ofi_zero_flow_balance', "semantic_hash": 'c16283c3013f2e0a', "approved_authoring_tier": "daily"},
    'positive_event_age': {"review_id": 'r59-surface-promotion:positive_event_age', "semantic_hash": 'b85fef435145a025', "approved_authoring_tier": "daily"},
    'positive_event_rate': {"review_id": 'r59-surface-promotion:positive_event_rate', "semantic_hash": 'b85fef435145a025', "approved_authoring_tier": "daily"},
    'relation_distinct_count': {"review_id": 'r59-surface-promotion:relation_distinct_count', "semantic_hash": '3c8c95a9f2f52bf5', "approved_authoring_tier": "daily"},
    'report_asof': {"review_id": 'r59-surface-promotion:report_asof', "semantic_hash": 'a189f20b5925cc1d', "approved_authoring_tier": "daily"},
    'same_calendar_day_mean': {"review_id": 'r59-surface-promotion:same_calendar_day_mean', "semantic_hash": '6629c1e540247f0a', "approved_authoring_tier": "daily"},
    'same_calendar_month_return': {"review_id": 'r59-surface-promotion:same_calendar_month_return', "semantic_hash": 'c1e760f4656cb006', "approved_authoring_tier": "daily"},
    'signed_event_decay': {"review_id": 'r59-surface-promotion:signed_event_decay', "semantic_hash": '68a0cf5414aa5938', "approved_authoring_tier": "daily"},
    'signed_event_rate': {"review_id": 'r59-surface-promotion:signed_event_rate', "semantic_hash": 'b85fef435145a025', "approved_authoring_tier": "daily"},
    'sin_phase': {"review_id": 'r59-surface-promotion:sin_phase', "semantic_hash": 'b0af21dd1fcd1c98', "approved_authoring_tier": "daily"},
    'state_adaptive_deadband': {"review_id": 'r59-surface-promotion:state_adaptive_deadband', "semantic_hash": '45f8137f6824fade', "approved_authoring_tier": "daily"},
    'state_adaptive_slew_limit': {"review_id": 'r59-surface-promotion:state_adaptive_slew_limit', "semantic_hash": '85d883af8dbb6096', "approved_authoring_tier": "daily"},
    'state_age': {"review_id": 'r59-surface-promotion:state_age', "semantic_hash": '4745bde223b4c028', "approved_authoring_tier": "daily"},
    'state_episode_age': {"review_id": 'r59-surface-promotion:state_episode_age', "semantic_hash": '4745bde223b4c028', "approved_authoring_tier": "daily"},
    'state_episode_age_capped': {"review_id": 'r59-surface-promotion:state_episode_age_capped', "semantic_hash": '252e704ea46f6f62', "approved_authoring_tier": "daily"},
    'state_episode_age_lower_bound': {"review_id": 'r59-surface-promotion:state_episode_age_lower_bound', "semantic_hash": '4745bde223b4c028', "approved_authoring_tier": "daily"},
    'state_episode_censored_flag': {"review_id": 'r59-surface-promotion:state_episode_censored_flag', "semantic_hash": '4745bde223b4c028', "approved_authoring_tier": "daily"},
    'state_flip_age': {"review_id": 'r59-surface-promotion:state_flip_age', "semantic_hash": '4745bde223b4c028', "approved_authoring_tier": "daily"},
    'state_flip_density': {"review_id": 'r59-surface-promotion:state_flip_density', "semantic_hash": '4745bde223b4c028', "approved_authoring_tier": "daily"},
    'state_l1_turnover_prox': {"review_id": 'r59-surface-promotion:state_l1_turnover_prox', "semantic_hash": 'bee7927fc63a9679', "approved_authoring_tier": "daily"},
    'state_l2_partial_adjustment': {"review_id": 'r59-surface-promotion:state_l2_partial_adjustment', "semantic_hash": '60df243de483c159', "approved_authoring_tier": "daily"},
    'state_persistence': {"review_id": 'r59-surface-promotion:state_persistence', "semantic_hash": '4745bde223b4c028', "approved_authoring_tier": "daily"},
    'state_transition_count': {"review_id": 'r59-surface-promotion:state_transition_count', "semantic_hash": '4745bde223b4c028', "approved_authoring_tier": "daily"},
    'state_transition_rate': {"review_id": 'r59-surface-promotion:state_transition_rate', "semantic_hash": '4745bde223b4c028', "approved_authoring_tier": "daily"},
    'sv_net_flow_direction': {"review_id": 'r59-surface-promotion:sv_net_flow_direction', "semantic_hash": 'c16283c3013f2e0a', "approved_authoring_tier": "daily"},
    'sv_own_flow_fraction': {"review_id": 'r59-surface-promotion:sv_own_flow_fraction', "semantic_hash": 'c86fb125305702d2', "approved_authoring_tier": "daily"},
    'sv_self_relative_change': {"review_id": 'r59-surface-promotion:sv_self_relative_change', "semantic_hash": '96fa21d39dcc02f9', "approved_authoring_tier": "daily"},
    'sv_signed_volume_volatility': {"review_id": 'r59-surface-promotion:sv_signed_volume_volatility', "semantic_hash": 'c16283c3013f2e0a', "approved_authoring_tier": "daily"},
    'tod_close_midday_ratio': {"review_id": 'r59-surface-promotion:tod_close_midday_ratio', "semantic_hash": '49d98b1488a89dea', "approved_authoring_tier": "daily"},
    'tod_edge_activity': {"review_id": 'r59-surface-promotion:tod_edge_activity', "semantic_hash": 'a84a9477104d27a6', "approved_authoring_tier": "daily"},
    'tod_intraday_range_position': {"review_id": 'r59-surface-promotion:tod_intraday_range_position', "semantic_hash": '400c8c46524c44e8', "approved_authoring_tier": "daily"},
    'tod_open_midday_ratio': {"review_id": 'r59-surface-promotion:tod_open_midday_ratio', "semantic_hash": '1a6997787cb5dc52', "approved_authoring_tier": "daily"},
    'ts_abs_entropy_nats': {"review_id": 'r59-surface-promotion:ts_abs_entropy_nats', "semantic_hash": '249da95e182bc983', "approved_authoring_tier": "daily"},
    'ts_autocorrelation_time_initial_positive_sequence': {"review_id": 'r59-surface-promotion:ts_autocorrelation_time_initial_positive_sequence', "semantic_hash": 'a814d4b252a7e2ed', "approved_authoring_tier": "daily"},
    'ts_butterworth_lowpass_causal': {"review_id": 'r59-surface-promotion:ts_butterworth_lowpass_causal', "semantic_hash": '8ecfd1a86fc2456b', "approved_authoring_tier": "daily"},
    'ts_causal_local_linear_smoother': {"review_id": 'r59-surface-promotion:ts_causal_local_linear_smoother', "semantic_hash": 'd470a99fc7a267aa', "approved_authoring_tier": "daily"},
    'ts_cumulative_deviation_score': {"review_id": 'r59-surface-promotion:ts_cumulative_deviation_score', "semantic_hash": 'c808514c6830bceb', "approved_authoring_tier": "daily"},
    'ts_effective_turning_rate': {"review_id": 'r59-surface-promotion:ts_effective_turning_rate', "semantic_hash": '2dbcb854af4adcdf', "approved_authoring_tier": "daily"},
    'ts_expectile': {"review_id": 'r59-surface-promotion:ts_expectile', "semantic_hash": '300b3a8edc60844f', "approved_authoring_tier": "daily"},
    'ts_extremogram': {"review_id": 'r59-surface-promotion:ts_extremogram', "semantic_hash": '0cb0a011283fa35a', "approved_authoring_tier": "daily"},
    'ts_forbidden_ordinal_pattern_excess': {"review_id": 'r59-surface-promotion:ts_forbidden_ordinal_pattern_excess', "semantic_hash": 'ff556be804d50a86', "approved_authoring_tier": "daily"},
    'ts_forbidden_ordinal_pattern_signed_excess': {"review_id": 'r59-surface-promotion:ts_forbidden_ordinal_pattern_signed_excess', "semantic_hash": '9434ed348506e589', "approved_authoring_tier": "daily"},
    'ts_fractional_difference_discarded_weight_mass': {"review_id": 'r59-surface-promotion:ts_fractional_difference_discarded_weight_mass', "semantic_hash": '4d2b1512df8ed58b', "approved_authoring_tier": "daily"},
    'ts_hampel_filter_causal': {"review_id": 'r59-surface-promotion:ts_hampel_filter_causal', "semantic_hash": 'ef8101c686bac49e', "approved_authoring_tier": "daily"},
    'ts_hodges_lehmann_location': {"review_id": 'r59-surface-promotion:ts_hodges_lehmann_location', "semantic_hash": 'e126d05c07d84e5a', "approved_authoring_tier": "daily"},
    'ts_kramers_moyal_diffusion': {"review_id": 'r59-surface-promotion:ts_kramers_moyal_diffusion', "semantic_hash": '22219d60495e6218', "approved_authoring_tier": "daily"},
    'ts_kramers_moyal_drift': {"review_id": 'r59-surface-promotion:ts_kramers_moyal_drift', "semantic_hash": '22219d60495e6218', "approved_authoring_tier": "daily"},
    'ts_lo_mackinlay_vr': {"review_id": 'r59-surface-promotion:ts_lo_mackinlay_vr', "semantic_hash": '445ea90d9d89ee16', "approved_authoring_tier": "daily"},
    'ts_lo_mackinlay_z': {"review_id": 'r59-surface-promotion:ts_lo_mackinlay_z', "semantic_hash": '445ea90d9d89ee16', "approved_authoring_tier": "daily"},
    'ts_matrix_profile_motif_frequency': {"review_id": 'r59-surface-promotion:ts_matrix_profile_motif_frequency', "semantic_hash": '3d6fae12ecbd5215', "approved_authoring_tier": "daily"},
    'ts_matrix_profile_neighbor_dispersion': {"review_id": 'r59-surface-promotion:ts_matrix_profile_neighbor_dispersion', "semantic_hash": 'e7c80b0d61d1f8ed', "approved_authoring_tier": "daily"},
    'ts_mean_abs_deviation': {"review_id": 'r59-surface-promotion:ts_mean_abs_deviation', "semantic_hash": 'a0e877dc2bf44e9c', "approved_authoring_tier": "daily"},
    'ts_mean_abs_deviation_strict': {"review_id": 'r59-surface-promotion:ts_mean_abs_deviation_strict', "semantic_hash": '2c22c62b204ff4b4', "approved_authoring_tier": "daily"},
    'ts_mean_reversion_ou_approx_half_life': {"review_id": 'r59-surface-promotion:ts_mean_reversion_ou_approx_half_life', "semantic_hash": 'cf9832a6a81bc1b2', "approved_authoring_tier": "daily"},
    'ts_mean_reversion_ou_approx_half_life_prior': {"review_id": 'r59-surface-promotion:ts_mean_reversion_ou_approx_half_life_prior', "semantic_hash": 'dc1c3563af669cab', "approved_authoring_tier": "daily"},
    'ts_median3_causal': {"review_id": 'r59-surface-promotion:ts_median3_causal', "semantic_hash": '446379e9e71b587e', "approved_authoring_tier": "daily"},
    'ts_median_abs_deviation': {"review_id": 'r59-surface-promotion:ts_median_abs_deviation', "semantic_hash": 'a0e877dc2bf44e9c', "approved_authoring_tier": "daily"},
    'ts_pickands_tail_index': {"review_id": 'r59-surface-promotion:ts_pickands_tail_index', "semantic_hash": '2e58bd61a958fd63', "approved_authoring_tier": "daily"},
    'ts_quantilogram': {"review_id": 'r59-surface-promotion:ts_quantilogram', "semantic_hash": '0cb0a011283fa35a', "approved_authoring_tier": "daily"},
    'ts_robust_ema': {"review_id": 'r59-surface-promotion:ts_robust_ema', "semantic_hash": 'c76dc05cccf7d625', "approved_authoring_tier": "daily"},
    'ts_rolling_median_causal': {"review_id": 'r59-surface-promotion:ts_rolling_median_causal', "semantic_hash": '6785a3a06694476f', "approved_authoring_tier": "daily"},
    'ts_rqa_determinism_fixed_rr': {"review_id": 'r59-surface-promotion:ts_rqa_determinism_fixed_rr', "semantic_hash": 'ecbabe7a17b005d3', "approved_authoring_tier": "daily"},
    'ts_rqa_laminarity_fixed_rr': {"review_id": 'r59-surface-promotion:ts_rqa_laminarity_fixed_rr', "semantic_hash": 'ecbabe7a17b005d3', "approved_authoring_tier": "daily"},
    'ts_spectral_lowpass_trailing': {"review_id": 'r59-surface-promotion:ts_spectral_lowpass_trailing', "semantic_hash": '8462399ce60b4d00', "approved_authoring_tier": "daily"},
    'ts_super_smoother': {"review_id": 'r59-surface-promotion:ts_super_smoother', "semantic_hash": '76f8ceebb7f994a3', "approved_authoring_tier": "daily"},
    'ts_variance_ratio_proxy': {"review_id": 'r59-surface-promotion:ts_variance_ratio_proxy', "semantic_hash": 'eeee05913e6a9413', "approved_authoring_tier": "daily"},
    'val1_discount_regime_share': {"review_id": 'r59-surface-promotion:val1_discount_regime_share', "semantic_hash": 'aaf4a4fd9b43f3b4', "approved_authoring_tier": "daily"},
    'val1_earnings_yield_ma_diff': {"review_id": 'r59-surface-promotion:val1_earnings_yield_ma_diff', "semantic_hash": '7f803404e7c6866d', "approved_authoring_tier": "daily"},
    'val1_earnings_yield_persistence': {"review_id": 'r59-surface-promotion:val1_earnings_yield_persistence', "semantic_hash": 'b46e072e4585ee28', "approved_authoring_tier": "daily"},
    'val1_earnings_yield_slope': {"review_id": 'r59-surface-promotion:val1_earnings_yield_slope', "semantic_hash": '9c83ad5d3c0908e8', "approved_authoring_tier": "daily"},
    'val1_equity_yield_dispersion': {"review_id": 'r59-surface-promotion:val1_equity_yield_dispersion', "semantic_hash": 'bac4b7939503a9db', "approved_authoring_tier": "daily"},
    'val1_fcf_yield_growth': {"review_id": 'r59-surface-promotion:val1_fcf_yield_growth', "semantic_hash": '538bf6ca933cdee0', "approved_authoring_tier": "daily"},
    'val1_valuation_percentile_own': {"review_id": 'r59-surface-promotion:val1_valuation_percentile_own', "semantic_hash": '97416deb074e880c', "approved_authoring_tier": "daily"},
    'val1_valuation_stat_spread': {"review_id": 'r59-surface-promotion:val1_valuation_stat_spread', "semantic_hash": '9f05bf798b97d291', "approved_authoring_tier": "daily"},
    'val1_valuation_z_own': {"review_id": 'r59-surface-promotion:val1_valuation_z_own', "semantic_hash": '97416deb074e880c', "approved_authoring_tier": "daily"},
    'val1_valuations_lag_component': {"review_id": 'r59-surface-promotion:val1_valuations_lag_component', "semantic_hash": '81714f959fb233d5', "approved_authoring_tier": "daily"},
    'vax_liquidity_penalty_exposure': {"review_id": 'r59-surface-promotion:vax_liquidity_penalty_exposure', "semantic_hash": 'bbc3323681175640', "approved_authoring_tier": "daily"},
    'vv1_dispersion_vol': {"review_id": 'r59-surface-promotion:vv1_dispersion_vol', "semantic_hash": '40eedf96ae815a55', "approved_authoring_tier": "daily"},
    'vv1_downside_vol_share': {"review_id": 'r59-surface-promotion:vv1_downside_vol_share', "semantic_hash": '114dc166ee9af05a', "approved_authoring_tier": "daily"},
    'vv1_fractional_share': {"review_id": 'r59-surface-promotion:vv1_fractional_share', "semantic_hash": '510c623fbb360b4b', "approved_authoring_tier": "daily"},
    'vv1_long_short_vol_beta': {"review_id": 'r59-surface-promotion:vv1_long_short_vol_beta', "semantic_hash": '510c623fbb360b4b', "approved_authoring_tier": "daily"},
    'vv1_vol_acceleration': {"review_id": 'r59-surface-promotion:vv1_vol_acceleration', "semantic_hash": '6dd54e326cc0a28f', "approved_authoring_tier": "daily"},
    'vv1_vol_level_score': {"review_id": 'r59-surface-promotion:vv1_vol_level_score', "semantic_hash": 'a96f52aec0063c63', "approved_authoring_tier": "daily"},
    'vv1_vol_of_vol': {"review_id": 'r59-surface-promotion:vv1_vol_of_vol', "semantic_hash": '114dc166ee9af05a', "approved_authoring_tier": "daily"},
    'WMA': {"review_id": 'r59-surface-promotion-pandasonly:WMA', "semantic_hash": '27069cad30a82cf2', "approved_authoring_tier": "daily"},  # pandas-only
    'same_clock_lag': {"review_id": 'r59-surface-promotion-pandasonly:same_clock_lag', "semantic_hash": 'c2e79604a3b0a732', "approved_authoring_tier": "daily"},  # pandas-only
    'ts_activity_spectral_entropy': {"review_id": 'r59-surface-promotion-pandasonly:ts_activity_spectral_entropy', "semantic_hash": '205777716b0bad8f', "approved_authoring_tier": "daily"},  # pandas-only
    'ts_ar_fitted_value': {"review_id": 'r59-surface-promotion-pandasonly:ts_ar_fitted_value', "semantic_hash": '2f07898a31f54aa3', "approved_authoring_tier": "daily"},  # pandas-only
    'ts_ar_in_sample_resid': {"review_id": 'r59-surface-promotion-pandasonly:ts_ar_in_sample_resid', "semantic_hash": '2f07898a31f54aa3', "approved_authoring_tier": "daily"},  # pandas-only
    'ts_detrended_level_spectral_entropy': {"review_id": 'r59-surface-promotion-pandasonly:ts_detrended_level_spectral_entropy', "semantic_hash": 'e11d6af9498a398c', "approved_authoring_tier": "daily"},  # pandas-only
    'ts_l1_trend_filter_trailing': {"review_id": 'r59-surface-promotion-pandasonly:ts_l1_trend_filter_trailing', "semantic_hash": 'f6e01f446b57aa7d', "approved_authoring_tier": "daily"},  # pandas-only
    'ts_mcginley_dynamic': {"review_id": 'r59-surface-promotion-pandasonly:ts_mcginley_dynamic', "semantic_hash": 'b5d3b3dddcb2c92d', "approved_authoring_tier": "daily"},  # pandas-only
    'ts_nlms_filter': {"review_id": 'r59-surface-promotion-pandasonly:ts_nlms_filter', "semantic_hash": 'cdbef8e4fce358e6', "approved_authoring_tier": "daily"},  # pandas-only
    'ts_one_euro_filter': {"review_id": 'r59-surface-promotion-pandasonly:ts_one_euro_filter', "semantic_hash": '83604971cb4c1dd2', "approved_authoring_tier": "daily"},  # pandas-only
    'ts_poly2_forecast_error': {"review_id": 'r59-surface-promotion-pandasonly:ts_poly2_forecast_error', "semantic_hash": '0568e435a2f5ba79', "approved_authoring_tier": "daily"},  # pandas-only
    'ts_poly2_forecast_error_z': {"review_id": 'r59-surface-promotion-pandasonly:ts_poly2_forecast_error_z', "semantic_hash": '0568e435a2f5ba79', "approved_authoring_tier": "daily"},  # pandas-only
    'ts_poly2_prior_coeff': {"review_id": 'r59-surface-promotion-pandasonly:ts_poly2_prior_coeff', "semantic_hash": '0568e435a2f5ba79', "approved_authoring_tier": "daily"},  # pandas-only
    'ts_return_spectral_entropy': {"review_id": 'r59-surface-promotion-pandasonly:ts_return_spectral_entropy', "semantic_hash": '199748c064caf9aa', "approved_authoring_tier": "daily"},  # pandas-only
    'ts_rls_filter': {"review_id": 'r59-surface-promotion-pandasonly:ts_rls_filter', "semantic_hash": '57f8bc141060c564', "approved_authoring_tier": "daily"},  # pandas-only
    'ts_ssa_denoise_trailing': {"review_id": 'r59-surface-promotion-pandasonly:ts_ssa_denoise_trailing', "semantic_hash": '1117731d573233d9', "approved_authoring_tier": "daily"},  # pandas-only
    'ts_total_variation_filter_trailing': {"review_id": 'r59-surface-promotion-pandasonly:ts_total_variation_filter_trailing', "semantic_hash": '0ace6112ba7c7573', "approved_authoring_tier": "daily"},  # pandas-only
    'ts_vidya': {"review_id": 'r59-surface-promotion-pandasonly:ts_vidya', "semantic_hash": '3ac66db92098c9f1', "approved_authoring_tier": "daily"},  # pandas-only
    'ts_wavelet_shrinkage_trailing': {"review_id": 'r59-surface-promotion-pandasonly:ts_wavelet_shrinkage_trailing', "semantic_hash": '5352ca02f4f31147', "approved_authoring_tier": "daily"},  # pandas-only
    'years_since_date': {"review_id": 'r59-surface-promotion-pandasonly:years_since_date', "semantic_hash": '47a2c219b68eb392', "approved_authoring_tier": "daily"},  # pandas-only
}
for _c, _m in _R59_PROMOTIONS.items():
    register_daily_migration(_c, review_id=_m["review_id"], semantic_hash=_m["semantic_hash"], approved_authoring_tier=_m["approved_authoring_tier"])
# =====================================================================
