"""A-share field glossary: canonical field name -> Chinese description.

Authored descriptions for every field declared in ``catalog.py``.  The ``_f``
helper looks up the description here when the declaration does not pass an
explicit one, so every FieldSpec carries a human-readable caliber.

口径来源：COS lqtp 数据字典、data_access/docs/用户使用手册.md §6.2、
以及各表 _table() 元数据注释。金额类字段默认人民币元（CNY）；
财报类字段为报告期（ReportPeriodEndDate）累计值，PIT 以 PubDate 为知识时间。
"""
from __future__ import annotations

FIELD_DESCRIPTIONS: dict[str, str] = {
    # ------------------------------------------------------------------
    # StockBalance — 资产负债表（报告期，CNY）
    # ------------------------------------------------------------------
    "account_receivable": "应收账款：销售商品或提供劳务应向客户收取的款项",
    "accounts_payable": "应付账款：因采购商品或接受劳务应向供应商支付的款项",
    "advance_peceipts": "预收款项：预先收取但尚未确认收入的款项",
    "bill_receivable": "应收票据：持有的商业汇票（银行承兑/商业承兑）面值",
    "biological_assets": "生物资产：农业活动中持有的有生命的动物与植物",
    "bond_invest": "债权投资：以摊余成本计量的债券类投资",
    "bonds_payable": "应付债券：发行的债券面值及应付利息",
    "borrowing_capital": "拆入资金：从同业及其他金融机构借入的款项",
    "borrowing_from_centralbank": "向中央银行借款：金融类企业向央行借入的款项",
    "bought_sellback_assets": "买入返售金融资产：按返售协议先买入再卖出的证券款项",
    "capital_reserve_fund": "资本公积：股本溢价及其他资本性公积",
    "cash_equivalents": "货币资金：库存现金、银行存款及其他货币资金",
    "commission_payable": "应付手续费及佣金：应付未付的手续费与佣金",
    "construction_in_progress": "在建工程：尚未完工转固的工程建造支出",
    "construction_materials": "工程物资：为在建工程准备的材料物资",
    "contract_assets": "合同资产：已履约但收款权利还取决于其他履约义务的资产",
    "contract_liabilities": "合同负债：已收客户对价而应向客户转让商品的义务",
    "current_assets": "流动资产合计：一年内可变现或耗用的资产总额",
    "current_liabilities": "流动负债合计：一年内需偿还的负债总额",
    "deferred_earning": "递延收益：尚待确认的政府补助等收益",
    "deferred_earning_current": "递延收益（流动部分）：一年内将确认的递延收益",
    "deferred_tax_assets": "递延所得税资产：可抵扣暂时性差异产生的所得税资产",
    "deferred_tax_liabilities": "递延所得税负债：应纳税暂时性差异产生的所得税负债",
    "deposit_in_interbank": "存放同业：存放于同业及其他金融机构的款项",
    "derivative_financial_asset": "衍生金融资产：以公允价值计量的衍生工具资产头寸",
    "derivative_financial_liability": "衍生金融负债：以公允价值计量的衍生工具负债头寸",
    "development_expenditure": "开发支出：满足资本化条件的研发支出",
    "dividend_payable": "应付股利：已宣告但尚未支付的股利",
    "dividend_receivable": "应收股利：被投资单位已宣告未发放的股利",
    "employee_payable": "应付职工薪酬：应付未付的工资、奖金、社保等",
    "estimate_liability": "预计负债：未决诉讼、担保等或有事项的预计义务",
    "estimate_liability_current": "预计负债（流动部分）：一年内预计清偿的部分",
    "fixed_assets": "固定资产：房屋、设备等有形资产的原值减累计折旧",
    "fixed_assets_liquidation": "固定资产清理：处置固定资产过程中的过渡科目",
    "foreign_currency_report_conv_diff": "外币报表折算差额：外币报表折算产生的权益调整",
    "goodwill": "商誉：并购对价超过可辨认净资产公允价值的部分",
    "hold_for_sale_assets": "持有待售资产（旧准则列报）：计划出售的资产",
    "hold_sale_asset": "持有待售资产：已决定出售且可立即出售的资产",
    "hold_sale_liability": "持有待售负债：与持有待售资产对应的负债",
    "hold_to_maturity_investments": "持有至到期投资：有明确意图持有到期的债券投资",
    "insurance_contract_reserves": "保险合同准备金：保险公司计提的寿险/产险责任准备金",
    "insurance_receivables": "应收保费：已确认但尚未收到的保费",
    "intangible_assets": "无形资产：专利、商标、土地使用权等无实物形态的资产",
    "interest_payable": "应付利息：已计提尚未支付的借款/债券利息",
    "interest_receivable": "应收利息：已计提尚未收到的利息",
    "inventory": "存货：原材料、在产品、库存商品等",
    "invested_capital": "投入资本：股东与债权人投入企业经营的全部资本",
    "investment_property": "投资性房地产：为赚取租金或增值持有的房地产",
    "lease_liability": "租赁负债：新租赁准则下尚未支付的租赁付款额现值",
    "lend_capital": "拆出资金：拆放给同业及其他金融机构的款项",
    "loan_and_advance": "发放贷款和垫款：银行类客户贷款及垫款",
    "loan_and_advance_current_assets": "发放贷款及垫款（列示于流动资产部分）",
    "loan_and_advance_noncurrent_assets": "发放贷款及垫款（列示于非流动资产部分）",
    "long_deferred_expense": "长期待摊费用：摊销期超过一年的待摊支出",
    "long_term_equity_investment": "长期股权投资：对联营/合营及子公司的股权投资",
    "longterm_account_payable": "长期应付款：一年以上的应付引进设备款等",
    "longterm_loan": "长期借款：期限超过一年的借款",
    "longterm_receivable_account": "长期应收款：融资租赁等一年以上的应收款项",
    "longterm_salaries_payable": "长期应付职工薪酬：离职后福利等长期薪酬义务",
    "minority_interest": "少数股东权益：子公司净资产中归属少数股东的部分",
    "non_current_asset_in_one_year": "一年内到期的非流动资产：即将到期重分类的长期资产",
    "non_current_liability_in_one_year": "一年内到期的非流动负债：即将到期重分类的长期负债",
    "notes_payable": "应付票据：开出并承兑的商业汇票",
    "oil_gas_assets": "油气资产：油气开采相关的井及相关设施",
    "ordinary_risk_reserve_fund": "一般风险准备：从净利润中计提的风险准备（金融类）",
    "other_bond_invest": "其他债权投资：以公允价值计量且变动计入其他综合收益的债券投资",
    "other_comprehensive_income": "其他综合收益：未在损益中确认的利得与损失",
    "other_current_assets": "其他流动资产：未单独列示的流动资产",
    "other_current_liability": "其他流动负债：未单独列示的流动负债",
    "other_equity_tools": "其他权益工具：优先股、永续债等权益类工具",
    "other_equity_tools_invest": "其他权益工具投资：指定为 FVOCI 的非交易性权益投资",
    "other_non_current_assets": "其他非流动资产：未单独列示的非流动资产",
    "other_non_current_financial_assets": "其他非流动金融资产：以公允价值计量的非流动金融资产",
    "other_non_current_liability": "其他非流动负债：未单独列示的非流动负债",
    "other_payable": "其他应付款：与经营无直接关系的应付暂收款项",
    "other_receivable": "其他应收款：非主营应收的往来款、押金等",
    "paidin_capital": "实收资本（股本）：股东实际缴入的注册资本",
    "pepertual_liability_equity": "永续债（权益工具口径）：计入权益的永续债",
    "pepertual_liability_noncurrent": "永续债（非流动负债口径）：计入负债的永续债",
    "preferred_shares_equity": "优先股（权益工具口径）：计入权益的优先股",
    "preferred_shares_noncurrent": "优先股（非流动负债口径）：计入负债的优先股",
    "prepayments": "预付款项：按合同预付给供应商的款项",
    "proxy_secu_proceeds": "代理买卖证券款：证券公司代理客户买卖证券的往来款",
    "pub_date": "公告披露日：财报对外披露日期，作为 PIT 知识时间（严格 PIT 用次一交易日）",
    "receivable_fin": "应收款项融资：以公允价值计量且变动计入其他综合收益的应收票据等",
    "receivings_from_vicariously_sold_securities": "代理承销证券款：代客户承销发行证券的往来款",
    "reinsurance_contract_reserves_receivable": "应收分保合同准备金：应向再保险分入方收取的准备金",
    "reinsurance_payables": "应付分保账款：再保险业务应付分出方款项",
    "reinsurance_receivables": "应收分保账款：再保险业务应从分入方收取款项",
    "report_period_end_date": "报告期截止日：财报覆盖期间的截止日期（如 2025-12-31）",
    "retained_profit": "未分配利润：历年累积未分配的净利润",
    "settlement_provi": "结算备付金：证券公司为证券交易清算存放的款项",
    "shareholders_equity": "归属于母公司所有者权益：合并报表中归属母公司股东的净资产",
    "shortterm_loan": "短期借款：一年以内的借款",
    "sold_buyback_secu_proceeds": "卖出回购金融资产款：按回购协议先卖出再买入的证券款项",
    "specific_account_payable": "专项应付款：政府投入等具有专项用途的应付款",
    "specific_reserves": "专项储备：安全生产费等专项用途的权益储备",
    "surplus_reserve_fund": "盈余公积：从净利润中提取的法定与任意盈余公积",
    "taxes_payable": "应交税费：增值税、所得税等应交未交税费",
    "total_assets": "资产总计：流动与非流动资产合计",
    "total_debt": "带息债务合计：短期借款、长期借款、应付债券等计息负债之和",
    "total_liabilities": "负债合计：流动与非流动负债合计",
    "total_non_current_assets": "非流动资产合计：一年以上变现/耗用的资产总额",
    "total_non_current_liability": "非流动负债合计：一年以上需偿还的负债总额",
    "total_owner_equities": "股东权益合计（不含少数股东权益）",
    "total_sheet_owner_equities": "资产负债表股东权益总计（含少数股东权益）",
    "trading_assets": "交易性金融资产：以公允价值计量且变动计入当期损益的金融资产",
    "trading_liability": "交易性金融负债：以公允价值计量且变动计入当期损益的金融负债",
    "treasury_stock": "库存股：公司回购持有的本公司股份（权益减项）",
    "update_time": "数据入库时间：COS 写入时间戳，仅作快内排序，不可作历史修订时钟",
    "usufruct_assets": "使用权资产：新租赁准则下确认的租赁使用权",
    # ------------------------------------------------------------------
    # StockCashFlow — 现金流量表（报告期，CNY）
    # ------------------------------------------------------------------
    "borrowing_repayment": "偿还借款支付的现金：偿还本金支付的现金",
    "cash_and_equivalents_at_end": "期末现金及现金等价物余额",
    "cash_equivalent_increase": "现金及现金等价物净增加额",
    "cash_equivalents_at_beginning": "期初现金及现金等价物余额",
    "cash_from_bonds_issue": "发行债券收到的现金",
    "cash_from_borrowing": "取得借款收到的现金",
    "cash_from_invest": "吸收投资收到的现金（筹资活动，含发行股票）",
    "cash_from_mino_s_invest_sub": "子公司吸收少数股东投资收到的现金",
    "dividend_interest_payment": "分配股利、利润或偿付利息支付的现金",
    "exchange_rate_change_effect": "汇率变动对现金及现金等价物的影响",
    "financing_cash_flow": "筹资活动产生的现金流量净额",
    "fix_intan_other_asset_acquis_cash": "购建固定资产、无形资产和其他长期资产支付的现金（资本开支）",
    "fix_intan_other_asset_dispo_cash": "处置固定资产、无形资产和其他长期资产收回的现金净额",
    "goods_and_services_cash_paid": "购买商品、接受劳务支付的现金",
    "goods_sale_and_service_render_cash": "销售商品、提供劳务收到的现金",
    "handling_charges_and_commission": "手续费及佣金相关现金流量（金融类报表科目）",
    "impawned_loan_net_increase": "质押贷款净增加额",
    "interest_and_commission_cashin": "收到的利息及手续费佣金（金融类）",
    "invest_cash_paid": "投资支付的现金（对外股权/债权投资）",
    "invest_proceeds": "取得投资收益收到的现金（分红、利息）",
    "invest_withdrawal_cash": "收回投资收到的现金（本金部分）",
    "investing_cash_flow": "投资活动产生的现金流量净额",
    "net_borrowing_from_central_bank": "向中央银行借款净增加额（金融类）",
    "net_borrowing_from_finance_co": "向其他金融机构拆入资金净增加额",
    "net_buyback": "回购业务资金净增加额（买入返售/卖出回购）",
    "net_cash_deal_subcompany": "处置子公司及其他营业单位收到的现金净额",
    "net_cash_from_sub_company": "取得子公司及其他营业单位支付的现金净额",
    "net_cash_received_from_reinsurance_business": "收到再保险业务现金净额",
    "net_deal_trading_assets": "交易性金融资产净增加额（金融类）",
    "net_deposit_in_cb_and_ib": "客户存款和同业存放款项净增加额（金融类）",
    "net_deposit_increase": "客户存款净增加额（金融类）",
    "net_increase_in_placements": "同业及其他金融机构存放款项净增加额（金融类）",
    "net_insurer_deposit_investment": "保户储金及投资款净增加额（保险类）",
    "net_loan_and_advance_increase": "客户贷款及垫款净增加额（金融类）",
    "net_original_insurance_cash": "收到原保险合同保费取得的现金",
    "operating_cash_flow": "经营活动产生的现金流量净额（OCF）",
    "original_compensation_paid": "支付原保险合同赔付款项的现金",
    "other_cash_from_invest_act": "收到其他与投资活动有关的现金",
    "other_cash_to_invest_act": "支付其他与投资活动有关的现金",
    "other_cashin_related_operate": "收到其他与经营活动有关的现金",
    "other_finance_act_cash": "收到其他与筹资活动有关的现金",
    "other_finance_act_payment": "支付其他与筹资活动有关的现金",
    "other_operate_cash_paid": "支付其他与经营活动有关的现金",
    "policy_dividend_cash_paid": "支付保单红利的现金",
    "proceeds_from_sub_to_mino_s": "子公司支付给少数股东的股利或利润",
    "pub_date": "公告披露日：财报对外披露日期，作为 PIT 知识时间",
    "report_period_end_date": "报告期截止日：财报覆盖期间的截止日期",
    "staff_behalf_paid": "支付给职工以及为职工支付的现金",
    "subtotal_finance_cash_inflow": "筹资活动现金流入小计",
    "subtotal_finance_cash_outflow": "筹资活动现金流出小计",
    "subtotal_invest_cash_inflow": "投资活动现金流入小计",
    "subtotal_invest_cash_outflow": "投资活动现金流出小计",
    "subtotal_operate_cash_inflow": "经营活动现金流入小计",
    "subtotal_operate_cash_outflow": "经营活动现金流出小计",
    "tax_levy_refund": "收到的税费返还",
    "tax_payments": "支付的各项税费",
    "update_time": "数据入库时间：COS 写入时间戳，仅作快内排序",
    # ------------------------------------------------------------------
    # StockIncome — 利润表（报告期，CNY）
    # ------------------------------------------------------------------
    "administration_expense": "管理费用：行政管理部门发生的费用",
    "asset_deal_income": "资产处置收益：处置固定资产、无形资产等产生的利得",
    "asset_impairment_loss": "资产减值损失：存货、固定资产等减值计提",
    "basic_eps": "基本每股收益：归属于母公司净利润除以加权平均股本（元/股）",
    "ci_minority_owners": "综合收益总额（归属少数股东部分）",
    "ci_parent_company_owners": "综合收益总额（归属母公司股东部分）",
    "commission_expense": "手续费及佣金支出（金融类）",
    "commission_income": "手续费及佣金收入（金融类）",
    "credit_impairment_loss": "信用减值损失：应收款项、债权投资等信用减值计提",
    "diluted_eps": "稀释每股收益：考虑潜在稀释股份后的每股收益（元/股）",
    "discon_operate_net_profit": "终止经营净利润：已终止经营业务的净利润",
    "disposal_loss_non_current_liability": "非流动资产处置损失",
    "exchange_income": "汇兑收益（金融类报表科目）",
    "fair_value_variable_income": "公允价值变动收益：持有资产公允价值变动计损益部分",
    "financial_expense": "财务费用：利息支出、汇兑损益及手续费等",
    "gross_profit": "营业毛利：营业收入减营业成本",
    "income_tax_expense": "所得税费用：当期与递延所得税合计",
    "interest_cost_fin": "利息支出（金融类报表科目）",
    "interest_expense": "利息费用：借款、债券等融资利息支出",
    "interest_income": "利息收入：存款、债券等产生的利息",
    "interest_income_fin": "利息收入（金融类报表科目）",
    "invest_income_associates": "对联营企业和合营企业的投资收益（权益法）",
    "investment_income": "投资收益：处置投资损益、分红及理财收益等",
    "minority_profit": "少数股东损益：净利润中归属少数股东的部分",
    "net_open_hedge_income": "净敞口套期收益：套期会计下净敞口套期产生的损益",
    "net_pay_insurance_claims": "赔付支出净额（保险类）",
    "net_profit": "净利润：利润总额减所得税费用",
    "non_operating_expense": "营业外支出：与经营无直接关系的支出（捐赠、罚没等）",
    "non_operating_revenue": "营业外收入：与经营无直接关系的收入（政府补助、罚没等）",
    "nopat": "税后净营业利润（NOPAT）：息税前利润按实际税率调整后",
    "np_parent_company_owners": "归属于母公司股东的净利润（归母净利润）",
    "operating_cost": "营业成本：与营业收入对应的直接成本",
    "operating_profit": "营业利润：收入减成本费用（含投资收益等）",
    "operating_revenue": "营业收入：主营与其他业务收入合计",
    "operating_tax_surcharges": "税金及附加：消费税、城建税、教育费附加等",
    "other_composite_income": "其他综合收益：不能重分类进损益及可重分类部分合计",
    "other_composite_income_mino_at": "其他综合收益（归属少数股东部分）",
    "other_earnings": "其他收益：与日常经营相关的政府补助等",
    "policy_dividend_payout": "保单红利支出（保险类）",
    "premiums_earned": "已赚保费：保险类企业确认的保费收入",
    "pub_date": "公告披露日：财报对外披露日期，作为 PIT 知识时间",
    "rd_expenses": "研发费用：研究与开发阶段费用化支出",
    "refunded_premiums": "退保金（保险类）",
    "reinsurance_cost": "分出保费（再保险成本）",
    "report_period_end_date": "报告期截止日：财报覆盖期间的截止日期",
    "selling_expense": "销售费用：销售与营销环节发生的费用",
    "sust_operate_net_profit": "持续经营净利润：持续经营部分的净利润",
    "total_composite_income": "综合收益总额：净利润与其他综合收益合计",
    "total_operating_cost": "营业总成本：营业成本加期间费用及税金等",
    "total_operating_revenue": "营业总收入：营业收入（含利息/手续费收入等金融类）",
    "total_profit": "利润总额：营业利润加营业外收支净额",
    "update_time": "数据入库时间：COS 写入时间戳，仅作快内排序",
    "withdraw_insurance_contract_reserve": "提取保险合同准备金（保险类损益）",
    # ------------------------------------------------------------------
    # StockIndicator — 财务指标（报告期，比率类）
    # ------------------------------------------------------------------
    "adjusted_profit": "扣除非经常性损益后的净利润（扣非净利润）",
    "adjusted_profit_to_profit": "扣非净利润 / 净利润",
    "eps": "每股收益 EPS（元/股，摊薄口径）",
    "expense_to_total_revenue": "费用总额 / 营业总收入（期间费用率）",
    "financing_expense_to_total_revenue": "财务费用 / 营业总收入",
    "ga_expense_to_total_revenue": "管理费用 / 营业总收入",
    "goods_sale_and_service_to_revenue": "销售商品、提供劳务收到的现金 / 营业收入（收入含金量）",
    "gross_profit_margin": "销售毛利率：毛利 / 营业收入",
    "inc_net_profit_annual": "净利润同比增长率（近 12 个月/年度累计口径）",
    "inc_net_profit_to_shareholders_annual": "归母净利润同比增长率（近 12 个月/年度累计口径）",
    "inc_net_profit_to_shareholders_year_on_year": "归母净利润同比增长率（本期同比）",
    "inc_net_profit_year_on_year": "净利润同比增长率（本期同比）",
    "inc_operation_profit_annual": "营业利润同比增长率（近 12 个月/年度累计口径）",
    "inc_operation_profit_year_on_year": "营业利润同比增长率（本期同比）",
    "inc_return": "净资产收益率（ROE）同比增长率",
    "inc_revenue_annual": "营业收入同比增长率（近 12 个月/年度累计口径）",
    "inc_revenue_year_on_year": "营业收入同比增长率（本期同比）",
    "inc_total_revenue_annual": "营业总收入同比增长率（近 12 个月/年度累计口径）",
    "inc_total_revenue_year_on_year": "营业总收入同比增长率（本期同比）",
    "invesment_profit_to_profit": "投资收益 / 利润总额",
    "net_profit_margin": "销售净利率：净利润 / 营业收入",
    "net_profit_to_total_revenue": "净利润 / 营业总收入",
    "ocf_to_operating_profit": "经营活动现金流量净额 / 营业利润（盈利质量）",
    "ocf_to_revenue": "经营活动现金流量净额 / 营业收入",
    "operating_expense_to_total_revenue": "营业费用（销售+管理+研发+财务）/ 营业总收入",
    "operating_profit_to_profit": "营业利润 / 利润总额（主营利润占比）",
    "operation_profit_to_total_revenue": "营业利润 / 营业总收入（营业利润率）",
    "pub_date": "公告披露日：指标计算所用财报的披露日期，作为 PIT 知识时间",
    "report_period_end_date": "报告期截止日：指标对应财报的报告期",
    "roa": "总资产收益率 ROA：净利润 / 平均总资产",
    "roe": "净资产收益率 ROE：归母净利润 / 平均归母净资产",
    "value_change_profit": "公允价值变动损益 / 利润总额",
    # ------------------------------------------------------------------
    # StockDailyBar / StockDailyBarAdj — A 股日线（原始/后复权）
    # ------------------------------------------------------------------
    "open": "当日开盘价（原始币价）",
    "high": "当日最高价",
    "low": "当日最低价",
    "close": "当日收盘价",
    "pre_close": "前收盘价：昨日收盘价（除权除息已按交易所口径调整）",
    "volume": "当日成交量（股）",
    "amount": "当日成交额（元）",
    "vwap": "当日成交量加权均价（成交额/成交量）",
    "ret": "当日涨跌幅：收盘价相对前收盘的收益率",
    "high_limit": "当日涨停价",
    "low_limit": "当日跌停价",
    "adj_factor": "复权因子：原始价 × 因子 = 后复权价",
    "is_suspend": "当日是否停牌（布尔标志）",
    "symbol": "证券代码（如 000001.SZ），标的连接列",
    "trade_date": "交易日：日线表时间列",
    "adj_open": "后复权开盘价：Open × 复权因子",
    "adj_high": "后复权最高价：High × 复权因子",
    "adj_low": "后复权最低价：Low × 复权因子",
    "adj_close": "后复权收盘价：Close × 复权因子（收益计算的标准价格）",
    "adj_pre_close": "后复权前收盘价",
    "adj_amount": "后复权成交额（Amount × 复权因子）",
    "adj_vwap": "后复权成交量加权均价",
    "adj_high_limit": "后复权涨停价",
    "adj_low_limit": "后复权跌停价",
    "target_vwap_return_h01": "目标列：未来 1 日相对 VWAP 买入的前瞻收益（供调仓/标注，禁止作为因子输入）",
    "target_vwap_return_h05": "目标列：未来 5 日相对 VWAP 买入的前瞻收益（禁止作为因子输入）",
    "target_vwap_return_h10": "目标列：未来 10 日相对 VWAP 买入的前瞻收益（禁止作为因子输入）",
    "target_vwap_return_h20": "目标列：未来 20 日相对 VWAP 买入的前瞻收益（禁止作为因子输入）",
    # ------------------------------------------------------------------
    # StockMinuteBar / StockMinuteBarAdj — A 股分钟线（原始/后复权）
    # ------------------------------------------------------------------
    "minute_open": "该分钟开盘价",
    "minute_high": "该分钟最高价",
    "minute_low": "该分钟最低价",
    "minute_close": "该分钟收盘价",
    "minute_volume": "该分钟成交量（股）",
    "minute_amount": "该分钟成交额（元）",
    "minute_vwap": "该分钟成交量加权均价",
    "minute_update_time": "分钟数据入库时间戳",
    "quote_time": "分钟时间戳：标记分钟 K 线的结束时刻（09:31 = 09:30-09:31 那根 bar）",
    # ------------------------------------------------------------------
    # StockValuationDaily — 每日估值
    # ------------------------------------------------------------------
    "market_cap": "总市值：当日收盘总股本 × 股价（元）",
    "circulating_market_cap": "流通市值：流通股本 × 股价（元）",
    "a_market_cap": "A 股市值：仅 A 股流通部分市值（元）",
    "free_market_cap": "自由流通市值：剔除大股东及战略持股后的市值（元）",
    "capitalization": "总股本（股）",
    "circulating_cap": "流通股本（股）",
    "a_cap": "A 股股本（股）",
    "free_cap": "自由流通股本（股）",
    "pe_ratio": "市盈率 PE（最新一期年化口径）",
    "pe_ratio_lyr": "市盈率 PE（静态，最近年报口径）",
    "pe_ratio_ttm": "市盈率 PE（TTM，滚动 12 个月）",
    "pb_ratio": "市净率 PB：总市值 / 归母净资产",
    "ps_ratio": "市销率 PS：总市值 / 营业收入（TTM）",
    "pcf_ratio": "市现率 PCF：总市值 / 经营现金流净额",
    "pcf_ratio_2": "市现率 PCF（现金净增加额口径）",
    "dividend_yield": "股息率：近 12 个月现金分红 / 股价",
    "turnover_ratio": "换手率：成交量 / 流通股本",
    # ------------------------------------------------------------------
    # StockCapitalDaily — 每日股本
    # ------------------------------------------------------------------
    "total_capital": "总股本（股，当日快照）",
    "circulating_capital": "流通股本（股，当日快照）",
    # ------------------------------------------------------------------
    # StockTopTenShareholder — 十大股东
    # ------------------------------------------------------------------
    "share_number": "该股东持股数量（股）",
    "share_ratio": "该股东持股占总股本比例",
    "share_pledge": "该股东质押股份数量（股）",
    "share_freeze": "该股东被冻结股份数量（股）",
    "shareholder_rank": "股东名次（1-10，按持股比例降序）",
    "shareholder_name": "股东名称",
    "shareholder_id": "股东标识 ID（同一主体跨期可追踪）",
    "shareholder_class": "股东类别（机构 / 个人 / 产品等）",
    "shares_nature": "股份性质（流通股 / 限售股等）",
    # ------------------------------------------------------------------
    # StockTopTenFloatShareholder — 十大流通股东
    # ------------------------------------------------------------------
    "float_share_number": "该流通股东持股数量（股）",
    "float_share_ratio": "该流通股东持股占流通股本比例",
    "float_share_pledge": "该流通股东质押股份数量（股）",
    "float_share_freeze": "该流通股东被冻结股份数量（股）",
    "float_shareholder_rank": "流通股东名次（1-10）",
    "float_shareholder_name": "流通股东名称",
    "float_shareholder_id": "流通股东标识 ID",
    "float_shareholder_class": "流通股东类别（机构 / 个人 / 产品等）",
    "float_shares_nature": "流通股东股份性质",
    # ------------------------------------------------------------------
    # StockDividend — 分红送转
    # ------------------------------------------------------------------
    "cash_dividend": "每股现金股利（税前，元/股）",
    "stock_dividend": "送股比例：每股送红股数（股/股）",
    "stock_transfer": "转增比例：每股资本公积转增股数（股/股）",
    "right_reg_date": "股权登记日：享有本次分红送转权利的截止日",
    # ------------------------------------------------------------------
    # EtfDailyBar — ETF 日线
    # ------------------------------------------------------------------
    "etf_open": "ETF 当日开盘价",
    "etf_high": "ETF 当日最高价",
    "etf_low": "ETF 当日最低价",
    "etf_close": "ETF 当日收盘价",
    "etf_pre_close": "ETF 前收盘价",
    "etf_volume": "ETF 当日成交量（份）",
    "etf_amount": "ETF 当日成交额（元）",
    # ------------------------------------------------------------------
    # IndexDailyBar — 指数日线
    # ------------------------------------------------------------------
    "index_open": "指数当日开盘点位",
    "index_high": "指数当日最高点位",
    "index_low": "指数当日最低点位",
    "index_close": "指数当日收盘点位",
    "index_pre_close": "指数前收盘点位",
    "index_volume": "指数成分成交量（股）",
    "index_amount": "指数成分成交额（元）",
    # ------------------------------------------------------------------
    # IndexConstituent — 指数成分
    # ------------------------------------------------------------------
    "index_symbol": "指数代码（如 000300.SH），参数化数据集的必选参数",
    "index_weight": "成分股在指数中的权重（百分比）",
    # ------------------------------------------------------------------
    # StockIndustry / StockStatus
    # ------------------------------------------------------------------
    "industry_code": "行业分类代码（分组键，用于截面分组算子）",
    "industry_name": "行业名称",
    "change_date": "状态变更日期",
    "change_type": "状态变更类型（上市 / 暂停 / 恢复 / 退市等）",
    "public_status": "当前公开状态标签（上市 / 退市等）",
    "public_status_code": "状态编码（数值型标识）",
}

# ------------------------------------------------------------------
# 表名限定覆盖（优先于通用名条目）——同名字段在不同表口径不同
# ------------------------------------------------------------------
TABLE_FIELD_DESCRIPTIONS: dict[str, str] = {
    # StockDailyBarAdj：源列 AdjX = X × 复权因子；Volume 原始值；Return 原样
    'StockDailyBarAdj.open': '后复权开盘价：Open × 复权因子',
    'StockDailyBarAdj.high': '后复权最高价：High × 复权因子',
    'StockDailyBarAdj.low': '后复权最低价：Low × 复权因子',
    'StockDailyBarAdj.close': '后复权收盘价：Close × 复权因子（收益计算的标准价格）',
    'StockDailyBarAdj.pre_close': '后复权前收盘价：PreClose × 复权因子',
    'StockDailyBarAdj.amount': '后复权成交额：Amount × 复权因子',
    'StockDailyBarAdj.vwap': '后复权成交量加权均价：Vwap × 复权因子',
    'StockDailyBarAdj.high_limit': '后复权涨停价：HighLimit × 复权因子',
    'StockDailyBarAdj.low_limit': '后复权跌停价：LowLimit × 复权因子',
    'StockDailyBarAdj.volume': '当日成交量（股，原始值，不作复权调整）',
    'StockDailyBarAdj.ret': '当日涨跌幅（原始收益率，复权前后一致）',
    'StockDailyBarAdj.adj_factor': '复权因子：原始价 × 因子 = 后复权价',
    'StockDailyBarAdj.is_suspend': '当日是否停牌（布尔标志）',
    # StockMinuteBarAdj：分钟 bar 源列为后复权
    'StockMinuteBarAdj.minute_open': '后复权分钟开盘价：Open × 复权因子',
    'StockMinuteBarAdj.minute_high': '后复权分钟最高价：High × 复权因子',
    'StockMinuteBarAdj.minute_low': '后复权分钟最低价：Low × 复权因子',
    'StockMinuteBarAdj.minute_close': '后复权分钟收盘价：Close × 复权因子',
    'StockMinuteBarAdj.minute_volume': '该分钟成交量（股，原始值，不作复权调整）',
    'StockMinuteBarAdj.minute_amount': '后复权分钟成交额：Amount × 复权因子',
    'StockMinuteBarAdj.minute_vwap': '后复权分钟成交量加权均价：Vwap × 复权因子',
}
