#!/usr/bin/env python3
"""从 Week2 汇报因子定义生成 formulas/ 与 source/catalog.json。"""
from __future__ import annotations

import json
import sys
from pathlib import Path

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
if str(PACKAGE_ROOT) not in sys.path:
    sys.path.insert(0, str(PACKAGE_ROOT))

from lib.dsl_validate import validate_formula  # noqa: E402

WEEK2_FACTORS = [
    {
        "id": "w2_001",
        "slug": "vol_quantile_stress",
        "name_zh": "量能分位 × 应激动量",
        "cluster": "herd_stress",
        "rank_ic_pct": 4.99,
        "tier": "qualified",
        "formula": "clip(ema(ts_delta(close, 1) / delay(close, 1) * ts_rank(volume, 6) * (high - low), 12), -2.5, 2.5)",
        "note": "日收益 × 6日量能分位 × 日内振幅；EMA(12)+clip(±2.5)",
    },
    {
        "id": "w2_002",
        "slug": "herd_stress_cross",
        "name_zh": "羊群应激交叉",
        "cluster": "herd_stress",
        "rank_ic_pct": 4.92,
        "tier": "qualified",
        "formula": "clip(ema((close / delay(close, 5) - 1) * ts_rank(volume, 8) * (high - low), 12), -3, 3)",
        "note": "5日动量 × 8日量能分位 × 应激区间",
    },
    {
        "id": "w2_003",
        "slug": "log_range_gate",
        "name_zh": "量加权对数区间门控",
        "cluster": "herd_stress",
        "rank_ic_pct": 4.83,
        "tier": "qualified",
        "formula": "ema(ts_delta(close, 1) * log(1 + volume / ts_mean(volume, 5)) * (1 + min(2, max(0, (high - low - ts_mean(high - low, 5)) / ts_std(high - low, 5)))), 12)",
        "note": "ΔC（绝对涨跌额）× log量比 × 5日range z-score 加成",
    },
    {
        "id": "w2_004",
        "slug": "stress_range_vol",
        "name_zh": "应激区间 × 放量",
        "cluster": "herd_stress",
        "rank_ic_pct": 3.34,
        "tier": "qualified",
        "formula": "(high - low) * volume / ts_mean(volume, 20)",
        "note": "日内波动 × 相对20日均量",
    },
    {
        "id": "w2_005",
        "slug": "vol_weight_range_clip10",
        "name_zh": "量加权区间 clip EMA10",
        "cluster": "herd_stress",
        "rank_ic_pct": 4.50,
        "tier": "qualified",
        "formula": "ema(ts_delta(close, 1) / delay(close, 1) * volume / ts_mean(volume, 20) * (1 + min(2, max(0, (high - low - ts_mean(high - low, 10)) / ts_std(high - low, 10)))), 10)",
        "note": "收益×量比×10日range z-score",
    },
    {
        "id": "w2_006",
        "slug": "log_range_gate_z10",
        "name_zh": "对数区间门控 10日版",
        "cluster": "herd_stress",
        "rank_ic_pct": 4.79,
        "tier": "qualified",
        "formula": "ema(ts_delta(close, 1) * log(1 + volume / ts_mean(volume, 5)) * (1 + min(2, max(0, (high - low - ts_mean(high - low, 10)) / ts_std(high - low, 10)))), 12)",
        "note": "ΔC（绝对涨跌额）× log量比；zscore 窗口 10 日",
    },
    {
        "id": "w2_007",
        "slug": "vol_gated_surge",
        "name_zh": "波动率门控 Surge",
        "cluster": "intraday_pressure",
        "rank_ic_pct": 4.56,
        "tier": "qualified",
        "formula": "ema(if_else((high - low) > median(high - low, 20), close / open - 1, 0) * ts_max(volume, 20) / volume, 20)",
        "note": "日内方向 × 极端放量 × range 高于20日中位数才生效",
    },
    {
        "id": "w2_008",
        "slug": "tanh_gated_reversal",
        "name_zh": "Tanh 门控量确认动量",
        "cluster": "intraday_pressure",
        "rank_ic_pct": 4.53,
        "tier": "qualified",
        "formula": "tanh(2 * (high - low) / (2 * close - high - low) * ts_mean(close, 5) / ts_mean(high - low, 5))",
        "note": "日内反转位置 + tanh 压缩",
    },
    {
        "id": "w2_009",
        "slug": "intraday_vol_ratio",
        "name_zh": "日内收益 × 均量比",
        "cluster": "intraday_pressure",
        "rank_ic_pct": 4.30,
        "tier": "qualified",
        "formula": "ema((close / open - 1) * volume / ts_mean(volume, 20), 10)",
        "note": "日内涨跌方向 × 相对20日均量",
    },
    {
        "id": "w2_010",
        "slug": "reversal_cross_smooth",
        "name_zh": "反转交叉平滑版",
        "cluster": "intraday_pressure",
        "rank_ic_pct": 3.20,
        "tier": "qualified",
        "formula": "ts_mean((high - low) / (2 * close - high - low) * ts_mean(close, 5) / ts_mean(high - low, 5), 3)",
        "note": "日内反转核 × 3日平滑",
    },
    {
        "id": "w2_011",
        "slug": "stress_dir_clip25",
        "name_zh": "应激 dir clip 2.5 变体",
        "cluster": "intraday_pressure",
        "rank_ic_pct": 3.45,
        "tier": "qualified",
        "formula": "ema(max(0, (high - low - ts_mean(high - low, 40)) / ts_std(high - low, 40)) * min(2, volume / ts_mean(volume, 20)) * clip((high - low) / (close - open), -2.5, 2.5), 15)",
        "note": "应激累积 × 量比 × 方向 clip ±2.5",
    },
    {
        "id": "w2_012",
        "slug": "stress_dir_w25",
        "name_zh": "应激 dir w25 变体",
        "cluster": "intraday_pressure",
        "rank_ic_pct": 3.44,
        "tier": "qualified",
        "formula": "ema(max(0, (high - low - ts_mean(high - low, 40)) / ts_std(high - low, 40)) * min(2, volume / ts_mean(volume, 25)) * clip((high - low) / (close - open), -2, 2), 15)",
        "note": "量比基线 25 日，方向 clip ±2",
    },
    {
        "id": "w2_013",
        "slug": "adaptive_dir_vol",
        "name_zh": "自适应方向波动",
        "cluster": "dir_vol_volume",
        "rank_ic_pct": 4.32,
        "tier": "qualified",
        "formula": "ema(close / (high - low), 10) * ema(volume / ts_mean(volume, 25), 15) * ema(close / (close - open), 3)",
        "note": "波动 × 量能 × 方向 三因子乘积",
    },
    {
        "id": "w2_014",
        "slug": "sigmoid_vol_blend",
        "name_zh": "自适应 sigmoid 量能混合",
        "cluster": "dir_vol_volume",
        "rank_ic_pct": 3.85,
        "tier": "elite",
        "formula": "ema(close / (high - low), 8) * (sigmoid(5 * (volume - 0.85 * ts_mean(volume, 25))) * ema(volume, 10) + (1 - sigmoid(5 * (volume - 0.85 * ts_mean(volume, 25)))) * ema(volume, 30))",
        "note": "sigmoid 切换快/慢 EMA 量能混合",
    },
    {
        "id": "w2_015",
        "slug": "inverse_vol_momentum_v3",
        "name_zh": "逆波动门控动量 v3",
        "cluster": "dir_vol_volume",
        "rank_ic_pct": 3.77,
        "tier": "qualified",
        "formula": "(close / delay(close, 5) - 1) * (1.5 - 0.5 * ts_rank(ts_std(ts_delta(close, 1), 20), 20))",
        "note": "5日动量 × 逆波动权重",
    },
    {
        "id": "w2_016",
        "slug": "vol_weight_price_move",
        "name_zh": "量加权价格变动",
        "cluster": "vol_regime",
        "rank_ic_pct": 3.91,
        "tier": "elite",
        "formula": "ema(ts_delta(close, 1) / delay(close, 1) * volume / ts_mean(volume, 20), 5)",
        "note": "价量一致性核心因子",
    },
    {
        "id": "w2_017",
        "slug": "vol_break_continuous_gate",
        "name_zh": "波动率突破连续门控",
        "cluster": "vol_regime",
        "rank_ic_pct": 3.54,
        "tier": "qualified",
        "formula": "ema((divide(close - low, high - low) - 0.5) * divide(median(high - low, 20), high - low), 5)",
        "note": "区间位置 × median(range)/range 连续波动缩放",
    },
    {
        "id": "w2_018",
        "slug": "vol_regime_trend",
        "name_zh": "波动率 regime 趋势",
        "cluster": "vol_regime",
        "rank_ic_pct": 3.49,
        "tier": "qualified",
        "formula": "ema((close / delay(close, 5) - 1) * ts_max(volume, 20) / volume * (divide(median(high - low, 20), high - low) - 1), 5)",
        "note": "短动量 × 极端放量 × 波动率偏离",
    },
    {
        "id": "w2_019",
        "slug": "stress_accum_dir_vol",
        "name_zh": "应激累积 × 量权 × 方向",
        "cluster": "herd_stress",
        "rank_ic_pct": 3.45,
        "tier": "elite",
        "formula": "ema(max(0, (high - low - ts_mean(high - low, 40)) / ts_std(high - low, 40)) * min(2, volume / ts_mean(volume, 20)) * clip((high - low) / (close - open), -3, 3), 15)",
        "note": "应激累积 × 量比 × 方向 clip ±3",
    },
    {
        "id": "w2_020",
        "slug": "herd_vol_stress",
        "name_zh": "羊群 × 波动应激",
        "cluster": "herd_stress",
        "rank_ic_pct": 4.10,
        "tier": "qualified",
        "formula": "ema(close / (close - open) * median(volume, 10) / volume, 5)",
        "note": "代数化简：(H-L)/(C-O)*C/(H-L)=C/(C-O)；量能中位比",
    },
    {
        "id": "w2_021",
        "slug": "herd_simplified",
        "name_zh": "简化羊群",
        "cluster": "herd_stress",
        "rank_ic_pct": 3.27,
        "tier": "qualified",
        "formula": "ema((high - low) / (close - open) * median(volume, 10) / volume, 5)",
        "note": "去掉 stress range 的 ablation",
    },
    {
        "id": "w2_022",
        "slug": "asymmetric_range_ratio",
        "name_zh": "上涨/下跌不对称 range 比",
        "cluster": "order_imbalance",
        "rank_ic_pct": 3.28,
        "tier": "qualified",
        "formula": "-1 * ema(divide(divide(ts_sum(if_else(close <= open, high - low, 0), 20), ts_sum(if_else(close <= open, 1, 0), 20)), divide(ts_sum(if_else(close > open, high - low, 0), 20), ts_sum(if_else(close > open, 1, 0), 20))) * median(volume, 10) / volume, 2)",
        "note": "涨跌日条件均值比（汇报为条件 median，DSL 用 masked mean 近似）",
    },
    {
        "id": "w2_023",
        "slug": "order_imbalance_vol",
        "name_zh": "订单失衡 × 量比 EWM",
        "cluster": "order_imbalance",
        "rank_ic_pct": 3.10,
        "tier": "qualified",
        "formula": "ema((high - low) / (close - (high + low) / 2) * volume / ts_mean(volume, 20), 5)",
        "note": "收盘相对区间中点失衡 × 量比",
    },
    {
        "id": "w2_024",
        "slug": "sharpe_momentum_v2",
        "name_zh": "自适应波动率门控动量 v2",
        "cluster": "order_imbalance",
        "rank_ic_pct": 3.25,
        "tier": "qualified",
        "formula": "divide(close / delay(close, 5) - 1, ts_std(ts_delta(close, 1), 30))",
        "note": "5日动量 / 30日波动率",
    },
    {
        "id": "w2_025",
        "slug": "vol_confirm_binary",
        "name_zh": "量确认动量二元门控",
        "cluster": "order_imbalance",
        "rank_ic_pct": 3.20,
        "tier": "qualified",
        "formula": "(close / delay(close, 5) - 1) * volume / ts_mean(volume, 20) * sign(close - (high + low) / 2)",
        "note": "量确认动量 × 相对区间中点方向",
    },
    {
        "id": "w2_026",
        "slug": "range_pos_vol_gate",
        "name_zh": "区间位置量门控 mut",
        "cluster": "vol_regime",
        "rank_ic_pct": 3.09,
        "tier": "qualified",
        "formula": "ema(divide(close - low, high - low) * volume / ts_mean(volume, 20), 5)",
        "note": "区间位置 × 量比，EMA(5)",
    },
    {
        "id": "w2_027",
        "slug": "asymmetric_range_15d",
        "name_zh": "不对称 vol 15日窗",
        "cluster": "order_imbalance",
        "rank_ic_pct": 3.11,
        "tier": "qualified",
        "formula": "-1 * ema(divide(divide(ts_sum(if_else(close <= open, high - low, 0), 15), ts_sum(if_else(close <= open, 1, 0), 15)), divide(ts_sum(if_else(close > open, high - low, 0), 15), ts_sum(if_else(close > open, 1, 0), 15))) * median(volume, 10) / volume, 2)",
        "note": "条件均值比，窗口 15",
    },
    {
        "id": "w2_028",
        "slug": "asymmetric_range_ema5",
        "name_zh": "不对称 vol 6日 EMA5",
        "cluster": "order_imbalance",
        "rank_ic_pct": 3.28,
        "tier": "qualified",
        "formula": "-1 * ema(divide(divide(ts_sum(if_else(close <= open, high - low, 0), 20), ts_sum(if_else(close <= open, 1, 0), 20)), divide(ts_sum(if_else(close > open, high - low, 0), 20), ts_sum(if_else(close > open, 1, 0), 20))) * ema(volume, 5) / volume, 2)",
        "note": "条件均值比 + 量比基线 ema(volume,5)",
    },
]

# A.pdf — 9 个 Elite 因子（LQTP 统一评估框架汇报）
A_PDF_FACTORS = [
    {
        "id": "a_001",
        "slug": "intraday_vol_surge",
        "name_zh": "日内收益×量能 Surge",
        "cluster": "intraday_pressure",
        "rank_ic_pct": 4.52,
        "ic_pct": 2.54,
        "icir": 0.21,
        "rank_icir": 0.37,
        "tier": "elite",
        "source_pdf": "A.pdf",
        "formula": "ema((close / open - 1) * volume / ts_max(volume, 20), 20)",
        "note": "日内方向 × V/max(V,20)；EMA(20)",
    },
    {
        "id": "a_002",
        "slug": "herd_momentum_stress",
        "name_zh": "羊群动量×应激区间",
        "cluster": "herd_stress",
        "rank_ic_pct": 4.51,
        "ic_pct": 2.42,
        "icir": 0.24,
        "rank_icir": 0.37,
        "tier": "elite",
        "source_pdf": "A.pdf",
        "formula": "ema(ts_delta(close, 1) / delay(close, 1) * volume / ts_mean(volume, 5) * (high - low) / close, 5)",
        "note": "ΔC/C × V/MA(V,5) × (H-L)/C；EMA(5)",
    },
    {
        "id": "a_003",
        "slug": "dir_vol_volume_25d",
        "name_zh": "方向性波动×量能(25日基准)",
        "cluster": "dir_vol_volume",
        "rank_ic_pct": 4.32,
        "ic_pct": 2.97,
        "icir": 0.31,
        "rank_icir": 0.36,
        "tier": "elite",
        "source_pdf": "A.pdf",
        "formula": "ema(close / (high - low), 10) * ema(volume / ts_mean(volume, 25), 15) * ema((close - open) / close, 3)",
        "note": "C/(H-L) × V/MA(V,25) × (C-O)/C 三分量独立 EMA",
    },
    {
        "id": "a_004",
        "slug": "vol_confirm_ewm",
        "name_zh": "量确认动量(EWM平滑)",
        "cluster": "price_volume_confirm",
        "rank_ic_pct": 4.32,
        "ic_pct": 2.49,
        "icir": 0.22,
        "rank_icir": 0.34,
        "tier": "elite",
        "source_pdf": "A.pdf",
        "formula": "ema((close / delay(close, 5) - 1) * volume / ts_mean(volume, 20), 10)",
        "note": "5日动量 × 量比；EWM(10)（汇报未展开公式，按逻辑簇还原）",
    },
    {
        "id": "a_005",
        "slug": "intraday_reversal",
        "name_zh": "日内反转",
        "cluster": "intraday_reversal",
        "rank_ic_pct": 3.94,
        "ic_pct": 3.41,
        "icir": 0.37,
        "rank_icir": 0.37,
        "tier": "elite",
        "source_pdf": "A.pdf",
        "formula": "-1 * (2 * close - high - low) / (high - low) * ts_mean(high - low, 5) / ts_mean(close, 5)",
        "note": "Williams 型收盘位置 × MA(H-L,5)/MA(C,5)",
    },
    {
        "id": "a_006",
        "slug": "vol_adjusted_momentum",
        "name_zh": "量调整动量",
        "cluster": "momentum",
        "rank_ic_pct": 3.85,
        "ic_pct": 2.40,
        "icir": 0.22,
        "rank_icir": 0.30,
        "tier": "elite",
        "source_pdf": "A.pdf",
        "formula": "ema((close / delay(close, 3) - 1) * volume / ts_mean(volume, 20), 5)",
        "note": "3日短周期动量 × 量比；EMA(5)（汇报未展开公式，按逻辑簇还原）",
    },
    {
        "id": "a_007",
        "slug": "adaptive_dir_vol_cross",
        "name_zh": "自适应方向波动交叉",
        "cluster": "dir_vol_volume",
        "rank_ic_pct": 3.75,
        "ic_pct": 2.42,
        "icir": 0.27,
        "rank_icir": 0.34,
        "tier": "elite",
        "source_pdf": "A.pdf",
        "formula": "ema(close / (high - low), 8) * ema((close - open) / close, 10) * ema(volume / ts_mean(volume, 25), 15)",
        "note": "波动×方向×自适应量能三分量交叉（汇报未展开公式，按逻辑簇还原）",
    },
    {
        "id": "a_008",
        "slug": "vol_gated_momentum_ratio",
        "name_zh": "波动门控动量×量比",
        "cluster": "vol_regime",
        "rank_ic_pct": 3.65,
        "ic_pct": 2.33,
        "icir": 0.23,
        "rank_icir": 0.30,
        "tier": "elite",
        "source_pdf": "A.pdf",
        "formula": "(close / delay(close, 5) - 1) * (0.5 + 0.5 * ts_rank(ts_atr(high, low, close, 14) / close, 20)) * volume / ts_mean(volume, 20)",
        "note": "Ret5 × [0.5+0.5×RankPct(ATR14/C)] × V/MA(V,20)",
    },
    {
        "id": "a_009",
        "slug": "vol_confirm_5d",
        "name_zh": "量确认动量(5日)",
        "cluster": "price_volume_confirm",
        "rank_ic_pct": 3.62,
        "ic_pct": 2.39,
        "icir": 0.23,
        "rank_icir": 0.29,
        "tier": "elite",
        "source_pdf": "A.pdf",
        "formula": "(close / delay(close, 5) - 1) * volume / ts_mean(volume, 20)",
        "note": "经典 5日量确认动量（无额外平滑）",
    },
]

FACTORS = WEEK2_FACTORS + A_PDF_FACTORS


def main() -> int:
    formulas_dir = PACKAGE_ROOT / "formulas"
    formulas_dir.mkdir(parents=True, exist_ok=True)

    catalog = {
        "source": "Week2 汇报.pdf + A.pdf — 孙海崴 A股价量因子",
        "schema_version": "week2_pv.v1",
        "week2_count": len(WEEK2_FACTORS),
        "a_pdf_count": len(A_PDF_FACTORS),
        "factor_count": len(FACTORS),
        "notation_map": {
            "C": "close",
            "O": "open",
            "H": "high",
            "L": "low",
            "V": "volume",
            "ΔC/C": "ts_delta(close, 1) / delay(close, 1)",
            "ΔC": "ts_delta(close, 1)",
            "ATR14": "ts_atr(high, low, close, 14)",
            "RankPct(x,n)": "ts_rank(x, n)",
            "ts_pct(C,n)": "close / delay(close, n) - 1",
            "MA(V,n)": "ts_mean(volume, n)",
            "rank_pct(V,n)": "ts_rank(volume, n)",
            "Q(x,n,50)": "median(x, n)",
            "z(range,n)": "(range - ts_mean(range,n)) / ts_std(range,n)",
        },
        "factors": [],
    }

    fail = 0
    for item in FACTORS:
        ok, msg = validate_formula(item["formula"])
        entry = {**item, "dsl_valid": ok, "validation_error": msg or None}
        catalog["factors"].append(entry)
        if not ok:
            fail += 1
            print("FAIL", item["id"], msg)
            continue

        out = formulas_dir / f"{item['id']}_{item['slug']}.dsl"
        out.write_text(item["formula"].strip() + "\n", encoding="utf-8")

    source_dir = PACKAGE_ROOT / "source"
    source_dir.mkdir(parents=True, exist_ok=True)
    (source_dir / "week2_factors_catalog.json").write_text(
        json.dumps(catalog, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    print(f"built {len(FACTORS)} formulas, failures={fail}")
    return fail


if __name__ == "__main__":
    raise SystemExit(main())
