"""Multi-fidelity evaluation: Stage0-5 profile-bound tiers (R61-FI-036).

The pre-existing module already modelled an L0-L4 ``MultiFidelityScheduler``
and ``PromotionCriteria`` funnel.  R61-FI-036 (plan §31) keeps that machinery
and adds the *canonical Stage 0-5* model over it:

- ``EvaluationStage`` — the 6 canonical stages (Stage0 static → Stage5 sealed
  test);
- ``StageEvaluationProfile`` — a Stage bound to a named QE EvidenceProfile
  *id string* (e.g. ``CHEAP_SCREEN_CN_1D``); FO never imports QE, so the
  binding is a validated string reference that resolves only inside QE's
  ``QE_EVIDENCE_PROFILE`` policy;
- ``StageProfileRegistry`` — versioned Stage0-5 bindings;
- ``StageCostTelemetry`` — the plan §31 per-stage cost record (wall/CPU/GPU/
  bytes/candidate count/metric count) with a mutable accumulator so the
  scheduler can later calibrate budgets empirically;
- ``Stage2DiagnosisBudget`` — the diagnosis-directed candidate budget the
  Stage 2 profile carries (generated by FI-034's
  :func:`~factor_optimizer.policy.repair_registry.diagnosis_search_budget`).

The fidelity integer the runner passes to an ``EvaluationProtocol`` maps onto
``FidelityTier`` values 0..4 (pre-existing contract); the Stage names/order
below document which QE EvidenceProfile runs at each point of the funnel.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple

from factor_optimizer.policy.repair_registry import (
    DiagnosisSearchBudget,
    RepairBudgetConfig,
    diagnosis_search_budget,
)
from factor_optimizer.policy.repair import DiagnosisKind


class FidelityTier(Enum):
    """
    Evaluation fidelity tiers from cheapest to most expensive.

    L0: Ultra-fast screening (small sample, single metric)
    L1: Fast screening (moderate sample, basic metrics)
    L2: Standard evaluation (full sample, core metrics)
    L3: High-fidelity (full sample, extended metrics, robustness)
    L4: Production-grade (full sample, all metrics, cross-validation)
    """
    L0 = 0
    L1 = 1
    L2 = 2
    L3 = 3
    L4 = 4


# ---------------------------------------------------------------------------
# Canonical Stage 0-5 (plan §31) with QE EvidenceProfile bindings
# ---------------------------------------------------------------------------


class EvaluationStage(Enum):
    """Canonical multi-fidelity stages (plan §31, R61-FI-036).

    Stage0 static (near-zero factor-value cost; DSL/FE checks only — never a
    QE profile) → Stage5 sealed test (one-shot, single winner).  The plan's
    Stage1-5 each run a named QE EvidenceProfile id (string reference).
    """

    STAGE0 = 0
    STAGE1 = 1
    STAGE2 = 2
    STAGE3 = 3
    STAGE4 = 4
    STAGE5 = 5

    @property
    def fidelity_tier(self) -> FidelityTier:
        """Map a stage onto the legacy L0-L4 fidelity integer contract.

        Stage0 (static) needs no factor-value evaluation; it is represented
        by L0 in the runner contract but never runs a QE profile.  Stage1-4
        map onto L0-L3 (progressive full-evaluation tiers); Stage5 (sealed
        one-shot) maps onto L4.
        """
        mapping = {
            EvaluationStage.STAGE0: FidelityTier.L0,
            EvaluationStage.STAGE1: FidelityTier.L0,
            EvaluationStage.STAGE2: FidelityTier.L1,
            EvaluationStage.STAGE3: FidelityTier.L2,
            EvaluationStage.STAGE4: FidelityTier.L3,
            EvaluationStage.STAGE5: FidelityTier.L4,
        }
        return mapping[self]


def _validate_profile_id(profile_id: str) -> str:
    if not isinstance(profile_id, str) or not profile_id.strip():
        raise ValueError(
            "evidence_profile must be a non-empty QE EvidenceProfile id string"
        )
    if not profile_id.isupper():
        raise ValueError(
            f"evidence_profile {profile_id!r} must be an upper-case "
            "QE EvidenceProfile id (e.g. CHEAP_SCREEN_CN_1D)"
        )
    return profile_id


@dataclass(frozen=True)
class StageEvaluationProfile:
    """A multi-fidelity stage bound to a named QE EvidenceProfile (plan §31).

    Attributes:
        stage: The canonical stage.
        evidence_profile: QE EvidenceProfile id string (policy
            ``QE_EVIDENCE_PROFILE``).  String reference only — FO never
            imports QE.  Fail-closed on empty / non-upper tokens so a typo'd
            id cannot silently become an unvalidated lower-case default.
        policy_id: Stable policy family (``FO_EVALUATION_STAGE``).
        policy_version: Semantic-version string.
    """

    stage: EvaluationStage
    evidence_profile: str = ""
    policy_id: str = "FO_EVALUATION_STAGE"
    policy_version: str = "1.0.0"

    def __post_init__(self) -> None:
        if not isinstance(self.stage, EvaluationStage):
            raise ValueError("stage must be an EvaluationStage member")
        object.__setattr__(
            self,
            "evidence_profile",
            _validate_profile_id(self.evidence_profile),
        )
        if not isinstance(self.policy_id, str) or not self.policy_id.strip():
            raise ValueError("policy_id must be a non-empty string")
        if not isinstance(self.policy_version, str) or not self.policy_version.strip():
            raise ValueError("policy_version must be a non-empty string")


#: Canonical Stage1-5 → QE EvidenceProfile bindings (plan §31, R61-FI-036).
DEFAULT_STAGE_PROFILES: Tuple[StageEvaluationProfile, ...] = (
    # Stage0 runs static checks only — no factor-value QE profile.
    StageEvaluationProfile(
        stage=EvaluationStage.STAGE0,
        evidence_profile="CHEAP_SCREEN_CN_1D",
        policy_id="FO_EVALUATION_STAGE",
        policy_version="1.0.0",
    ),
    # Stage1 GPU cheap screen: dead-vs-repairable + generate diagnoses.
    StageEvaluationProfile(
        stage=EvaluationStage.STAGE1,
        evidence_profile="CHEAP_SCREEN_CN_1D",
        policy_id="FO_EVALUATION_STAGE",
        policy_version="1.0.0",
    ),
    # Stage2 diagnosis-directed repair: bounded candidate budgets.
    StageEvaluationProfile(
        stage=EvaluationStage.STAGE2,
        evidence_profile="SHAPE_DIAGNOSTIC_CN_1D",
        policy_id="FO_EVALUATION_STAGE",
        policy_version="1.0.0",
    ),
    # Stage3 full validation: RAW + top 2-3 candidates, all core horizons.
    StageEvaluationProfile(
        stage=EvaluationStage.STAGE3,
        evidence_profile="FULL_VALIDATION_CN_1D",
        policy_id="FO_EVALUATION_STAGE",
        policy_version="1.0.0",
    ),
    # Stage4 expensive statistical evidence: only Pareto/near-Pareto survivors.
    StageEvaluationProfile(
        stage=EvaluationStage.STAGE4,
        evidence_profile="EXPENSIVE_STATISTICAL_CN_1D",
        policy_id="FO_EVALUATION_STAGE",
        policy_version="1.0.0",
    ),
    # Stage5 sealed test: one-shot winner only.
    StageEvaluationProfile(
        stage=EvaluationStage.STAGE5,
        evidence_profile="MODEL_FEATURE_DIAGNOSTIC_CN_1D",
        policy_id="FO_EVALUATION_STAGE",
        policy_version="1.0.0",
    ),
)


class StageProfileRegistry:
    """Versioned registry mapping each EvaluationStage to its evidence profile.

    Immutable after construction; the default carries the canonical
    Stage0-5 bindings (plan §31).  ``profile_for`` resolves a stage; an
    unknown stage fails closed with a typed ``ValueError``.
    """

    def __init__(
        self,
        profiles: Sequence[StageEvaluationProfile],
        policy_id: str = "FO_EVALUATION_STAGE",
        policy_version: str = "1.0.0",
    ) -> None:
        if not isinstance(profiles, (list, tuple)) or not profiles:
            raise ValueError("stage profile registry requires a non-empty profile list")
        if not all(isinstance(p, StageEvaluationProfile) for p in profiles):
            raise TypeError(
                "stage profiles must be StageEvaluationProfile instances"
            )
        stages = [p.stage for p in profiles]
        if len(stages) != len(set(stages)):
            raise ValueError("stage profile registry has duplicate stages")
        self._profiles: Dict[EvaluationStage, StageEvaluationProfile] = {
            p.stage: p for p in profiles
        }
        self._policy_id = policy_id
        self._policy_version = policy_version
        for p in profiles:
            if p.policy_id != policy_id:
                raise ValueError(
                    f"stage profile {p.stage.name} policy_id {p.policy_id!r} "
                    f"does not match registry {policy_id!r}"
                )

    @classmethod
    def default(cls) -> "StageProfileRegistry":
        """The canonical Stage0-5 registry (plan §31)."""
        return cls(DEFAULT_STAGE_PROFILES)

    @property
    def policy_id(self) -> str:
        return self._policy_id

    @property
    def policy_version(self) -> str:
        return self._policy_version

    def profile_for(self, stage: EvaluationStage | int) -> StageEvaluationProfile:
        if isinstance(stage, int):
            try:
                stage = EvaluationStage(stage)
            except ValueError:
                raise ValueError(f"unknown evaluation stage {stage!r}") from None
        try:
            return self._profiles[stage]
        except KeyError:
            raise ValueError(
                f"evaluation stage {stage.name} has no registered profile"
            ) from None

    @property
    def stages(self) -> Tuple[EvaluationStage, ...]:
        return tuple(sorted(self._profiles, key=lambda s: s.value))

    def evidence_profiles(self) -> Dict[str, str]:
        """Stage name → evidence-profile id (string reference) mapping."""
        return {
            p.stage.name: p.evidence_profile for p in self._profiles.values()
        }

    def __len__(self) -> int:
        return len(self._profiles)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "policy_id": self._policy_id,
            "policy_version": self._policy_version,
            "profiles": [
                {
                    "stage": p.stage.name,
                    "evidence_profile": p.evidence_profile,
                    "policy_id": p.policy_id,
                    "policy_version": p.policy_version,
                }
                for p in self._profiles.values()
            ],
        }


# ---------------------------------------------------------------------------
# Stage 2 diagnosis-directed candidate budget
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Stage2DiagnosisBudget:
    """The diagnosis-directed candidate plan Stage 2 executes (plan §31).

    Wraps the FI-034 :class:`DiagnosisSearchBudget` generator output with the
    Stage-2 profile binding.  The candidate ceiling is the soft total budget's
    upper bound (6-12) — Stage 2 never floods hundreds of candidates.

    Attributes:
        stage_profile: The Stage2 StageEvaluationProfile.
        plan: The concrete diagnosis-directed candidate plan.
        budget_config: The config that produced the plan (defaults E5).
    """

    stage_profile: StageEvaluationProfile
    plan: DiagnosisSearchBudget
    budget_config: RepairBudgetConfig = field(default_factory=RepairBudgetConfig)

    def __post_init__(self) -> None:
        if not isinstance(self.stage_profile, StageEvaluationProfile):
            raise TypeError("stage_profile must be a StageEvaluationProfile")
        if self.stage_profile.stage is not EvaluationStage.STAGE2:
            raise ValueError(
                "Stage2DiagnosisBudget requires the STAGE2 profile"
            )
        if not isinstance(self.plan, DiagnosisSearchBudget):
            raise TypeError("plan must be a DiagnosisSearchBudget")

    @property
    def candidate_ceiling(self) -> int:
        return self.plan.total_candidates_ceiling

    def to_dict(self) -> Dict[str, Any]:
        return {
            "stage_profile": self.stage_profile,
            "plan": self.plan.to_dict(),
            "budget_config": self.budget_config,
        }


def build_stage2_budget(
    diagnoses: Sequence[DiagnosisKind | str],
    *,
    evidence: Optional[Mapping[str, object]] = None,
    budget_config: Optional[RepairBudgetConfig] = None,
    stage_registry: Optional[StageProfileRegistry] = None,
) -> Stage2DiagnosisBudget:
    """Build the Stage-2 diagnosis-directed budget for a factor (plan §31).

    The candidate budget is bounded 6-12 (soft); the Stage-2 profile binding
    is resolved from the versioned Stage registry (default
    ``SHAPE_DIAGNOSTIC_CN_1D`` for Stage 2).
    """
    stage_registry = stage_registry or StageProfileRegistry.default()
    profile = stage_registry.profile_for(EvaluationStage.STAGE2)
    plan = diagnosis_search_budget(
        diagnoses,
        evidence=evidence,
        config=budget_config,
    )
    return Stage2DiagnosisBudget(
        stage_profile=profile,
        plan=plan,
        budget_config=budget_config or RepairBudgetConfig(),
    )


# ---------------------------------------------------------------------------
# Per-stage cost telemetry (plan §31)
# ---------------------------------------------------------------------------


@dataclass
class StageCostTelemetry:
    """Mutable per-stage cost accumulator (plan §31 cost telemetry).

    Attributes:
        stage: Stage this telemetry records.
        evidence_profile: QE EvidenceProfile id string (or ``"static"`` for
            Stage0 which never runs a QE profile).
        wall_time_s: Wall-clock seconds spent in this stage.
        cpu_time_s: CPU seconds spent.
        gpu_time_s: GPU kernel seconds (0 when no GPU kernel ran).
        h2d_d2h_bytes: Host↔device transfer bytes (0 when none).
        peak_vram_bytes: Peak device memory bytes (0 when unknown).
        bytes_read: Data bytes read by the stage.
        candidate_count: Number of candidates evaluated in the stage.
        metric_count: Number of metrics computed across the stage's
            evaluations.
        factor_value_cache_hits: Factor-value cache hits.
        policy_id / policy_version: Versioned stage-profile policy that this
            telemetry was recorded under.
    """

    stage: EvaluationStage
    evidence_profile: str = ""
    wall_time_s: float = 0.0
    cpu_time_s: float = 0.0
    gpu_time_s: float = 0.0
    h2d_d2h_bytes: int = 0
    peak_vram_bytes: int = 0
    bytes_read: int = 0
    candidate_count: int = 0
    metric_count: int = 0
    factor_value_cache_hits: int = 0
    policy_id: str = "FO_EVALUATION_STAGE"
    policy_version: str = "1.0.0"

    def __post_init__(self) -> None:
        if not isinstance(self.stage, EvaluationStage):
            raise ValueError("stage must be an EvaluationStage member")
        object.__setattr__(
            self,
            "evidence_profile",
            "static" if self.stage is EvaluationStage.STAGE0 else _validate_profile_id(
                self.evidence_profile
            ),
        )
        for name in (
            "wall_time_s",
            "cpu_time_s",
            "gpu_time_s",
        ):
            value = getattr(self, name)
            if isinstance(value, bool) or not isinstance(value, (int, float)):
                raise ValueError(f"{name} must be a number")
            if value < 0:
                raise ValueError(f"{name} must be non-negative")
            object.__setattr__(self, name, float(value))
        for name in (
            "h2d_d2h_bytes",
            "peak_vram_bytes",
            "bytes_read",
            "candidate_count",
            "metric_count",
            "factor_value_cache_hits",
        ):
            value = getattr(self, name)
            if isinstance(value, bool) or not isinstance(value, int):
                raise ValueError(f"{name} must be an int")
            if value < 0:
                raise ValueError(f"{name} must be non-negative")

    def record_evaluation(
        self,
        *,
        candidate_count: int = 1,
        metric_count: int = 0,
        wall_time_s: float = 0.0,
        cpu_time_s: float = 0.0,
        gpu_time_s: float = 0.0,
        h2d_d2h_bytes: int = 0,
        peak_vram_bytes: int = 0,
        bytes_read: int = 0,
        factor_value_cache_hits: int = 0,
    ) -> None:
        """Accumulate one evaluation's costs into this stage telemetry."""
        for value in (candidate_count, metric_count, h2d_d2h_bytes,
                      peak_vram_bytes, bytes_read, factor_value_cache_hits):
            if isinstance(value, bool) or not isinstance(value, int) or value < 0:
                raise ValueError("telemetry int counters must be non-negative ints")
        for value in (wall_time_s, cpu_time_s, gpu_time_s):
            if isinstance(value, bool) or not isinstance(value, (int, float)) or value < 0:
                raise ValueError("telemetry time counters must be non-negative numbers")
        self.candidate_count += candidate_count
        self.metric_count += metric_count
        self.wall_time_s += float(wall_time_s)
        self.cpu_time_s += float(cpu_time_s)
        self.gpu_time_s += float(gpu_time_s)
        self.h2d_d2h_bytes += h2d_d2h_bytes
        self.peak_vram_bytes = max(self.peak_vram_bytes, peak_vram_bytes)
        self.bytes_read += bytes_read
        self.factor_value_cache_hits += factor_value_cache_hits

    def to_dict(self) -> Dict[str, Any]:
        return {
            "stage": self.stage.name,
            "evidence_profile": self.evidence_profile,
            "wall_time_s": self.wall_time_s,
            "cpu_time_s": self.cpu_time_s,
            "gpu_time_s": self.gpu_time_s,
            "h2d_d2h_bytes": self.h2d_d2h_bytes,
            "peak_vram_bytes": self.peak_vram_bytes,
            "bytes_read": self.bytes_read,
            "candidate_count": self.candidate_count,
            "metric_count": self.metric_count,
            "factor_value_cache_hits": self.factor_value_cache_hits,
            "policy_id": self.policy_id,
            "policy_version": self.policy_version,
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "StageCostTelemetry":
        values = dict(data)
        values["stage"] = EvaluationStage[values["stage"]]
        return cls(**values)


@dataclass
class MultiStageCostTelemetry:
    """Accumulates one :class:`StageCostTelemetry` per stage (plan §31).

    Provides the scheduler a single record point: ``record_stage`` looks up
    (or creates) the stage's accumulator and merges the evaluation costs.
    This is a plain record — it performs no real GPU timing.
    """

    stage_profiles: StageProfileRegistry = field(
        default_factory=StageProfileRegistry.default
    )
    _per_stage: Dict[EvaluationStage, StageCostTelemetry] = field(
        default_factory=dict, init=False, repr=False
    )

    def telemetry_for(self, stage: EvaluationStage) -> StageCostTelemetry:
        if stage not in self._per_stage:
            profile = self.stage_profiles.profile_for(stage)
            self._per_stage[stage] = StageCostTelemetry(
                stage=stage,
                evidence_profile=profile.evidence_profile,
                policy_id=profile.policy_id,
                policy_version=profile.policy_version,
            )
        return self._per_stage[stage]

    def record_stage(
        self,
        stage: EvaluationStage,
        *,
        candidate_count: int = 1,
        metric_count: int = 0,
        wall_time_s: float = 0.0,
        cpu_time_s: float = 0.0,
        gpu_time_s: float = 0.0,
        h2d_d2h_bytes: int = 0,
        peak_vram_bytes: int = 0,
        bytes_read: int = 0,
        factor_value_cache_hits: int = 0,
    ) -> None:
        """Record one evaluation's costs into *stage*'s accumulator."""
        self.telemetry_for(stage).record_evaluation(
            candidate_count=candidate_count,
            metric_count=metric_count,
            wall_time_s=wall_time_s,
            cpu_time_s=cpu_time_s,
            gpu_time_s=gpu_time_s,
            h2d_d2h_bytes=h2d_d2h_bytes,
            peak_vram_bytes=peak_vram_bytes,
            bytes_read=bytes_read,
            factor_value_cache_hits=factor_value_cache_hits,
        )

    def report(self) -> Dict[str, Any]:
        """Structured telemetry report (stage -> StageCostTelemetry.to_dict())."""
        return {
            stage.name: self._per_stage[stage].to_dict()
            for stage in sorted(self._per_stage, key=lambda s: s.value)
        }

    def to_dict(self) -> Dict[str, Any]:
        return {
            "stage_profiles": self.stage_profiles.to_dict(),
            "per_stage": self.report(),
        }


@dataclass(frozen=True)
class FidelitySpec:
    """
    Specification for evaluation at a specific fidelity tier.

    Attributes:
        tier: Fidelity tier level
        sample_fraction: Fraction of full dataset to use
        num_metrics: Number of metrics to compute
        cross_validate: Whether to perform cross-validation
        compute_robustness: Whether to compute robustness checks
        cost_multiplier: Relative cost compared to L0
        typical_duration_ms: Typical evaluation duration
    """
    tier: FidelityTier
    sample_fraction: float
    num_metrics: int
    cross_validate: bool = False
    compute_robustness: bool = False
    cost_multiplier: float = 1.0
    typical_duration_ms: int = 100

    def __post_init__(self):
        if not 0 < self.sample_fraction <= 1.0:
            raise ValueError("sample_fraction must be in (0, 1]")
        if self.num_metrics < 1:
            raise ValueError("num_metrics must be >= 1")
        if self.cost_multiplier <= 0:
            raise ValueError("cost_multiplier must be > 0")


# Standard fidelity tier configurations
FIDELITY_TIERS: Dict[FidelityTier, FidelitySpec] = {
    FidelityTier.L0: FidelitySpec(
        tier=FidelityTier.L0,
        sample_fraction=0.05,
        num_metrics=1,
        cross_validate=False,
        compute_robustness=False,
        cost_multiplier=1.0,
        typical_duration_ms=50,
    ),
    FidelityTier.L1: FidelitySpec(
        tier=FidelityTier.L1,
        sample_fraction=0.15,
        num_metrics=3,
        cross_validate=False,
        compute_robustness=False,
        cost_multiplier=3.0,
        typical_duration_ms=150,
    ),
    FidelityTier.L2: FidelitySpec(
        tier=FidelityTier.L2,
        sample_fraction=0.50,
        num_metrics=5,
        cross_validate=False,
        compute_robustness=False,
        cost_multiplier=10.0,
        typical_duration_ms=500,
    ),
    FidelityTier.L3: FidelitySpec(
        tier=FidelityTier.L3,
        sample_fraction=1.0,
        num_metrics=8,
        cross_validate=True,
        compute_robustness=True,
        cost_multiplier=25.0,
        typical_duration_ms=2000,
    ),
    FidelityTier.L4: FidelitySpec(
        tier=FidelityTier.L4,
        sample_fraction=1.0,
        num_metrics=12,
        cross_validate=True,
        compute_robustness=True,
        cost_multiplier=50.0,
        typical_duration_ms=5000,
    ),
}


@dataclass
class PromotionCriteria:
    """
    Criteria for promoting a candidate to higher fidelity.

    Attributes:
        min_score: Minimum score at current tier to promote
        top_k_fraction: Fraction of top candidates to promote
        min_improvement: Minimum improvement over baseline
        require_all: Whether all criteria must be met (vs any)
    """
    min_score: Optional[float] = None
    top_k_fraction: Optional[float] = None
    min_improvement: Optional[float] = None
    require_all: bool = True

    def should_promote(
        self,
        score: float,
        rank: int,
        total: int,
        baseline_score: Optional[float] = None
    ) -> bool:
        """
        Check if candidate meets promotion criteria.

        Args:
            score: Candidate's score at current tier
            rank: Rank among peers (0 = best)
            total: Total number of candidates at this tier
            baseline_score: Baseline score for improvement comparison

        Returns:
            True if candidate should be promoted
        """
        checks = []

        if self.min_score is not None:
            checks.append(score >= self.min_score)

        if self.top_k_fraction is not None:
            threshold_rank = 0
            if total > 0 and self.top_k_fraction > 0:
                threshold_rank = max(1, int(total * self.top_k_fraction))
            checks.append(rank < threshold_rank)

        if self.min_improvement is not None and baseline_score is not None:
            improvement = score - baseline_score
            checks.append(improvement >= self.min_improvement)

        if not checks:
            return True

        return all(checks) if self.require_all else any(checks)


class MultiFidelityScheduler:
    """
    Schedules evaluation across fidelity tiers.

    Progressive evaluation: start at L0, promote promising candidates to higher tiers.
    """

    def __init__(
        self,
        tier_specs: Optional[Dict[FidelityTier, FidelitySpec]] = None,
        promotion_criteria: Optional[Dict[FidelityTier, PromotionCriteria]] = None,
    ):
        """
        Initialize scheduler.

        Args:
            tier_specs: Custom tier specifications (uses defaults if None)
            promotion_criteria: Criteria for promoting between tiers
        """
        self.tier_specs = tier_specs or FIDELITY_TIERS
        self.promotion_criteria = promotion_criteria or self._default_promotion()

    def _default_promotion(self) -> Dict[FidelityTier, PromotionCriteria]:
        """Default promotion criteria for each tier."""
        return {
            FidelityTier.L0: PromotionCriteria(top_k_fraction=0.5),
            FidelityTier.L1: PromotionCriteria(top_k_fraction=0.4),
            FidelityTier.L2: PromotionCriteria(top_k_fraction=0.3),
            FidelityTier.L3: PromotionCriteria(top_k_fraction=0.2),
        }

    def get_spec(self, tier: FidelityTier) -> FidelitySpec:
        """Get specification for a fidelity tier."""
        return self.tier_specs[tier]

    def next_tier(self, current: FidelityTier) -> Optional[FidelityTier]:
        """Get next higher fidelity tier."""
        if current == FidelityTier.L4:
            return None
        return FidelityTier(current.value + 1)

    def should_promote(
        self,
        current_tier: FidelityTier,
        score: float,
        rank: int,
        total: int,
        baseline_score: Optional[float] = None,
    ) -> bool:
        """
        Check if candidate should be promoted to next tier.

        Args:
            current_tier: Current fidelity tier
            score: Candidate's score at current tier
            rank: Rank among peers
            total: Total candidates at this tier
            baseline_score: Optional baseline for improvement check

        Returns:
            True if candidate meets promotion criteria
        """
        if current_tier not in self.promotion_criteria:
            return False

        criteria = self.promotion_criteria[current_tier]
        return criteria.should_promote(score, rank, total, baseline_score)

    def estimate_cost(self, tier: FidelityTier, num_evaluations: int = 1) -> float:
        """Estimate cost for evaluations at given tier."""
        spec = self.get_spec(tier)
        return spec.cost_multiplier * num_evaluations

    def estimate_duration_ms(self, tier: FidelityTier, num_evaluations: int = 1) -> int:
        """Estimate duration for evaluations at given tier."""
        spec = self.get_spec(tier)
        return spec.typical_duration_ms * num_evaluations

    def optimal_tier_for_budget(self, remaining_budget: float) -> FidelityTier:
        """Determine highest tier affordable with remaining budget."""
        for tier in reversed(list(FidelityTier)):
            if self.estimate_cost(tier) <= remaining_budget:
                return tier
        return FidelityTier.L0
