# -*- coding: utf-8 -*-
"""Fail-closed operator surface policy for factor formula authoring.

Only canonicals explicitly listed in ``DAILY_CANONICALS`` may enter new daily
factor DSL formulas. Runtime registration is not sufficient: newly registered
operators remain ``unclassified`` until reviewed and assigned deliberately.
"""
from __future__ import annotations

from typing import Iterable, Literal

OperatorSurface = Literal[
    "daily", "research", "unsafe", "legacy", "internal", "unclassified", "all"
]

DAILY_CANONICALS: frozenset[str] = frozenset(
    {
        'ADX',
        'ADXR',
        'AROON',
        'AROON_down',
        'AROON_up',
        'ATR',
        'ATR_WILDER',
        'BollingerBands',
        'BollingerLower',
        'BollingerUpper',
        'CCI',
        'DPO',
        'KAMA',
        'MACD',
        'MACD_hist',
        'MACD_line',
        'MACD_signal',
        'MOM',
        'OBV',
        'ROC',
        'RSI',
        'RSI_WILDER',
        'Slope',
        'StochasticD',
        'StochasticK',
        'TRIX',
        'WMA',
        'WilliamsR',
        'abs',
        'acos',
        'add',
        'aggr_top_n',
        'and_',
        'arg',
        'asin',
        'at_imax',
        'at_imin',
        'atan',
        'atan2',
        'avg',
        'beta',
        'blom_transform',
        'c_count',
        'c_mean',
        'c_percentile',
        'c_std',
        'c_sum',
        'clip',
        'cbrt',
        'ceil',
        'close_gap',
        'coalesce',
        'cos',
        'cosh',
        'coskewness_to_market',
        'cot',
        'count',
        'cs_demean',
        'cs_mad',
        'cs_mad_zscore',
        'cs_pct_rank',
        'cs_quantile',
        'cs_rank_01',
        'cs_regression',
        'cs_resid',
        'csc',
        'cum_count',
        'cum_delta',
        'cum_first',
        'cum_max',
        'cum_min',
        'cum_positive_streak',
        'cum_prod',
        'cum_sum',
        'cum_top_n_avg',
        'cum_top_n_sum',
        'cumulative_returns',
        'current_ratio',
        'debt_to_equity',
        'ts_decay_linear',
        'ts_delay',
        'digital_count',
        'div_or_default',
        'div_or_null',
        'divide',
        'downside_beta',
        'ts_ema',
        'eq',
        'ewm',
        'ewm_corr',
        'ewm_cov',
        'ewm_std',
        'ewm_var',
        'exp',
        'exp_neg',
        'expanding_max',
        'expanding_mean',
        'expanding_min',
        'expanding_rank',
        'expanding_std',
        'expanding_sum',
        'expanding_zscore',
        'ffill',
        'fillna',
        'fillna_const',
        'first_not_null',
        'fix',
        'flex_max',
        'flex_min',
        'floor',
        'ge',
        'geometric_mean',
        'group_count',
        'group_decay_linear',
        'group_max',
        'group_mean',
        'group_min',
        'group_neutralize',
        'group_normalize',
        'group_percentile',
        'group_rank',
        'group_std',
        'group_sum',
        'group_winsorize',
        'group_zscore',
        'gt',
        'harmonic_mean',
        'hump_decay',
        'identity',
        'idio_skew',
        'idio_vol',
        'ifnan',
        'intercept',
        'intraday_vwap_deviation',
        'inverse',
        'is_finite',
        'is_inf',
        'is_infinite',
        'is_nan',
        'is_not_null',
        'is_null',
        'le',
        'lerp',
        'log',
        'log10',
        'log2',
        'log_abs',
        'log_fill_invalid',
        'log_returns',
        'lt',
        'maximum',
        'micro_amihud_hf',
        'micro_bipower_var',
        'micro_jump_indicator',
        'micro_kyle_lambda',
        'micro_mid_return',
        'micro_realized_vol',
        'micro_spread',
        'micro_trade_imbalance',
        'micro_vpin',
        'minimum',
        'multiply',
        'nan_to_num',
        'ne',
        'neg',
        'normalize',
        'not_',
        'open_gap',
        'operating_margin',
        'or_',
        'power',
        'prev',
        'price_spread_deviation',
        'product',
        'protected_div',
        'protected_log',
        'protected_sqrt',
        'quantile',
        'quick_ratio',
        'rank',
        'rank_corr',
        'rank_pct',
        'rank_transform',
        'rankavg_transform',
        'real_turnover_rate',
        'residual_momentum_capm',
        'reverse',
        'rolling_beta',
        'rolling_beta_to_market',
        'round',
        'safe_div_null',
        'saturate',
        'scale',
        'sec',
        'sigmoid',
        'sign',
        'signed_log',
        'signed_power',
        'signed_sqrt',
        'sin',
        'sinh',
        'size_neutralize',
        'slope',
        'sqrt',
        'sqrt_abs',
        'square',
        'std_agg',
        'stdp',
        'subtract',
        'sum_agg',
        'tail_beta',
        'tan',
        'tanh',
        'tm_top_n_avg',
        'tm_top_n_sum',
        'trade_when',
        'truncate',
        'ts_argmax',
        'ts_argmin',
        'ts_autocorr',
        'ts_beta',
        'ts_bottom_n_avg',
        'ts_bottom_n_sum',
        'ts_corr',
        'ts_cov',
        'ts_decay_exp_window',
        'ts_delta',
        'ts_kurt',
        'ts_log_return',
        'ts_mad',
        'ts_max',
        'ts_max_buildup',
        'ts_mean',
        'ts_median',
        'ts_min',
        'ts_moment',
        'ts_pct',
        'ts_poly2_coeff',
        'ts_poly2_resid',
        'ts_product',
        'ts_quantile',
        'ts_rank',
        'ts_ratio',
        'ts_regression_slope',
        'ts_sharpe',
        'ts_skew',
        'ts_std',
        'ts_sum',
        'ts_sum_decay',
        'ts_time_slope',
        'ts_top_n_avg',
        'ts_top_n_std',
        'ts_topk_sum',
        'ts_var',
        'ts_zscore',
        'tukey_transform',
        'unitize',
        'van_der_waerden_transform',
        'varp',
        'volatility',
        'vp_weighted_price',
        'vpmacd',
        'vpmacd_signal',
        'vwap',
        'wavg',
        'weighted_mean',
        'where',
        'winsorize',
        'winsorize_mean',
        'wsum',
        'zscore',
    }
)

RESEARCH_ONLY_CANONICALS: frozenset[str] = frozenset(
    {
        'ACF',
        'Mode',
        'autocorr',
        'avg2',
        'bartlett_test',
        'cdf_chi2',
        'cdf_f',
        'cdf_normal',
        'cdf_t',
        'chi_square_test',
        'complex',
        'conj',
        'convolve',
        'corr_test',
        'causal_linear_extrapolate',
        'correlate',
        'decimate',
        'durbin_watson_test',
        'dropna',
        'eig',
        'fft',
        'filter_bandpass',
        'filter_highpass',
        'filter_lowpass',
        'filter_notch',
        'granger_causality',
        'ifft',
        'imag',
        'interpolate',
        'jarque_bera_test',
        'kendall_corr_test',
        'kpss_test',
        'ks_test',
        'lasso',
        'levene_test',
        'lilliefors_test',
        'lu_decompose',
        'mat_add',
        'mat_determinant',
        'mat_inverse',
        'mat_multiply',
        'mat_rank',
        'mat_subtract',
        'mat_transpose',
        'max_drawdown',
        'pacf',
        'pca',
        'pdf_chi2',
        'pdf_f',
        'pdf_normal',
        'pdf_t',
        'phase',
        'polar',
        'qr_decompose',
        'quarter',
        'quarter_from_cumulative',
        'quantile_normal',
        'quantile_t',
        'r_squared',
        'real',
        'regress',
        'residual',
        'ridge',
        'row_avg',
        'row_beta',
        'row_corr',
        'row_count',
        'row_kurt',
        'row_max',
        'row_median',
        'row_min',
        'row_prod',
        'row_skew',
        'row_std',
        'row_sum',
        'row_var',
        'sem',
        'sharpe_ratio',
        'spearman_corr_test',
        'stationarity_test',
        'svd',
        'ttm',
        'ttm_from_cumulative',
        'ttm_from_quarterly',
        'ttest_one_sample',
        'ttest_paired',
        'ttest_two_samples',
        'unwrap',
        'wavelet',
        'wavelet_denoise',
        'yoy',
        'yoy_by_period',
    }
)

UNSAFE_CANONICALS: frozenset[str] = frozenset(
    {
    }
)

LEGACY_ONLY_CANONICALS: frozenset[str] = frozenset(
    {
        'cube',
    }
)

INTERNAL_ONLY_CANONICALS: frozenset[str] = frozenset(
    {
        'constant',
    }
)

HIDDEN_DAILY_NAMES: frozenset[str] = frozenset(
    {
        'cube',
        'cumulative_max',
        'cumulative_mean',
        'cumulative_min',
        'fmax',
        'fmin',
        'inv',
        'reciprocal',
        'sqr',
    }
)


def classify_canonical(canonical: str) -> str:
    """Return the reviewed surface; unknown registrations fail closed."""
    if canonical in DAILY_CANONICALS:
        return "daily"
    if canonical in RESEARCH_ONLY_CANONICALS:
        return "research"
    if canonical in UNSAFE_CANONICALS:
        return "unsafe"
    if canonical in LEGACY_ONLY_CANONICALS:
        return "legacy"
    if canonical in INTERNAL_ONLY_CANONICALS:
        return "internal"
    return "unclassified"


def is_dsl_name_allowed(name: str, canonical: str, *, surface: OperatorSurface = "daily") -> bool:
    """Return whether a registry name is visible on the requested surface."""
    if surface == "all":
        return True
    category = classify_canonical(canonical)
    if surface == "daily":
        return category == "daily" and name not in HIDDEN_DAILY_NAMES
    if surface == "research":
        return category == "research"
    if surface == "unsafe":
        return category == "unsafe"
    if surface == "legacy":
        return category == "legacy" or name in HIDDEN_DAILY_NAMES
    if surface == "internal":
        return category == "internal"
    if surface == "unclassified":
        return category == "unclassified"
    raise ValueError(f"unknown operator surface: {surface!r}")


def unclassified_canonicals(canonicals: Iterable[str]) -> tuple[str, ...]:
    """Return runtime canonicals that have not passed surface review."""
    return tuple(sorted(c for c in canonicals if classify_canonical(c) == "unclassified"))


def surface_summary(canonicals: Iterable[str]) -> dict[str, int]:
    """Count canonical operators by reviewed surface."""
    out = {
        "daily": 0,
        "research": 0,
        "unsafe": 0,
        "legacy": 0,
        "internal": 0,
        "unclassified": 0,
    }
    for canonical in canonicals:
        out[classify_canonical(canonical)] += 1
    return out
